### ISSUE TITLE
Example doesn't show added todos after all are removed

### ISSUE THREAD

**Issue by kasbah** [FormidableLabs/urql#103]
1. Start the example
2. Remove all existing todos
3. Add a todo

Result: 
It won't show the newly added todo until you hit "Refetch (Skip Cache)"

Expected:
It should always show newly added todos.

**Comment by kitten** [comment]
v1 is released now which means this issue was resolved / is out-of-date 👌

Some docs and a proper announcement for v1 are still in progress in pending. It's completely usable so far but the API has changed, so I have to ask for some more patience, but everything will be ready quite soon ✌️

Extra note: this is expected and broken behaviour for the default cache and a known limitation. This will be resolved when we introduce a normalised cache for more complex data requirements
