### ISSUE TITLE
Webpack 5 resolution issues

### ISSUE THREAD

**Issue by ScriptedAlchemy** [FormidableLabs/urql#1086]
Please update your package.json correctly for Webapck Resolution in mjs/esm

```
[0] ModuleNotFoundError: Module not found: Error: Can't resolve 'graphql/language/visitor' in '/Volumes/lulu_dev/ecom-web-app/node_modules/@urql/core/dist'
[0] Did you mean 'visitor.mjs'?
[0] BREAKING CHANGE: The request 'graphql/language/visitor' failed to resolve only because it was resolved as fully specified
[0] (probably because the origin is a '*.mjs' file or a '*.js' file where the package.json contains '"type": "module"').
[0] The extension in the request is mandatory for it to be fully specified.
[0] Add the extension to the request.
```

urql version & exchanges: latest

**Steps to reproduce**

build on webpack v5

**Comment by kitten** [comment]
I suppose this is one of these issues that goes away with `javascript/auto` being added back to the mix. Well given that that's unlikely to be set up by default, yes, I agree, we'll have to fix this 😅

**Comment by ScriptedAlchemy** [comment]
ive patched it with the mjs javascript/auto loader trick. 

Just flagging it since We recommend users don't depend on resolutions but rather report to authors :P

**Comment by kitten** [comment]
Yea, we'll have to double check whether there's anything else we'll now need to update 😅😅

We're fixing this here first since that's the source of the issue: https://github.com/kitten/babel-plugin-modular-graphql/pull/1

I would've thought that Webpack would actually now switch to `javascript/auto` automatically when a sub-module of an ESM/exports-enabled package isn't exports-enabled, since we had issues before with similar stuff, which was marked as fixed in an issue somewhere. Oh well

**Comment by ScriptedAlchemy** [comment]
Apparently, the typical esm standard or whatever that we set in npm isn't quite correct or something. 

I suppose it's another explicit thing webpack prefers. Dropping polyfills makes things a lot more visible. 

Didn't ask too many questions about the reason the loader was removed. But I'd suppose it's "correct" or faster to be able to parse and resolve fields off the package file

**Comment by kitten** [comment]
I'd say it's arguably incorrect since `graphql` has no exports fields, hence Webpack shouldn't assume that it should be resolved the same as the package that uses it. Because that's how we get into resolution inconsistencies again depending on what package imports from it 😅

But yea anyway, doesn't help us, we'll probably issue a fix next week

**Comment by ScriptedAlchemy** [comment]
Haha yep it's been inconvenient. Thank you though!
