### ISSUE TITLE
(graphcache) - cache.resolve(parent, ...) doesn't seem to work

### ISSUE THREAD

**Issue by nghiepit** [FormidableLabs/urql#1207]
Hi guys,

After upgrade to `@urql/exchange-graphcache@3.3.1` `cache.resolve` doesn't seem to work always return `null` value.

```js
export const cache = cacheExchange({
  resolvers: {
    City: {
      name(parent, args, cache) {
        const id = cache.resolve(parent, "id");
        const name = cache.resolve(parent, "name");

        console.log({ id, name }); // null , null

        return `ID: ${id} - ` + name;
      }
    }
  }
});
```
`urql: 1.11.4`
`@urql/exchange-graphcache: 3.3.1`

**Steps to reproduce**
Check log tab
https://codesandbox.io/s/headless-wildflower-ynjsk

**The repo older version still work**
https://codesandbox.io/s/prod-monad-gmvyk

**Comment by kitten** [comment]
This probably needs a change in the documentation, but this is still working as intended. What's happened is that basically `__typename` won't be added to entities anymore automatically by Graphcache but in-order, like for a normal field, only if it's defined. Obviously since we add `__typename` fields to query documents, it'll always be (in some form) defined for each selection set. But it may be added later on. https://github.com/FormidableLabs/urql/pull/1185

I believe the documentation sometimes speaks about using `cache.resolve(parent, ...)`, however afaik that has never been safe. This isn't safe because the `parent` may not have its `id` field (or any other keyable field) added to it by the time the resolver with `cache.resolve` is reached.

The safe method here is to use `info.parentKey`, e.g. `cache.resolve(info.parentKey, 'name')`.

**Comment by nghiepit** [comment]
Thanks, @kitten I will change to `info.parentKey` instead.

**Comment by kitten** [comment]
I've discussed this with @JoviDeCroock and we came to the conclusion that this actually _should_ be supported. We did use it ourselves in the documentation and it's a pretty intuitive way to resolve fields gradually from a parent, instead of using `info.parentKey`, so I'm opening a patch that automatically _aliases_ `parent` to `info.parentKey` in all cases.

**Comment by nghiepit** [comment]
The new`graphqlcache@3.3.2` still doesn't work for me.
https://codesandbox.io/s/condescending-dream-zf7uu?file=/utils/urql.js

**Comment by kitten** [comment]
@nghiepit Nice catch! I believe I've actually forgotten to enable the additional case we were after. Follow up PR has been filed
