### ISSUE TITLE
RFC: Normalizing parameters of useMutation

### ISSUE THREAD

**Issue by ostrebler** [FormidableLabs/urql#1261]
## Summary

`useQuery` has a declarative approach and accepts a configuration object as parameter, with variables and all. On the other hand `useMutation` has a more functional approach, only takes the mutation document as parameter, and one has to pass variables and other options on each call (or use function composition, which isn't always create for keeping stable references).

## Proposed Solution

I propose to apply the `useQuery` philosophy to `useMutation` : 

```ts
const [result, addTodo] = useMutation({
  mutation: AddTodoDocument,
  variables: { listId: props.id }
})
```

- If variables come from state or props, this could be a way to enforce `addTodo`'s stable identity ;
- It unifies the design logic between both hooks ;
- You would have room to add more configs to the hook, including a `onCompleted` callback, further reducing the need to compose functions to do advanced stuff.

**Comment by kitten** [comment]
There's an issue for this already where we closed this but I can elaborate on why we decided against this again here ✌️

First of all, this isn't a matter of functional v non-functional. Having parameters passed as an object doesn't make the parameters anything else. Also adding a second argument, for context, was proposed in another issue, which to add some information here is the only argument / input that would even be up to be added. (But it's also available as a second argument on `executeMutation`)

Our API design is always focused on encouraging specific patterns while discouraging others; similarly, this pattern is conscious because `useMutation` is used very differently from `useQuery`. The former is always called imperatively at some point, and encouraging `executeMutation` to be wrapped is a pattern that we want people to prefer rather than managing a second set of state or effects to synchronise mutation inputs.

So to keep this short, on a surface level it's tempting to make all three hooks identical, however diving a little deeper, the situations in which mutations are used are very different from queries, and one API leads to very different API over the other from being used, especially when someone first migrated to hooks.

**Comment by ostrebler** [comment]
Yes, I understand the choice. Thanks for your explanation.

**Comment by kitten** [comment]
Oh just a note, (not necessarily for you, but just so I can use this as a link in the future :heart:)

The `useMutation` hook still takes an input of `DocumentNode | string`, which has been pointed out. This may seem counter-inutitive, after all I'm arguing above that it's a very imperative trigger. The reason why this is the case is because the mutation document will determine a fixed shape of the result, which the hook may store and provide too. So the "pure" imperative alternative is actually `client.mutation` and `useMutation` takes this single input because it's the only input that will determine its type and provide a consistent shapeof the result.
