### ISSUE TITLE
[GraphCache] Undocumented optional argument 'variables' for writeFragment

### ISSUE THREAD

**Issue by kaiba42** [FormidableLabs/urql#1305]
## Summary

The method `writeFragment` for GraphCache accepts a optional argument called `variables`, as shown in the type definition below:

```javascript
writeFragment<T = Data, V = Variables>(fragment: DocumentNode | TypedDocumentNode<T, V>, data: T, variables?: V): void;
```

However, there is no documentation for this argument, and how it might be used. I assume it ties into the [experimental features](https://github.com/graphql/graphql-js/pull/1141) surrounding variables for fragments that have been adopted in packages like [graphql-tag](https://github.com/apollographql/graphql-tag/pull/167), and are being currently discussed in [this thread](https://github.com/graphql/graphql-spec/issues/204) for the GraphQL spec.

## Proposed Solution

A bit of documentation on how this argument can be used would be great. I'm not sure if using variables in fragments is supported by the `gql` util exported from urql, and I'm not sure if using variables in fragments demands a particular GraphQL server implementation (e.g. using Apollo). Would love to get some clarity on this.

Thanks for all your work on urql! 
It's a truly awesome client 😄

**Comment by kitten** [comment]
This doesn't yet tie into the new feature, since it isn't "main line" yet but the GraphQL spec does allow variables to be used in fragments. This is a little confusing since that won't make much sense unless that fragment is written right next to a query, but is presumably for practical reasons since the grammar is unaltered for fragments and operations.

We do have this argument consequentially since it may be needed in some cases, and it's good to reserve it for this experimental feature too. Hence we assume most won't need to use it or need to know about it and will furthermore find it if they're looking for it; like yourself 😛💖

The API docs do mention this with an inline code example: https://formidable.com/open-source/urql/docs/api/graphcache/#readfragment

**Comment by kaiba42** [comment]
Ah, the `readFragment` docs, of course. I can imagine that fragments with variables that have a default value, or are nullable, can stand on their own without being next to a corresponding query. That could introduce the possibility for some tough debugging when used unintentionally though...

Anyways, thanks for the swift reply!
