### ISSUE TITLE
"TypeError: b is not a function" when mocking executeMutation

### ISSUE THREAD

**Issue by baldurpan** [FormidableLabs/urql#1325]
I'm getting this error in unit testing when using jest.fn to mock mutations, like explained in the urql testing documentation.
Strangely enough, this doesn't happen when I define the mocks inside the test. 

It's also worth pointing out that this error doesn't happen if I don't use jest.fn, but if course then I cannot assert executeMutation using expect().

**urql version:**

 Latest

**Steps to reproduce**

Here is a test repo for demonstration (Includes a working test and a failing test):
https://github.com/baldurpan/urql-mutation-test

**Comment by aurthurm** [comment]
facing the same issue here

**Comment by kitten** [comment]
I'd assume this happens because between the start of your run and the test itself the hoisted `executeMutation: jest.fn()` function is reset, meaning that it doesn't execute your mocked return value anymore and doesn't return the value as expected.

It's probably returning `undefined` by the time as the test runs as I can reproduce the error even when calling `jest.fn().mockReturnValue(...)` until I move `executeMutation.mockReturnValue(...)` to the body of the test function. This is also fixed when I move the instantion of the mocked client to a `beforeEach` clause.

I'd expect this to happen because the tests set up the `@testing-library` environment which extends `expect` and probably also resets the mocks. I suppose we can update the docs to reflect this, but it isn't a bug per se.
