### ISSUE TITLE
Cannot update a component (`Component`) while rendering a different component (`OtherComponent`).

### ISSUE THREAD

**Issue by danbeneventano** [FormidableLabs/urql#1382]
Getting this error in any component where I'm using `useQuery`. Using React and the following exchanges:
- @urql/devtools
- dedupExchange
- @urql/exchange-graphcache
- @urql/exchange-auth
- @urql/exchange-multipart-fetch
- subscriptionExchange

The stack trace points to this line:

https://github.com/FormidableLabs/urql/blob/47eaff17fcf72684eb12bd1009d3014f91a81c86/packages/react-urql/src/hooks/useQuery.ts#L149

**Comment by kitten** [comment]
Hiya :wave:

Just a quick note, we recognise this issue from a previous fix we had to do on a prior implementation of our React hooks bindings. That being said, usually we'd ask for more details that follow our bug template and possibly provide a reproduction: https://raw.githubusercontent.com/FormidableLabs/urql/main/.github/ISSUE_TEMPLATE/Bug_report.md

To give you more information on what's going on here; because the hooks have the option to use React suspense and suspend on any changes, they perform checks during render to determine whether their state is out-of-date and whether they need to request a change. When that change happens they briefly poll the client for a synchronous check on whether the new state is already ready without fetching against the API. When this result comes back _all `useQuery` hooks with the same input see this result_ and will trigger an update. This is something that the React team has put an explicit warning into the reconciler for.

That being said, this will only happen when:
- `useQuery` is mounted (or updated) with a query and set of variables
- A second `useQuery` hook is mounted (or updated) elsewhere with the same query and same set of variables

Hence, I do have to warn you, while we will mute this warning in a patch with the PR that's linked, this is a slight problem in GraphQL apps, since it shouldn't be necessary to create multiple query hooks with the same inputs and its more advisable to hoist as many data requirements as possible to the top of a page and to let the rest of the components reuse this same data (passing and splitting it via props)

So that's just a side note on the issue in general ✌️

**Comment by styxlab** [comment]
Still seeing this issue in latest `urql` version. Stack points to the following line:

https://github.com/FormidableLabs/urql/blob/ef4b5b002d31e17d84fb41e5feb24d2200c9656f/packages/react-urql/src/hooks/useQuery.ts#L156

So, #1383 does not fix this for me. I will follow the tipp to hoist the query, but this somewhat goes against what React hooks are invented for.

**Comment by danbeneventano** [comment]
Yeah, I'm still getting this error occasionally. I agree that this is against the point of react hooks

**Comment by kitten** [comment]
@danbeneventano I'm sorry you're still having trouble with this. Curiously we do have several apps that also use shared hook state extensively. Can you point to a reproduction with the latest version of urql and React? If not, we'll have to see whether it occurs in the apps we have, but I haven't seen this for several versions

**Comment by danbeneventano** [comment]
> @danbeneventano I'm sorry you're still having trouble with this. Curiously we do have several apps that also use shared hook state extensively. Can you point to a reproduction with the latest version of urql and React? If not, we'll have to see whether it occurs in the apps we have, but I haven't seen this for several versions

I'll see if I can produce a reproduction, but it's been happening very unpredictably (maybe related to network speed)

**Comment by styxlab** [comment]
Just two comments:

@danbeneventano Don't think this is related to network as the issue occurs in my local development environment. 
@kitten: This is "just a warning", so it can be overlooked easily.

Unfortunately the issue occurs in a larger code base that I cannot share, so I cannot promise a reproduction. The general pattern in my case:

- 2 identical(!) useQuery 
- the second useQuery is in a child of the first useQuery but many levels down the React tree
- problem is triggered, when I call the query re-execution function of the hook
- it does not matter, if I call the re-execution function in the parent or the child, problem is present in both cases

I hope this description at least gives some hints on how this may be reproduced.

**Comment by ostrebler** [comment]
@kitten Same error here as @danbeneventano, without any duplicate query. I simply have something like this :

```typescript
export default function List({ project, principles, renderItem }: Props) {
  const [filters, setFilters] = useListVariables({});
  const [{ data, fetching }] = useEngineeringArticlesQuery({ // generated by codegen
    variables: {
      ...filters,
      principles,
      projectId: project?.id
    }
  });
  return (
    <ListView
      loading={fetching}
      content={data?.engineeringArticles}
      renderItem={renderItem ?? (article => <Item.Admin article={article} />)}
    />
  );
}
```

When props change, thus `variables` changes : 

```
index.js:1 Warning: Cannot update a component (`Page`) while rendering a different component (`List`). To locate the bad setState() call inside `List`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render
    at List
    at div
    at div
    at Card
    ......
```

**Comment by styxlab** [comment]
@kitten: Could you please re-open this issue (or shall we make a new one?). The issue is hard to debug and makes using `urql hooks` a nightmare in larger code-bases.

**Comment by kitten** [comment]
@ostrebler @styxlab We have `urql` active in a lot of projects that are sufficiently large where we haven't encountered this, so I'd actually guess on a mis-use of `executeQuery` or a separate hook that isn't in `urql` causing this, so without a reproduction I won't open an issue since that'd mean taking a stab in the dark 😅

We also don't reopen old issues, since the cause will never be the same and they wouldn't track resolution correctly anyway. So if you have a reproduction please feel free to open an issue.

**Comment by ostrebler** [comment]
@kitten  What do you mean by misuse of executeQuery? It's not another non-urql hook causing this, I made sure of that. It's a fact that it comes from useQuery, and without a duplicate query in my case. So there is something to investigate here. 

It seems very hard to reproduce in a demo, because when the codebase is extremely large, the multiple factors causing this could be in a million places...

**Comment by styxlab** [comment]
@kitten: Okay, I will try to make a reproduction and open a new issue if I succeed.

**Comment by kitten** [comment]
@ostrebler that's just one example of what could cause this: Running any `Client` operations during render. Our hooks actually shield themselves from this since only one cause can be attributed to our hooks: mounting. So if we don't have a repro (which actually after the fix for this issue was never again attributed to our hooks 😅) we're in the dark since any update from one component during rendering of another triggers this warning.

One thing that you could look at is the `Page` component, since there's seemingly an update there that's caused by `List`. Maybe a runaway state change during render?

**Comment by ostrebler** [comment]
@kitten Hello. I wasn't able to find the cause of the error back then. I'm commenting here because I'm getting it again, this time I can pinpoint a specific code modification that leads to it.

When I have two queries like this : 

```ts
const [resultA] = useQuery({ query: QueryADocument });
const [resultB] = useQuery({ query: QueryBDocument });
```

I don't get the error. However, pausing the second to wait for the first triggers the error : 

```ts
const [resultA] = useQuery({ query: QueryADocument });
const [resultB] = useQuery({ query: QueryBDocument, pause: !resultA.data });
```

Btw I'm sorry I'm in a rush, I don't have time to setup a proper reproduction. I might do it in the futur if I don't find another cause for this error.

**Comment by bryansum** [comment]
FWIW I was seeing this error and this was fixed by `2.0.4` for me: https://github.com/FormidableLabs/urql/pull/1722

**Comment by nandorojo** [comment]
I'm seeing this in `2.0.5`. It seems like two different components are fetching the same query, but with different fields. As a result, one is updating the other. A bit hard to reproduce, since it feels like a race condition, but I'll try if no one else has reproduced.

**Comment by styxlab** [comment]
I am seeing this issue even with one hook (e.g. when switching between pages):
```
Warning: Cannot update a component (`Navbar`) while rendering a different component (`Navbar`).
```
with
```
export default function Navbar(): ReactElement {
   const [plan] = usePlanQuery()
}
```
I suspect this issue is due to missing garbage collection when the component gets out of scope. I managed to find a workaround as follows:

```
export default function Navbar(): ReactElement {
   const ref = useRef()

   const [plan] = usePlanQuery({ pause: !ref.current })
}
```

**Comment by Coobaha** [comment]
@kitten @JoviDeCroock this is still happening after switch to `use-sync-external-store` https://github.com/FormidableLabs/urql/pull/2164

**Comment by kitten** [comment]
So, since some people have been missing this, I'll cross-post it here for awareness. This is basically a pinned announcement re. us reverting the `useSyncExternalStore` refactor: https://github.com/FormidableLabs/urql/issues/2309
