### ISSUE TITLE
`reexecuteQuery` works only with `requestPolicy: "network-only"`

### ISSUE THREAD

**Issue by Epimodev** [FormidableLabs/urql#1395]
Hello Formidable team 👋

I'm using urql on a project and since version `2.0.1`, the function to reexecute a query seems broken.  
At the moment, my team find a workaround by adding a context with `requestPolicy: "network-only"` in `useQuery` hook.  
Even if `requestPolicy: "network-only"` is set in client, `reexecuteQuery` works only if I add `requestPolicy: "network-only"` in `useQuery` hook.  

urql version: `2.0.1`  
exchanges: default exchanges `[dedupExchange, cacheExchange, fetchExchange]`  

**Steps to reproduce**

I created a codesandbox available here: https://codesandbox.io/s/urql-reexecutequery-poc-ogf2f

**Expected behavior**
Each time I call `reexecuteQuery`, an http request should be send without setting `requestPolicy` in `useQuery`.  
In the codesandbox, `nbInterval` and `nbReexecuteQuery` should always be equals.

**Actual behavior**
If I didn't set `requestPolicy` in `useQuery`, `reexecuteQuery` doesn't send a new http request.  
In the codesandbox, we can see `nbReexecuteQuery` stays 0 whereas `nbInterval` is well incremented

Edit: I forgot to add a detail: I'm using `suspense`, and when I disable it, there are 2 requests send each time I call `reexecuteQuery` function.

**Comment by JoviDeCroock** [comment]
By default the caching-strategy used in these requests is `cache-first` this means that if you do `reexecuteQuery` you'll hit your cache boundary by default. If you'd use `cache-and-network` or `network-only` only then the fetch-layer will be hit to refresh this query.

Basically because there is a result in cache we'll never hit the `fetchExchange` boundary.

**Comment by Epimodev** [comment]
Thanks a lot @JoviDeCroock for your answer and reactivity!  

I try to disable cache by removing `cacheExchange` and I've got the same behaviour.  
And if I set `network-only` un my urql client, I think it should become `network-only` by default for all my `useQuery` in my app.

**Comment by kitten** [comment]
I'm having a bit of trouble working through your expected behaviour and example here. I can see that you've set `requestPolicy: 'network-only'` on the client. However, that's very likely to give you unexpected behaviour.

This means that your initial state will never be present and that, if React decides to double mount this component, it would issue two pending requests before it then actually attempts the request.

When you call `reexecuteQuery` to refetch data then you can pass `reexecuteQuery({ requestPolicy: 'network-only' })` of course to refresh the data from the API only. You shouldn't add this to the hook as the same principle applies; if you instruct the hook (or by extension) to skip the cache by default then you may get very odd behaviour as you start relying only on component state to hold the response.

You've got `setNbReexecuteQuery` inside the `fetchOptions` function, which is supposed to be a sideeffect-less function. This means that you'll instruct the component to re-render at a point in time where it attempts to execute the request. This may still lead to a response but your component will be forced to re-render which will give you different behaviour in concurrent/suspense as opposed to without it. I can't really make accurate predictions on what that will do though, since that's unsupported.

The supported case here works quite well: https://codesandbox.io/s/urql-reexecutequery-poc-forked-eeuym

So I'd love to narrow this done to what your specific use-case forces you to do and what behaviour we're then expecting to see. This is a little more complex than it looks; With suspense there's an additional "React cache" that holds the result for an additional render.

**Comment by Epimodev** [comment]
Thanks a lot for all those details!

About `setNbReexecuteQuery`, I added it to display on screen if `reexecuteQuery` was called without going in network devtool. Now I understand why I've got some unexpected behavior during my tests.  

We use `network-only` to be sure we display always latest data during navigation.  

And we have a use-case where we do a mutation, and then reexecute the query to update our UI, it looks like this:
```ts
updateData(data).then(reexecuteQuery)
```

With urql `1.11.6` it works well but since we upgrade to version `2.0.1` this doesn't work anymore.

**Comment by kitten** [comment]
@Epimodev So, we've got some information on that in "Basics", but if you call `reexecuteQuery` then technically nothing will happen. Only if you pass it `requestPolicy: 'network-only'` will it refetch. There's also `cache-and-network` which may be a good alternative to passively update data.

However, overall, there's a warning to be made here 😅 It's most of the time not adivsable to update data as we navigate around. It's possible to use `network-only` (or even `cache-and-network`) frequently, but that kind of defeats the point of minimising queries and network requests.

In the easiest case you can indeed call `reexecuteQuery({ requestPolicy: 'network-only' })` though and that'll do what you expect. However, setting `network-only` as the default anywhere will lead to unexpected behaviour. It's possible that this kind of worked before, but things get weird as we had to support more use-cases, so as we never made a guarantee on that that's now unsupported.

Basically, from a conceptual point of view, you'd have to ask: Does it make sense, especially with suspense, that we fetch on each mount or update? Because generally that's what the React team (and `urql` across frameworks) attempts to avoid.

For mutations, we'd recommend you to utilise the document cache (or the normalised cache's) mechanisms instead. Especially the document cache will (rather aggressively) refetch queries for you as data changes: https://formidable.com/open-source/urql/docs/concepts/document-caching/

So most of the time it's better to be declarative to avoid coupling mutations to queries that may be in very different places rather than imperatively coupling the two.

That being said, I'm wondering whether that makes sense, or whether there was any other constraint that's bothering your implementation here?

**Comment by Epimodev** [comment]
Ok, it's much clearer for me now, thank you very much!

We'll use `reexecuteQuery({ requestPolicy: 'network-only' })` at the moment but we'll try to use the cache as you advise.

Thanks again for all those explanations and advises 😀

**Comment by kitten** [comment]
@Epimodev Alright, just feel free to ping us with any questions as they arise 🙌

**Comment by chriszrc** [comment]
The whole point of ever needing the `reexecuteQuery` function is to.... re-execute it 🤦‍♂️. Can't network-only be made the default somehow so we don't run into this obvious footgun?

**Comment by kitten** [comment]
@chriszrc: This thread is from 2021, mind you.

By definition, I'd consider something a footgun if, by intuition, a user is likely to use it in such a way that it'll cause problems that aren't immediately apparent, and as such aren't rectified before they're in effect.

This isn't the case here because, if you intend to execute as per `requestPolicy: 'network-only'` as a re-execution in any bindings, but are using the default of `requestPolicy: 'cache-first'` this is quite immediately apparent in multiple ways, and can hence be recitified before it has any consequences. If it isn't, the consequences of not re-executing are frequently either obvious or inconsequential.
Often this is used as an escape hatch, when cache invalidation isn't working/setup correctly, which already is a chain of problems preceding this.

It's also well documented. The TSDocs list that this is required prominently, hence making it accessible quite easily in an LSP/TSServer-enabled editor.
The documentation also lists this in prominent places, since we consider this part of the "basics" of the bindings APIs (https://urql.dev/goto/docs/basics/react-preact/#reexecuting-queries)

I'm happy to concede that:
- our docs are not in the best of shapes, so while the placement is prominent, parts of them are often dismissed upon reading by our users
- the design decision here isn't immediately obvious unless at least one of the two caching docs has been read (e.g. https://urql.dev/goto/docs/basics/document-caching/) or the architecture is well understood

Anyway, to further explain this, reexecution isn't referring to network calls or caching per se. GraphQL's architecture first of all is transport agnostic, and while `urql` obviously has the typical bias towards HTTP transport (as per the GraphQL over HTTP spec), it isn't limited to this transport. Further, `urql` itself doesn't have an architecture that revolves around HTTP request and response structure, but instead streams of operations and results.

The architecture page explains this in more detail: https://urql.dev/goto/docs/architecture/
Execution means: An operation is sent into the `Client` pipeline of "exchanges" and results are filtered out for this operation.

Re-execution hence doesn't refer to "send a new network request" but "execute the operation again"

**Comment by chriszrc** [comment]
I'm aware it's an old thread, but it seemed like the right place, and the issue itself is still relevant. Yes, I did see this in the docs the first time I went through them, then used urql for a while, and totally forgot about it lol. Is there some way to at least configure this globally for all reexecute functions so I can set it once and forget it?
