### ISSUE TITLE
SimplePagination : not working

### ISSUE THREAD

**Issue by trompx** [FormidableLabs/urql#1399]
Hello,
I'm trying to setup pagination with simplePagination.
My setup:
```
    "@urql/core": "^2.0.0",
    "@urql/devtools": "^2.0.3",
    "@urql/exchange-auth": "^0.1.2",
    "@urql/exchange-graphcache": "^4.0.0",
    "@urql/exchange-multipart-fetch": "^0.1.11",
    "@urql/exchange-persisted-fetch": "^1.3.0",
    "urql": "^2.0.1",
```

urqClient:
```ts
  url: "http://localhost:4000/graphql",
  exchanges: [
    devtoolsExchange,
    dedupExchange,
    cacheExchange({
      resolvers: {
        Query: {
          // copied the content of simplePagination (main branch) to debug
          brandsPaginated: mySimplePagination({
            offsetArgument: "page",
            limitArgument: "pageSize",
            mergeMode: "after",
          }),
        },
      },
    }),
    errorExchange,
    multipartFetchExchange,
  ]
```

When I do pagination without urql cache resolver, I get data page after page.
I request data thanks to the generated hooks by codegen with the typescript-urql plugin.
```
  const { data, fetching, error } = useBrandsPaginatedQuery({ variables: {
    pageSize: 3,
    page: page,
  }});
```

brandsPaginated.graphql
```
query BrandsPaginated($page: Int, $pageSize: Int) {
  brandsPaginated(page: $page, pageSize: $pageSize) {
    page
    nextPage
    items {
      ...Brand
    }
  }
}

```
The brand id is a bigInt typed with type-graphql ID and used as string accross the app.

Also I use generics to have a global pagination accross multiple entities. I have the following paginated.response.ts:
```
export interface TPaginatedResponse<T> {
  items: T[];
  page: number;
  nextPage: number | null;
}
```
Not sure if urql will cache the items as brandsPaginated items or if I have to have a response name specific to each query for the cache to work?

**Expected behavior**
The data return by the paginated queries should stay in cache and display the request data + the previous data.

**Actual behavior**
1. First when I set in the cache resolver the following:
```
brandsPaginated: mySimplePagination({
   offsetArgument: "offset",
   limitArgument: "pageSize",
   mergeMode: "after",
 }),
```
and log the value of **compareArgs(fieldArgs, args)** in the simplePagination, it always returns true despite the fact that my offset argument is **page** and not **offset**.

2. When not using the cache resolver, I get for the first request : 
```
items: (3) [{…}, {…}, {…}]
nextPage: 1
page: 0
```
When I set the cache resolver as described at the top of the issue, I get:
```
0: null
1: null
2: null
3: null
4: null
5: null
6: null
7: null
8: null
9: null
10: null
11: null
12: null
13: null
14: null
15: null
16: null
17: null
18: null
19: null
20: null
21: null
22: null
23: null
24: null
25: null
26: null
```
Debugging further, doing **console.log(links)** outputs:
```
0: "Q"
1: "u"
2: "e"
3: "r"
4: "y"
5: "."
6: "b"
7: "a"
8: "n"
9: "d"
10: "s"
11: "P"
12: "g"
13: "i"
14: "t"
15: "("
16: "{"
17: """
18: "p"
19: ":"
20: "0"
21: ","
22: "S"
23: "z"
24: "3"
25: "}"
26: ")"
```
So it seems the **cache.resolve(entityKey, fieldKey)** set the links value wrong.
Here are the complete values I get from info and other vars used in simplePagination.ts :

```
entityKey: "Query"
fieldName: "brandsPaginated"
fieldInfos:
  arguments: {page: 0, pageSize: 3}
  fieldKey: "brandsPaginated({"page":0,"pageSize":3})"
  fieldName: "brandsPaginated"
```

Any idea of what could have gone wrong? Let me know if I can provide more info.

**Comment by kitten** [comment]
If you use GraphQL Code Generator I'm not quite sure what's output here, maybe you can elaborate, but I don't quite remember. However, `useBrandsPaginatedQuery(variables)` doesn't quite look right. Typically I'd expect `useBrandsPaginatedQuery({ variables: { ...} })`.

I also see that your structure in the result is:

```js
    page
    nextPage
    items {
      ...Brand
    }
```

Basically, the two pagination helpers are limited in what they do. They're intended to help you set up pagination quickly but they expect an _exact_ shape that they need to know of. The helper doesn't deal with any fields that don't return a list of results. In your schema you seem to instead return a `Connection` type similar to a relay paginator. The pagination helper doesn't know about this structure so it won't work.

I'd either recommend you to switch to `relayPagination` and implement Relay-compliant pagination or instead move your pagination combination for infinite scrolling to your UI; e.g. if it's React this would look something like this: https://twitter.com/benawad/status/1303503308271816711?s=20

**Comment by trompx** [comment]
Thanks for the fast answer @kitten.

My bad it was a typo while triming my code, but I had the **variables:** while using the codegen query.
Do you mind elaborating what kind of **exact shape** they need to know of?
You mean it only works for queries where results are returned directly (not in a nested object) like the following?
```
query BrandsPaginated($page: Int, $pageSize: Int) {
  brandsPaginated(page: $page, pageSize: $pageSize) {
      ...Brand
  }
}
```
Yes my response includes fields similar to relay paginator but a bit simpler, I don't really need he full relay pagination. But if there is not intermediary solution I'll maybe try to implement it.

Thanks for the link to benawad solution. It seems his cursorPagination is tied to a specific query but I guess it could take argument to pass the typename when setting resolvers in the cacheExchange.

**Comment by kitten** [comment]
So the specific solution in that tweet is basically based on our advice; pagination, especially if it's custom and based on your own terms and schema become much easier when you simply have multiple components loading the separate pages and a parent that keeps track of loading more.

It is generalisable as well of course. But generally I'd recommend this because it's easier to maintain.

The idea of our helpers is that if you already have one of the two supported cases you'll be able to test out infinite pagination rather quickly, or those can be useful on React Native where page-based components aren't an option with `FlatList`

**Comment by trompx** [comment]
I like to be in control when I use a library, so not managing to get data from simplePagination is a bit frustrating. I get that I can manage the cache of paginated queries directly in components but I'd rather levergage urql normalized cache (which is why I use urql in the first place).
I think something is still wrong. I tried to implement benawad old solution (cursorPagination) but I don't manage to get the data client side, despite the data being returned by the server. It is not passed if I don't return the data in a very specific way.

```ts
export const mySimplePagination = ({
  typename,
}: PaginationParams): Resolver => {
  return (_parent, fieldArgs, cache, info) => {
    const { parentKey: entityKey, fieldName } = info;
    const allFields = cache.inspectFields(entityKey);
    const fieldInfos = allFields.filter((info) => info.fieldName === fieldName);
    const size = fieldInfos.length;
    if (size === 0) {
      return undefined;
    }

    const fieldKey = `${fieldName}(${stringifyVariables(fieldArgs)})`;
    const isItInTheCache = cache.resolve(
      cache.resolve(entityKey, fieldKey) as string,
      typename
    );
    info.partial = !isItInTheCache;
    let nextPage = 0;
    let page = 0;
    const results: string[] = [];
    fieldInfos.forEach((fi) => {
      const key = cache.resolve(entityKey, fi.fieldKey) as string;
      const data = cache.resolve(key, "items") as string[];
      nextPage = cache.resolve(key, "nextPage") as number;
      page = cache.resolve(key, "page") as number;
      results.push(...data);
    });
    // results here = ["Brand:2", "Brand:3", "Brand:4"]

    // 1. If I return directly results here, the client side query succeeds but I get:
    // results.data = brandsPaginated: Array(3)
    // 0: null
    // 1: null
    // 2: null
    // Any idea why it is not able to get the data returned by the server? 
    // Despite the fact that it seems it has access to the data returned.
    return results;

    // 2. If I return the data in the same structure as my response type defined server side,
    // the client side query returns : results.data = null
    return {
       __typename: typename.charAt(0).toUpperCase() + typename.slice(1),
       nextPage,
       page,
       items: results,
     };
  };
};
```

```
"next-urql": "^3.0.0"
"next": "10.0.7"
```

What happens with the data once it is returned by the paginator?

**Comment by kitten** [comment]
So, I would highly advise here that the pagination resolvers are likely the "largest" and most complex ones that you could write, so they're not trivial to get right. However, I'd hold off on starting with Ben's code here as it's not working properly (as pointed out when he wrote it in a video I believe)

Instead you may want to start with the official one: https://github.com/FormidableLabs/urql/blob/main/exchanges/graphcache/src/extras/simplePagination.ts
You can also kind of see how the `relayPagination` resolver handles the non-list fields: https://github.com/FormidableLabs/urql/blob/e5ea77e836b11be379327bee7abe74109d0adabc/exchanges/graphcache/src/extras/relayPagination.ts#L282

But that being said, you don't gain control here. In fact, with the fragment approach you may actually have much more control since you're dealing with the separate queries still. I understand that you probably want to compare, but it's not quite of a nice experience like we'd want to recommend it.

**Comment by trompx** [comment]
I really appreciate the feedback @kitten. Sure pagination is a hard topic, and I try to get a good grasp on the best way to do it. I started with Apollo, then migrated to react query which leverage a lot and is really nice to work with, but lacks subscription and a normalized cache so I went for urql.

Anyway I managed to solve this!
As stated before, I was trying to understand how urql was getting the value from its cache to the client, and it seems it **absolutely needs the right typename**. As said before, I use generics, and my response were of the type **Paginated<DomainName>Response**.
In the initial benawad solution, he was hardcoding that value. I was myself passing the typename but as **BrandsPaginated** instead of **PaginatedBrandResponse** thus failing.

 For those looking for the same, I get the typename dynamically like:
```ts
   const fieldKey = `${fieldName}(${stringifyVariables(fieldArgs)})`;
    const typename = cache.resolve(
      cache.resolve(entityKey, fieldKey) as string,
      "__typename"
    ) as string;
```
Then:
```ts
    return {
      __typename: typename,
      nextPage,
      page,
      items: results,
    };
```
And it works like a charm. Will now experiment handling that logic directly in component similar to what benawad new solution to see what I prefer.

But tell me if I am wrong, I have a feeling that if I want to update the cache later (if some queries must update other queries), it will be harder if I am not using the cache resolver but instead a component based pagination?

**Comment by kitten** [comment]
That looks about right! 👍

For the field key by the way you can pass `fieldArgs` directly to `cache.resolve` so that you don't have to code the keying into your code yourself, ie `cache.resolve(entityKey, fieldName, fieldArgs)`.

Alternatively there's a `keyOfField` function https://github.com/FormidableLabs/urql/blob/e5ea77e836b11be379327bee7abe74109d0adabc/exchanges/graphcache/src/types.ts#L84

However, some of this information will also be available on the `info` argument of the resolver: https://formidable.com/open-source/urql/docs/api/graphcache/#info

**Comment by Svarto** [comment]
@trompx I am looking to do something a bit similar I believe, to paginate a nested array of objects rather than the first level that is returned by the query. Similar to your final one, where you specify:
```
    return {
      __typename: typename,
      nextPage,
      page,
      **items: results,**
    };
```

Would it be possible to see more code from how you made it work? Would be super helpful, thank you in advance!

**Comment by FireworksX** [comment]
@Svarto Did you resolve how paginate nested array?
