### ISSUE TITLE
refocusExchange causes "window is not defined" crash with nextjs ssr

### ISSUE THREAD

**Issue by breytex** [FormidableLabs/urql#1416]
urql version & exchanges:
2.0.1
dedupExchange, cacheExchange, ssrExchange, fetchExchange, refocusExchange

**Steps to reproduce**

1. set up nextjs based on the `next-urql` docs in _app.tsx
2. add refocusExchange 
3. load any page, see "window is not defined"

**Expected behavior**
refocusExchange should only be initialized on client side

**Actual behavior**
refocusExchange is initialized during ssr which causes it to crash

**Comment by kitten** [comment]
I think it's worth adding a small check for `typeof window` to the exchange but I wouldn't say that this is a bug, since you can also exclude the exchange from your `exchanges` list with such a check ✌️

So it could be a small enhancement but I'll just mark this by removing the bug label and will see whether we'll implement it soon, since we also had some plans to combine the `refocus` and `requestPolicy` exchanges at some point

**Comment by breytex** [comment]
> since you can also exclude the exchange from your exchanges list with such a check ✌️

Nice, didn't know it is that easy to conditionally load exchanges :)
I will try and report my findings here later.
Thanks for the quick help!

**Comment by breytex** [comment]
Hey @kitten ,

I have tried:
```typescript
const isServerSide = typeof window === 'undefined'

export default withUrqlClient(
  (ssrExchange, ctx) => {
    const exchanges = isServerSide
      ? [dedupExchange, cacheExchange, ssrExchange, fetchExchange]
      : [dedupExchange, refocusExchange(), cacheExchange, fetchExchange]

    return {
      url: 'http://localhost:4000/graphql',
      requestPolicy: 'cache-and-network',
      exchanges,
    }
  },
  { ssr: false }
)(MyApp)

```

The "window undefined" error is gone, but the refocus exchange doesn't seem to work. Queries are not triggered on window focus.
Is that exactly how you would have implemented it? Or is there a missunderstanding on my side?
