### ISSUE TITLE
RFC: [Vue] use composition apis outside setup()

### ISSUE THREAD

**Issue by zhongqf** [FormidableLabs/urql#1442]
## Summary

Currently, the vue 3 composition apis, like `useQuery`,`useMutation` , can only be used inside the `setup()` function.
This is very inconvenient like when you want to use urql as an api layer in vuex's action/mutaion，

## Proposed Solution

Just add a singleton `Client` instance in `useClient.ts`, and return it in `useClient()` method?

**Comment by kitten** [comment]
I'm not quite sure what the proposal here is. You can already use the provided client via context as you're describing. It's not a singleton since it can't be for server-side usage.

We don't yet support the options API but will ultimately look into it.

Sorry, I'll have to close this because it's not a valid RFC submission with an API change proposal. Maybe you actually wanted to start a discussion thread or your issue is already covered by #1327?

**Comment by zhongqf** [comment]
@kitten Thanks for reply

In current implementation of `useQuery` or `useMutation`, the first thing is calling `useClient()` to get the client instance, which is provided in `provideClient` or `urql` plugin's `install` method, by `inject` it in `useClient()`

https://github.com/FormidableLabs/urql/blob/69195d19d15d6f8b16a0e07130f5a4469494e37a/packages/vue-urql/src/useQuery.ts#L89-L93

https://github.com/FormidableLabs/urql/blob/69195d19d15d6f8b16a0e07130f5a4469494e37a/packages/vue-urql/src/useClient.ts#L15-L16

This is good when you using `useQuery` or `useMutation` inside a component's `setup()` function, 
but it will get an error when you using `useXXXX` in a promise or a callback like a vuex action, 

`No urql Client was provided. Did you forget to install the plugin or call ``provideClient`` in a parent?
    at useClient (useClient.ts:17)`

the reason is there is no a vue `currentInstance` available in the callback/promise's context so that the `inject` will fail.
