### ISSUE TITLE
[@urql/vue] useQuery/useMutation must be used in setup()

### ISSUE THREAD

**Issue by zhongqf** [FormidableLabs/urql#1445]
@kitten  Pls look at this:

https://codesandbox.io/s/romantic-zhukovsky-gdmg6?file=/src/components/HelloWorld.vue

When using `useQuery` in an event callback not the `setup()` directly ( Just to demonstrate the issue here, I know there is a `pause` option can do the same thing), it will fail with message
```
No urql Client was provided. Did you forget to install the plugin or call `provideClient` in a parent?
```
But it does provided the client in `App.vue`.

That is because, when you call `useQuery/useMutation`, firstly it will call `useClient()` to get the client that provided in ancestor or root components, by using the vue api `inject(symbol)`.  But when you are not be inside the `setup()` function directly, the `inject` function will fail because there is no vue's `currentInstance` in the callback context.

https://github.com/FormidableLabs/urql/blob/69195d19d15d6f8b16a0e07130f5a4469494e37a/packages/vue-urql/src/useQuery.ts#L89-L93

https://github.com/FormidableLabs/urql/blob/69195d19d15d6f8b16a0e07130f5a4469494e37a/packages/vue-urql/src/useClient.ts#L15-L16

**Comment by kitten** [comment]
That's because you can't use these `use*` APIs at arbitrary points but only as part of your setup.

You can kind of start seeing this idea in this intro on the Composition API: https://v3.vuejs.org/guide/composition-api-introduction.html

There you see that `use*` functions are used to compose a `setup` lifecycle out of smaller "setup" functions.

You can see here in our guide how we can handle this dynamically; https://formidable.com/open-source/urql/docs/basics/vue/#pausing-usequery

You can use `pause: true` with `result.executeQuery` even to dynamically start the hook. Basically the composition API guides you towards setting up all state and logic once and then to manipulate this state reactively rather than imperatively.

Alternatively, at any point you can use the imperative methods on the client itself to start queries. https://formidable.com/open-source/urql/docs/basics/core/#one-off-queries-and-mutations

The difference though is that these will never _update or react to changes_. That means if you don't use the hook, like `useQuery`, then your result will never change unless you start another query manually. Without this hook a mutation can't update your query result for instance

**Comment by zhongqf** [comment]
@kitten Thanks for the reply.

I can understand what are you said, but in the real world especially when you want to build a big application for production, you may need to consider separating your app into some modules (like vuex/redux does) or services (like angular does), and decoupling with several layers. In that situation, it is difficult to ensure that `use*` functions always be called in a directly or synchronously way, in the javascript world. Even not be the name of `use*`, maybe some async apis while keeping the vue's reactivity is more useful.

By the way, vue-apollo v4 can use the `use*` functions outside the `setup`.

**Comment by kitten** [comment]
You may find that separating the code is just the same as before; it's only different what you pull out into separate functions and how state interacts, meaning that all reactive variables and effects will be set up once and not change after the setup phase in theory.

That said, it's also important because otherwise it'd be impossible to tell these to stop at the right time or update. For instance, if you make the imperative call you never get an update as said before, but if we ran this entire hook with suspense support at an arbitrary point it'd also be unclear when it should stop receiving an update.

I'm not sure how Vue-apollo solved this in v4 but if they allow arbitrary calls to their `use*` calls that may just be a foot gun if they do implement their updates properly

**Comment by snaplesec** [comment]
I'm not sure that I understand how to do something like a login, you have to fill in a form then submit the form with @click event.  How do we submit the mutation to get the login creds with the form filled in, if it is in setup()?
I'm sure that I am not understanding something.

**Comment by kitten** [comment]
@snaplesec That's a pretty standard case; in the case of mutations you may want the props returned from `setup()` to have a callback that starts executing it. It could then also return the results if the same component were to read those back. So all in all, you could expose the entire return value of `useMutation` to your component.

**Comment by jvmonjo** [comment]
I have the same error: `Error: No urql Client was provided. Did you forget to install the plugin or call provideClient in a parent?`

But only whe I try to make a mutation. Queries work just fine. Both are used inside the setup function.

**Comment by bartenra** [comment]
I don't think it is a problem that useQuery/useMutation needs to be ran inside a `setup()`.

What is a problem though, is that inside a `setup()` you cannot cannot `await` two useQuery's, or even use useMutation after `await`ing an useQuery. :/ 

When I try do this I also get "No urql Client was provided. Did you forget to install the plugin or call `provideClient` in a parent?"

**Comment by kitten** [comment]
I'll close this for now, so we can move discussion to this RFC: https://github.com/FormidableLabs/urql/issues/1596

This is a first proposal to get a solution for some of the evidently confusing issues with the implementation and API today. There are still some unanswered question, but at least it'll give us a strawman proposal to work against ❤️
