### ISSUE TITLE
RFC: Add Next.js-style examples to main repo to ease getting started path

### ISSUE THREAD

**Issue by makuzaverite** [FormidableLabs/urql#1450]
When someone start using  a new tool can be intermediation, but looking at the example projects from the creators  really saves time for new comers.

I would like to ask if possible to add example directory inside this repo that show how to integrate this library different other UI frameworks out their including best practices and real-world use cases

**Comment by kitten** [comment]
That's a great point! I was actually thinking of creating just that, in the style of Next.js' examples as part of this proposed effort: https://github.com/FormidableLabs/urql/discussions/1427

> There should be large amounts of practical examples for each use-case isolated to what someone is looking for (Next's examples are a good & ideal sample of what this may look like.

so for instance, we should have `examples/with-react`, `examples/with-vue`, but also `examples/with-subscriptions` and such. The only thing standing in the way being that we'll have to set up a lot of example APIs, which for simplicity's sake _shouldn't_ live in the main repository.

**Comment by makuzaverite** [comment]
I don't know how you are organization works but having examples folder, I don't see anything bad with it. and If you may allow i can help setup examples of using this library

**Comment by kitten** [comment]
### First Examples

- [x] Next.js / next-urql example, #1502 
- [ ] "Basics" React (queries-only)
- [ ] "Basics" React Native (queries-only)

### Second Examples

These can all be written in React, because they don't focus on the bindings anyway.

- [ ] Retry on Error (`retryExchange`)
- [ ] Automatic Persisted Queries (`persistedFetchExchange`)
- [ ] Simple File Upload (`multipartFetchExchange`)
- [ ] React Pagination with `React.Fragment` components
- [ ] Graphcache with Pagination
- [ ] Authentication with refresh (`authExchange`)
- [ ] Mutations and cache updates with Graphcache

### Low Priority Examples

- [ ] "Basics" Preact (queries-only)
- [ ] "Basics" Vue (queries-only)
- [ ] "Basics" Svelte (queries-only)
