### ISSUE TITLE
RFC: (@urql/exchange-graphcache) Allow using .graphql files for schema awareness

### ISSUE THREAD

**Issue by danbeneventano** [FormidableLabs/urql#1518]
## Summary

Currently you have to use a `.json` file for schema awareness. The `schema` option should also accept `.graphql` files. For example, the [TypeGraphQL](https://typegraphql.com/) framework can output a `schema.graphql` file. The JSON requirement for schema awareness requires me to add another step to my code, that could be avoided if `.graphql` files are accepted.

## Proposed Solution

The `schema` option should accept a JSON object, an imported `.graphql` file, or a path to a `.graphql` file.

**Comment by kitten** [comment]
This is explicitly not supported because it'd mean we'd have to parse the schema (a path / direct import isn't possible since we're dealing with client-side code as well here) and then create a non-executable schema and introspect it.

To be fair, you can already do this and a utility for this exists in `@urql/introspection`: https://github.com/FormidableLabs/urql/blob/main/packages/introspection/src/getIntrospectedSchema.ts

But since you'd be pulling in more utilities and more from `graphql` you'd greatly increase your bundle size and add processing time to your app's startup for data that can be computed at compile time.

That being said, Graphcache obviously doesn't care about how the JSON data is derived, which is why for instance it can be generated using GraphQL Code Generator, which we'd assume is a common tool in a frontend app that is typed and which we'll recommend as part of our framework-efforts in the future

**Comment by danbeneventano** [comment]
I see, thanks for the insight!
