### ISSUE TITLE
RFC: React Client side suspense

### ISSUE THREAD

**Issue by wenerme** [FormidableLabs/urql#1531]
## Summary

Currently, enable suspense when createClient, then urql consider this ssr suspense, all useQuery will use suspense by default.

The checking logic is

```ts
const isSuspense = (client: Client, context?: Partial<OperationContext>) =>  client.suspense && (!context || context.suspense !== false);
```

But, suspense is really useful in __client__ when building complex sap, 

e.g. build a form builder need to pulling all schemas first, better to wait metadata is readly, otherwise the form will get alot rerender, and is hard to do it right, with an outside component handle the suspense, the build process can be sync.

## Proposed Solution

Currently, the useQuery accept context, allowed __opt-out__ suspense by providing a immutable context, have to write like

```ts
useQuery(gql``,  {context: useMemo({ suspense: true },[])})
```

useQuery should support suspense like react-query,

```ts
// react query
useQuery(queryKey, queryFn, { suspense: true })

// urql
useQuery(gql``,  { suspense: true })
```

## Requirements

* __opt-in__ suspense

**Comment by kitten** [comment]
Hiya :wave: Thanks for submitting this, however for now I'm closing this. The primary reason is that it's not a complete proposal that focuses on a single goal, but seems more to be a question towards the semantics of suspense in `urql`.

We shipped major improvements to our React bindings with the help of the React team and as a consequence suspense is much more reliable in the newer versions. However, we recommend to either embrace client-side suspense or not, meaning we wouldn't recommend to selectively turn suspense on or off. Instead, enabling suspense on the client-side should apply its semantics across an app and not selectively. It is possible however to then turn suspense _off_ selectively, kind of with the method you suggested, instead that the flag would be `suspense: false`, however your examples don't quite semantically match up with our API.

So, generally, suspense is _opt-in globally_ by design.
