### ISSUE TITLE
graphcache local resolver return array do not fallback to network

### ISSUE THREAD

**Issue by wenerme** [FormidableLabs/urql#1546]
urql version & exchanges:

latest, graph-cache 

**Steps to reproduce**

```ts
cacheExchange({
  resolvers: {
    Query: {
      findUserById: (data, args) => {
        return { __typename: "User", id: args.id };
      }
    },
  },
});
```

If the user not in cache, will not send a query

**Expected behavior**

fallback to send network query

**Actual behavior**

return null

I don't  find any doc about the resolver miss cache behavior, from the source, I found return undefined is missing, but have no way to fallback to network, this makes resolver useless, because the result may null without sending a real query.

**Comment by kitten** [comment]
Whoop, sorry, didn't mean to close there. This is more likely a usage issue on your end and totally supported. But without a reproduction or more information it's a little hard for us to help.

I can guarantee you though that it's not a bug, since this exact pattern is live in multiple sites.

Have you checked your console for warnings?

**Comment by wenerme** [comment]
@kitten thanks for you quick reply, I recheck the code

```ts
cacheExchange({
  keys: {
    UserDefinedTypeSchema: (data: any) => data?.name,
  },
  resolvers: {
    schemaByName: (_parent, args) => {
      // my first mistake - MUST use name, insead of id
      return { __typename: "UserDefinedTypeSchema", name: args.name };
    },
    schemaByNames: (_, args, cache, info) => {
      const names: string[] = args.names as any;
      // this NOT works
      return names.map((name) => ({
        __typename: "UserDefinedTypeSchema",
        name,
      }));
    },
  },
});
```

The schemaByNames will not fallback to network, I don't know is this by design.

The result is like

![image](https://user-images.githubusercontent.com/1777211/115031322-9a241280-9efa-11eb-933d-7ee290c9b24f.png)

**Comment by wenerme** [comment]
Currently use this workaround

```ts
schemaByNames: (_parent, args, cache) => {
  const names: string[] = args.names as any;
  const keys = names.map((name) => ({ __typename: 'UserDefinedTypeSchema', name }));
  if (keys.find((v) => !cache.resolve(v, 'name'))) {
    return;
  }
  return keys;
}
```

**Comment by kitten** [comment]
Sorry, I forgot about this a bit. Are you using schema awareness? Because if so then this is what it looks like and as that page explains you'll start getting partial results.

I've also seen another code snippet where you used imperative promise-based calls, which would explain why you wouldn't see future network results, and I wasn't quite sure last time why you were using those rather than any bindings

**Comment by wenerme** [comment]
@kitten do not enable schema awareness, the result is non null, this happened when useQuery with suspense disabled.

**Comment by kitten** [comment]
We discovered that this is related to an older check that allows list items to become nullable even without a schema. We're discussing whether that's still appropriate behaviour https://github.com/FormidableLabs/urql/blob/b6890ba1b0c9fa9e99301338555ea10d602cee22/exchanges/graphcache/src/operations/query.ts#L451

**Comment by kitten** [comment]
Just to keep you updated; this was in fact _not_ the desired behaviour and we've landed a fix that will go out with the next release cycle.
