### ISSUE TITLE
Subscribing to a query using `cache-and-network` only emits once (if the client is performing other requests in parallel)

### ISSUE THREAD

**Issue by jzarzeckis** [FormidableLabs/urql#1553]
urql version & exchanges:

* `urql@2.0.0`
* `exchanges: [dedupExchange, cacheExchange({ storage: makeDefaultStorage() }), fetchExchange]`

**Steps to reproduce**

```ts
toObservable(client.executeQuery(createRequest(SOME_QUERY), {
	requestPolicy: "cache-and-network"
})).subscribe({
	next: ({stale}) => console.log(`Got a response which was ${stale ? 'stale': 'fresh'}`),
	error: noop,
	complete: noop
})
```

**Expected behavior**

1. With a cold cache:
  1. `console.log()` called just once with "Got a response which was fresh"
2. With a hot cache:
  1. `console.log()` first called with data from cache with "Got a response which was stale"
  2. `console.log()` second called with "Got a response which was fresh"

**Actual behavior**

If there are other requests being made using the same client - it emits only once with the stale data.

It can be observed by looking at console logs in this codesanbox: https://codesandbox.io/s/charming-wescoff-s6und?file=/src/index.ts

Also - if you comment out line 28 in the sandbox (to ensure only 1 request is made by the client) the correct behaviour can be observed.

Other requests made by the client should not affect behaviour of each other.

**Comment by kitten** [comment]
This is currently expected behaviour.

We're debating whether we're going to change a couple of things about shared query streams;

However, in practice shared query operations should be rare as the best practice is to hoist data dependencies and fragments per page into a single query.

That being said, we've noticed a strong "overuse" of cache-and-network, where people have also started using it by default, which often defeats the point of caching in the first place, so we're also looking into how to discourage that in our API

**Comment by jzarzeckis** [comment]
Thanks for the explanation.
