### ISSUE TITLE
Performance optimization: stitching together queries

### ISSUE THREAD

**Issue by jamesplease** [FormidableLabs/urql#16]
Cool library, @kenwheeler ! I'm still checking out the code to see all of the features. I appreciate the simple approach you've taken here, particularly in comparison to the complexity of Apollo's source (I ❤️  Apollo, don't get me wrong! 🙂 )

---

One thing I noticed is that if a user passes in 10 queries, [10 requests are made](https://github.com/FormidableLabs/urql/blob/55de396e3797f8c68aef968334dd0405dbb1c866/src/components/client.tsx#L216-L217). I was thinking that it'd be neat if the queries could be stitched together.

Apollo and Relay can accomplish features like this by breaking the query down into an AST, which is powerful, but probably a little heavy-handed for what this library is doing. Luckily, the GraphQL syntax is (currently, at least) simple enough that there should be a way to do this robustly without an AST by making a few reasonable assumptions.

If you're :+1: to this idea, I'd be happy to put together a proof of concept.

---

**What lead me to this idea?**

I noticed that urql caches at the query level, rather than the root query level. i.e.;

```
{
  queryA
  queryB
}
```

creates one entry in the cache, and not two.

I was going to open a similar issue to this one, suggesting that a lightweight function could be written that splits up the query for caching purposes. But then I realized that because the component accepts an array of queries, that maybe that was the recommended approach instead.

I wonder how hard it'd be to write these two functions: one that joins root queries, and the other that splits them apart.

What do you think?

Thanks for reading! :v:

**Comment by kenwheeler** [comment]
I would love a proof of concept for this!

**Comment by jmeas** [comment]
> This comment is mostly about the effects of this update on request deduplication (described in #30 ) , which is because that is more likely to get merged before this does because I already have the work done there.

Should #30 land before this, then the implementation of `fetch-dedupe` there will need to be updated for this feature.

Instead of passing _one_ request key to `fetch-dedupe`, it will need to support `n` request keys, which represent all of the "sub-requests" contained in the "wrapping" HTTP request.

Once you pass all of the keys into fetch-dedupe, it will loop through its store of keys and compute difference. When the difference is 0, then the request contains new information and needs to be made.

---

An advanced optimization would be to _remove_ the queries that are already in flight from the request, and then pull them out of the cache once all of the requests return, but this would require a bit of tricky code to make it work seamlessly. I wonder if Apollo does that... :)

**Comment by kitten** [comment]
This could now be implemented on the exchange-level in v0.3+. In fact, with `urql-exchange-apollo` it's less of a pressing concern, since a user could now utilise `apollo-link-batch-http`. I'd say let's close this for now and come back to it later. https://github.com/kitten/urql-exchange-apollo

To answer some of the concerns here, request deduplication is now implemented, and it's relatively unrelated to this issue.

It won't make sense to split and merge all requests in my opinion. Instead we can apply the same Apollo batching of queries, which works differently than just a standard query afaik, but is supported by most GraphQL servers.

If we talk about splitting instead we're already at cache normalisation since the process needs to be reversible and recombinable, but normalisation adds additional complexity which we'd like to avoid.

**Comment by mistenkt** [comment]
I know this is an old issue, but instead of opening a new issue i thought i might aswell continue here as this is exactly the same "issue" i'm facing.

Has any more thought been put into batching of queries? Or are there any examples of a custom fetchExchange implementation that would solve this?
