### ISSUE TITLE
exchange-request-policy saves last access time, not last time of network request

### ISSUE THREAD

**Issue by brummelte** [FormidableLabs/urql#1636]
**urql version & exchanges:**

"urql": "^2.0.3"
"@urql/core": "^2.1.1"
"@urql/exchange-request-policy": "^0.1.2"

**Steps to reproduce**

Switch between two pages faster than the TTL

**Expected behavior**

Queries don't trigger `shouldUpgrade` (and subsequently a network request)

**Actual behavior**

Queries should trigger `shouldUpgrade` after TTL has been expired based on last network request, not after last access of cached data

**Reproduction**
https://codesandbox.io/s/vibrant-bird-5pi8t?file=/src/index.js

Open the console and use the toggle button faster than every two seconds and "shouldUpgrade" won't show in the console. Wait for two seconds and then toggle, then you will see "shouldUpgrade".

It will still not make a network request, but that is handled in this issue: https://github.com/FormidableLabs/urql/issues/1334

**Comment by kitten** [comment]
I wouldn't quite classify this as a bug, but rather as a change request maybe 🤔 I do think this kind of fits nicely into our bigger thoughts around merging the `requestPolicyExchange` with the `refocusExchange` and making a larger more featureful replacement for both that handle more of these edge cases.

I think in some cases it's very desireable actually, to have it use the last accessed time rather than last received time, but I think this will need more thought put into it rather than just switching it over potentially.

**Comment by brummelte** [comment]
With the current default TTL of 5 minutes, some queries might never reload.

I can't actually come up with a use case where last accessed time for upgrading to a network request is the preferred behavior.

With the current setting while actively using the software, data will stay stale. Only when becoming inactive and active again, data will be refreshed.

I can only see a benefit when having very low TTLs. But since we can only define a global TTL and not per query, I think TTLs will probably be higher.
