### ISSUE TITLE
Infinite render loop with suspense disabled for one query in urql core version 2.1.1

### ISSUE THREAD

**Issue by brummelte** [FormidableLabs/urql#1637]
**urql version & exchanges:**
urql 2.0.3
Fails with
"@urql/core": "^2.1.1"
But works with
"@urql/core": "^2.1.0"

**Steps to reproduce**

1. Set global suspense to true
2. Run a query with suspense disabled

**Expected behavior**

Query loading using suspense and loading normally.

**Actual behavior**

Inifinite rerender
"Too many re-renders. React limits the number of renders to prevent an infinite loop."

**Reproduction**
https://codesandbox.io/s/strange-gagarin-5xq4s?file=/src/index.js

Change @urql/core to ^2.1.0 and it works.

**Comment by kitten** [comment]
I spotted a usage of `useQuery` that creates a new `context` object on each render. Since React has `useMemo` we chose not to apply any kind of stringification or built-in memoisation to `context`, since not all values that the `context` accept are or have to be serialisable. Hence, you have to memoise it if you use it, e.g.:

```js
  const [res, executeQuery] = useQuery({
    query: TodoQuery,
    context: useMemo(() => ({ suspense: false }), [])
  });
```

**Comment by brummelte** [comment]
Perfect and makes sense, thanks.

I could not find many details in the documentation about the context parameter of useQuery. Maybe it should be added there.
