### ISSUE TITLE
exchange-graphcache: Race condition where Optimistic Updates are not persisted to the cache correctly

### ISSUE THREAD

**Issue by jesselee34** [FormidableLabs/urql#1639]
Optimistic updates are not persisted to the cache correctly when a third optimistic update is executed prior to the server response from the first, and; the input to the third mutation matches a value that was in the first or second.

@urql/exchange-graphcache: ^4.1.0
@urql/introspection: ^0.3.0
graphql": ^15.5.0
react": 16.12.0,
urql": 2.0.2

**Steps to reproduce**

I created a repository where the issue can be reproduced easily. The README.md has instructions to setup and run

https://github.com/jesselee34/exchange-graphcache-issue

**Expected behavior**

From the documentation about optimistic updates:

```
Note: While optimistic mutations are waiting for results from the API all queries that may alter our optimistic data are paused (or rather queued up) and all optimistic mutations will be reverted at the same time. This means that optimistic results can stack but will never accidentally be confused with "real" data in your configuration.
``` 

The "good" button in the sample repo appears to follow the behavior described here correctly.
The "bad" button does not.

Run the application, there's a good button and a bad button. Click the bad button 6 times in quick succession and observe the score.

**Actual behavior**

The bad button increments to score to 3 and is supposed to count backward from three, but instead it hangs until all the server responses return at which point it flips the score to 2, but the actual value at this point should be 1.

The good button just increments the score, and acts as expected.

**Comment by kitten** [comment]
I may be misunderstanding something here, but I don't think we can do anything about this. Since all of these mutations are run concurrently and conflict with one another we can't prevent the API from returning results to us in a different order. The optimistic updates on the client-side are ordered, but the API requests are not; so the only thing we could recommend here is to serialise some mutations and run them in series i.e. in order, because otherwise the results are applied in the order they're sent, which then may conflict with the server's order in which they're applied.

Let me know if that's factually accurate, but I think that's what's probably going on?

**Comment by jesselee34** [comment]
Hmm, I'm surprised that this is expected behavior.

I discovered the issue while testing an actual application. The example that I put together is a toy and simplified only to make the issue easy to reproduce.

I don't think the order of the responses from the server matters in this example. You can see the optimistic updates themselves are not acting correctly on the bad button. If you click it at least 4 times, the 4th click will not set the cache back to 2 as one would expect it to.

Would it be possible to include a timestamp with the optimistic update so graphcache doesn't confuse the first `count:2` with any subsequent `count: 2`?

**Comment by kitten** [comment]
So, to explain, we had a similar issue related to this under #1622, however we see this as expected behaviour (that's effective as long as we can make people aware of this when they run into it) because it prevents other even worse scenarios.

Every mutation is treated similar to a query; it's an operation and every operation gets a key and is treated as an atomic call. Mutations are a little special in that they may be executed imperatively and immediately without caching. In practice this introduces a small limitation: You may trigger a mutation with the same inputs twice rapidly and then get the same result in both call sites. But the mutation itself has run and is executed. It also updates the data as expected.

In Graphcache there's another component to this: Offline Support and Commutative Layers. We layer operations in order and that means in your case, when a mutation is duplicated later on, it reuses its old layer. In practice that's important because there's still a single order to them. With offline that's absolutely crucial as we want to determine a consistent order to optimistic mutations.

Now, why don't we think that it's an actual problem?

Mutations are typically _not_ as simple as "do something and assume inputs" but more often really explicit; they often are unique when some content is created or specify inputs that are repeatable, like "update text".

There's then also our concern that lifting this limitation would introduce different and more severe issues. For instance, if we incremented mutation keys by how many are running concurrently, then there's a possibility that the call site (when it's reinstantiated) won't be able to find its mutation anymore. In the case of React this is a big risk when the component remounts during its mutation and you'd expect the hook to present you the new result.

But in practice this issue presents itself in your example app because you're observing the number as it is in your UI and are then applying this number again in your mutation, also from the UI. Hence it's very reliant on the optimistic update applying rather than checking what the value should be with any unique recognisable ID/key.

If we consider what would happen if these limitations didn't exist then we'd like be in a "CRDT land" where we'd have some kind of vector counter (or at least consistent) order of how these operations are applied. Unfortunately, we're taking a lot more limitations around Offline Support, UI bindings <-> Cache syncing, and operation uniqueness (for retrying for instance) into account.

**Comment by jesselee34** [comment]
Maybe I'm confused about how optimistic updates are intended to be used, as I'm not sure I understand this:

```... Hence it's very reliant on the optimistic update applying rather than checking what the value should be with any unique recognizable ID/key.```

If I were to refactor the toy example, what would I change to ensure the 'bad' button updates the score as is intended?

**Comment by kitten** [comment]
@jesselee34 Well, in terms of optimistic updates, there's multiple sides to this, but specifically, what's interesting here is that you have a "feedback loop" here. An optimistically updated query is immediately used to schedule another, which eventually "folds in on itself" by repeating mutations with the same key. That alone is unlikely to happen in an actual app (assuming a well-designed schema with a mutation that's represents a user interaction, which is what we'd specifically want to attach an optimistic update to)

**Comment by jesselee34** [comment]
```...An optimistically updated query is immediately used to schedule another```

Now I'm starting to think I just don't understand how the optimistic update is supposed to be implemented.

In the toy example I'm not understanding what you mean by "immediately scheduling another"

My understanding of how it's supposed to work, and how I implemented it in the toy:

1. The user clicks the button which triggers a mutation.

2. The optimistic function configured for that mutation, returns the result that's expected from the real mutation

3. An updater for that mutation is configured to tell the cache how that particular mutation should update the cache.

Is this a poor understanding of how it's supposed to work?

**Comment by JoviDeCroock** [comment]
That's a good understanding of the semantics you are exposed to as a consumer, however there is more going on behind the scenes to keep data consistent. Rather than writing an optimistic update straight to the cache we'll have to save it into a layer, this way we can easily clear it when a result/error comes in from the real mutation. However what happens is that you can send a mutation like:

```
mutation x {}
```

twice, which results in the same key, so for us these two aren't different as we use an `operationKey` to identify which mutation is meant to represent a certain piece of data.

The concept of the data guarantees touched on in the first part are outlined [here](https://formidable.com/open-source/urql/docs/graphcache/normalized-caching/#deterministic-cache-updates) so not only optimistic updates are layered, individual operations are as well because queries could return results out of order, what happens when query 2 comes in before query 1? We'll have to make a layer on top of the cache and when query 1 comes in we write to the real data, clear the layer and write query 2.

**Comment by jesselee34** [comment]
I think I see what you're saying. Maybe I can provide some better context to how I actually found this issue. I think it's more likely to occur than you may be appreciating. That said, I am able to work around it by adding my own uniqueness to the operations themselves. This is a bit fragile though, since every mutation in my application will have to do this to avoid the bug.

In the real application we have various text fields, each with complicated business constraints which will cause a validation error. The requirement is that the field should be persisted regardless of whether the value triggers one of these constraints. We don't want these constraints to prevent a user from saving their progress.

How this race condition was discovered was that the user puts in a value that will trigger a validation error, they then change the value to try to fix the validation but happen to trigger a new validation, at which point the user just puts it back to what they initially changed it to. Since we're using the optimistic update to notify the validation system, what the user experiences when this happens is an out-of-date validation error because the value in the field no longer matches the value in the cache.

**Comment by kitten** [comment]
@jesselee34 So if I understand this correctly though, you're using optimistic updates to store UI state, or rather in progress state? The reason why I'm concerned about that is because the optimistic update is then explicitly not reflecting what the server should do. Also, if they see the error and change the value back then how would this trigger this issue if by then the error has been applied? That kind of sounds like this logic is actually applied on the front end too, but not in the UI, i.e. you're not preventing the mutation in the first place.

The reason why that's important is because we've found that any case that we can think of where one would run into this issue is a case that has these tiny "gotchas" that needed to be ignored before the issue is even made possible. So we're not saying it's unlikely to run into it, but we believe that any case that causes it is already subject to implementation issues that are out of our control.

**Comment by jesselee34** [comment]
The user is allowed to save progress whether or not a business constraint is triggered. So I'm not saving any "in progress state" in the UI that would be different than what the server's representation of the data would be at any given time.

Every field in my form will be subject to this race condition. The user just needs to change the value back to something they had previously set it to before the server responds. It will be especially likely with check box lists or radio lists since the values can be updated pretty fast.

I think I understand the problem with attempting to do this on the graphcache side. You wouldn't be able to distinguish between a like-change that was intended to behave like a unique operation and a retry, or any other re-run of the same operation.

I think adding some uniqueness to the mutations that are likely to encounter this is an acceptable workaround.

Thanks for all the help!
