### ISSUE TITLE
Cookies not sent on older browsers?

### ISSUE THREAD

**Issue by reverie** [FormidableLabs/urql#170]
Hi, sorry this is vague, but I've spent a couple days trying to fix this bug in my app and I think this is the last possibility. I don't know how this could make any sense. But if you have an idea, please throw it out there.

It's working fine almost everywhere. But on certain browsers (or devices?), I'm seeing no cookies being sent with requests made by the urql client. From the same browsers, cookies *are* being sent: on a normal GET request, on a normal form submission POST, and also on manually created XHR GET and POST requests. It doesn't matter if the urql client is created with a relative or absolute URL. It doesn't matter if the cookies are created with a Set-Cookie header or client-side with JS. The cookies are not http-only or secure-only. So I don't know what it could be, if not something the urql client (v0.2.2) is doing. Stumped.

**Comment by andyrichardson** [comment]
Hey @reverie  thanks for submitting this. Is this still a problem and, if so, are you able to provide an example reproduction?

It's probably worth noting that we use `fetch` for HTTP requests and you can pass in `fetchOptions` to the client in order to customise the request implementation. For example, there is a [credentials](https://developer.mozilla.org/en-US/docs/Web/API/Request/credentials) option which [may need to be set to `include`](https://stackoverflow.com/questions/34558264/fetch-api-with-cookie) in order to send cookies to a cross-origin address.

**Comment by kitten** [comment]
v1 is released now which means this issue was resolved / is out-of-date 👌

Some docs and a proper announcement for v1 are still in progress in pending. It's completely usable so far but the API has changed, so I have to ask for some more patience, but everything will be ready quite soon ✌️

**Extra note:** Not sure if this still applies to v1 though, so please reopen this issue or open a new one if this is still an issue

**Comment by reverie** [comment]
@andyrichardson Fetch was indeed the problem. I wonder whether urql should set a more permissive default value for the credentials option, to unify behavior across browsers.
