### ISSUE TITLE
RFC: access to graphcache directly

### ISSUE THREAD

**Issue by kelvin2200** [FormidableLabs/urql#1725]
## Summary

Expose the cache so that operations like `(read|write)Fragment` and `(read|write)Query` can be accessed globally

## Proposed Solution

Don't have one

## Requirements

The fact that such methods are NOT available except in a resolver context, should be stated in the docs
because the examples provided are UTTERLY CONFUSING. (please excuse my frustration)
```
import {gql} ....
cache.readFragment(...)
```
What does that mean??? Can I use the cache? ...because it seems I can't, though the example seems to point me in a direction where it might be possible???...

After searching for about 2 hrs through the docs with no luck, I came across this question
https://github.com/FormidableLabs/urql/issues/829

From what I understand, there is no plan for this to be implemented (though in my opinion this is a KEY * 1000 feature)
I fail to understand from the explanations why this is so problematic.
The cache is something where urql writes/reads under-the-hood.
Why is it available only in a resolver context, and why would it be problematic to expose it ???

I really hate it when coming across something that I really like, but is missing a key feature which makes it impossible for me to use.

As for a use case (which is also very wide), imagine a modular app, where modules are loaded based on some weird on-demand logic.

The modules have data dependencies of their own, and may need resolvers of their own, which you can't write initially because unless you actually get to use that module, it's basically dead code

Even if modules can "inject" their own resolvers at runtime (which I also haven't found a way to do... yet), certain on-demand functionality may have to modify (i.e. partially) an existing dataset. How would one do that, without having to go through a query or a mutation resolver... especially if one cannot be added to the existing graphCache. Also a resolver context imposes certain limits, like the inability to pass custom arguments.

Apollo, Relay... probably others, have this feature.

**Comment by JoviDeCroock** [comment]
Hey,

Sorry for the docs issue, feel free to shoot a PR :sweat_smile: also a proposed solution is more than welcome :eyes: 

As for the issue at hand, libraries like Apollo/Relay won't expose their internals to you either.

As in your linked issue, we designed graphcache around the concept of it being a normalized entity cache representation of a server-side source of truth. Once you start contradicting that source of truth, it becomes increasingly difficult to have confidence in the types of guarantees demanded by modern day data applications, including those that demand progressive enhancement (e.g. offline support, incremental delivery via code-splitting, etc).

Code-splitting, well that can be done with an object I guess. You mutate freshly loaded modules' updaters on the object and well it's modular.

```js
export let updates = { current: {} };
cacheExchange({ updates: updates.current })
```

When you import a module now you can deep-merge on that. To a point of "the inability to pass custom arguments." I wonder what these are needed for, what additional argument is used on the FE that the BE doesn't need? You can always add additional variables to your operation.

**Comment by kitten** [comment]
I wouldn't call this a key feature and that's something we've disputed in several issues 😄 Rather, it's a key feature that the cache _isn'_ arbitrarily modifiable.

Either way though, I'm closing this. it's fine if you'd like to ask questions, even if you'd like to politely voice some frustration, so we can clarify some API ideas of ours.
But it's not ok to abuse an issue template and subject us to a rant without any clear question even — just ranty assertions.

**Comment by kelvin2200** [comment]
I would like to apologize (again), if it seemed that I manifested uhm... something else other than my own frustration.
As for the fact that this shouldn't be/isn't a key feature, I strongly disagree. Furthermore... the issue is not that it's missing, just that it's "cloaked?"

I admit I didn't dig deep intro the pattern that urql uses, and I'm not pointing fingers or anything, but why does Apollo and Relay have methods for partially or entirely mutating existing data (that are not conditioned by a specific context). I mean... urql has them too with the only difference that you have to be in a resolver context. Technically inside an urql resolver where we can access the cache, we could write/modify any dataset (I could be wrong) by doing `cache.writeFragment(SomeContextUnrelatedDocument)`. If the cache is NOT arbitrarily modifiable?, ...I'm confused

Question:
While in a resolver context, we set a reference of the cache (once) on a global variable, and start calling methods like `writeFragment` on it from different parts of an app. What potential havoc is at bay by doing that?

**Comment by kitten** [comment]
That's pretty clearly elaborated in the issue you link though? As for why does Relay and Apollo have this and Graphcache doesn't? This isn't Relay/Apollo's cache for urql, but we're starting from first principles. And we can't find any single case where defining updates locally or modifying the normalised cache directly made sense and led to clean patterns.

Contrary to that, we found that having a centralised config and reactive updates / resolvers keeps it predictable.

> What potential havoc is at bay by doing that?

If we expand this, imho it becomes quite clear 😅 What potential havoc is caused by arbitrary updates on a globally mutable store, especially when the updates would be defined for interactions outside of GraphQL, which otherwise is our data's source of truth at all times?

**Comment by kelvin2200** [comment]
Got it... Not a feature, not on the roadmap. I'll be moving on. Thank you for your patience.

**Comment by huv1k** [comment]
👋 Hey, we are a little bit in a pickle, we wanted to use `urql`, but direct access to GraphQL cache is a blocker for us because we wanted to use it only for `read-only` access to get all objects by one `__typename`. Currently, we have normalized `stores` with our custom flux implementation before `redux` etc. and we want to migrate from it. We wanted to use https://formidable.com/open-source/urql/docs/api/graphcache/#inspectfields to incrementally migrate our normalized stores to GraphQL cache, but with our 300k+ lines codebase, it's really difficult to do it. We were thinking that we are going to use `writeData` from https://formidable.com/open-source/urql/docs/api/graphcache/#storage-option to dispatch to our stores, but this feels a little bit gimmicky 😅. Are there any other alternatives? 🤔 Maybe creating a custom exchange to work with our stores, but we would like to have one source of truth for data. This direct read-only access would help a lot during migration periods in a large codebase.

**Comment by kitten** [comment]
@huv1k Feel free to open a discussion thread with more details, but there are some potential solutions depending on your requirements. The problem here is though that I can't infer what data your stores hold or to what extent you're looking for a middle ground solution. Either way, middleground / compromise solutions aren't going to be pretty or easy in any case.

That said, read only access to the normalised cache would be facilitated by the `cache-only` request policy to data that's already in the cache. But it'd only apply to what's already in Graphcache.

The persisted storage API is unlikely to help you here, as it's only intended to store and rehydrate the state of the normalised cache asynchronously. The latter occurs only once at startup and this isn't to interface with a secondary, synchronous store.

Resolvers together with cache-onoy queries do allow you to access data without sending new operations to your API, but either way, eventually a query will have to be dispatched.

I'm not quite sure how that'd relate to your current state management code as we basically are facilitating a "closed box"-style GraphQL client, i.e. the normalised cache is opaque to the outside world to stop cache modifications from occuring that would put it into "impossible" states based on what you'd usually get from cached or real GraphQL results.
