### ISSUE TITLE
Issue #1716 not fixed : Svelte : TypedDocumentNode does not play well with Typescript for subscription

### ISSUE THREAD

**Issue by V-ed** [FormidableLabs/urql#1750]
After updating to `@urql/svelte@1.2.3` (which contains #1731), I went and checked if my issue from #1716 was fixed and it seems to be there again :

![image](https://user-images.githubusercontent.com/16652915/123488077-36deec80-d5dd-11eb-982e-b4eb8c4991e5.png)

This time however, my `data` variable is indeed properly typed (it is a `NewMessagesSubscription` instead of `any`).

cc @kitten

_Originally posted by @V-ed in https://github.com/FormidableLabs/urql/issues/1731#issuecomment-868850256_

**Comment by V-ed** [comment]
I use the following file in the meantime to fix my issue :

<details>
<summary><code>urqlsvelte.d.ts</code></summary>

```ts
import { OperationStore, SubscriptionHandler } from '@urql/svelte';

declare module '@urql/svelte' {
	export declare function subscription<Data = any, Result = Data, Variables = object>(
		store: OperationStore<Data, Variables>,
		handler?: SubscriptionHandler<Data, Result>,
	): OperationStore<Result, Variables>;
}

```

</details>

**Comment by kitten** [comment]
Happy to discuss this in the original issue, #1716, but let's not create more duplicates. For now, I haven't quite looked into this, but I did test this, so I'm surprised by this. However, I think it depends on how TypeScript infers types once again. Also, using a return value of `OperationStore<Result, Variables>` is plain incorrect. The input and output types here must match, which is why I've added a third generic. If TypeScript turns out not to be smart enough to infer this with little information however, it's possible that we'll have to keep it at that.
