### ISSUE TITLE
useQuery not updated after local resolves  

### ISSUE THREAD

**Issue by zhihengGet** [FormidableLabs/urql#1786]
version & exchanges:
latest
**Steps to reproduce**

1. in graphcache, create a local resolver that returns undefined
2.  create a query that will use that local resolver , a request is made, but after response (saw it in network ), useQuery didn't update react state and got an fetch successful , the data field is null which is weird

**Expected behavior**

if undefined is returned , and request is made, state should have that response but not

**Actual behavior**

request made, response received, but use Query no got update

**Comment by kitten** [comment]
Sorry, but we have examples and templates including example APIs for creating reproductions, so the minimum we ask for is either more investigation work or a small reproduction, since that really just takes a few minutes in the examples we have 😅 We can reopen this issue once confirmed or answer related usage questions here
