### ISSUE TITLE
When two identical queries are executed and one is paused then both are aborted and return no data

### ISSUE THREAD

**Issue by wereHamster** [FormidableLabs/urql#1841]
urql version & exchanges: urql 2.0.4, cache exchange 4.2.1

**Steps to reproduce**

 - Have two identical queries
 - Both not paused (so they start executing)
 - Then pause one of the two
 - The fetch request (if it was sent) is aborted, both queries return no data (even the query that was not paused).

https://codesandbox.io/s/nifty-feather-e3esz?file=/pages/index.js

The page shows the result from the two queries. I'd expect the first line to read `{"fetching":false,"stale":false}` (because the query is paused), but the second line to dump the data into the page, since the query in the second component is not paused.

**Expected behavior**

 - Fetch request should not be aborted, any other parallel and non-paused query should continue executing as usual.
 - The paused request may or may not return data (since the data will be fetched by the other request and stored in the cache).

**Actual behavior**

The second query never resolves, even though it is not paused.

**Comment by JoviDeCroock** [comment]
This happens because of the following, the `dedupExchange` filters out the second operation and lets the first go through, the first subsequently gets torn down meaning that neither are in flight. We'd have to solve this by tracking if there was some kind off deduped operation that didn't get a response yet.

So we see operation2 getting deduped due to `key1 === key2`, operation1 gets deduped but we know operation2 still waits for a response.
