### ISSUE TITLE
(graphcache) - Partial results aren't refetched

### ISSUE THREAD

**Issue by augustas1** [FormidableLabs/urql#1867]
Partial results on arrays are not being refetched when required data is missing.

urql version & exchanges:
"urql": "^2.0.4"
 "@urql/exchange-graphcache": "^4.1.4"
Schema integrated.

**Steps to reproduce**

1st query:
```
project {
  id
}
```
returns `[ { id: 1} ]`

2nd query:
```
project {
  id
  title
}
```
Queries are executed sequentially.

**1st Working scenario (when missing optional field)**

If `title` field is `optional` in schema, then 2nd query returns partial results `[ { id: 1, title: null } ]`, results are marked as `stale` and fallbacks to refetching (to fetch the `title`).

**2nd Not working scenario (when missing required field)**

If `title` field is `required` in schema, then 2nd query returns `[ null ]`. Cached result seems correct. But results aren't marked as `stale` and refetching isn't done as in the 1st scenario.

**Expected behavior**
Results should be marked as stale and refetched (2nd scenario).

**Actual behavior**
Results are not stale and not refetched (2nd scenario).

**Comment by kitten** [comment]
cc @JoviDeCroock: Seems like a rather simple fix.
The offending part of the code only performs partial logic when the field is nullable directly; however, it doesn't do anything when cascading, hence we need to update it to perform the `hasPartials` update when the schema is available and alter the return value based on `isFieldNullable`, rather than only doing that when the field is nullable. In other words, we'll update this to cascade anyway:

https://github.com/FormidableLabs/urql/blob/6cc8a24c99d4f6c633f5cd02099a569d4a317c33/exchanges/graphcache/src/operations/query.ts#L419-L427

I'll wait on #1854 to patch this.
