### ISSUE TITLE
(graphcache) - Overlapping queries that error trigger each other

### ISSUE THREAD

**Issue by bartenra** [FormidableLabs/urql#1954]
**urql version & exchanges:**

```
    "@urql/exchange-graphcache": "^4.3.3",
    "@urql/vue": "^0.4.3",
```

**Steps to reproduce**

Schema:

```graphql
  type User {
    id: ID!
    likesCheese: Boolean!
  }

  type Query {
    me: User
  }
```

Query One:

```graphql
{ 
  me {
    id
    likesCheese 
  }
}
```

Query Two:

```graphql
{
  me {
    id
  }
}
``` 

Enable `cacheExchange`.

Use `useQuery` for both queries.

Make sure the query fails.

**Expected behavior**

Both queries fail. The end.

**Actual behavior**

Urql is spamming the server with queries.

![image](https://user-images.githubusercontent.com/77667589/133075104-c946e0f3-3b05-4b20-b92e-ddf0d6dc758d.png)

![image](https://user-images.githubusercontent.com/77667589/133101669-dd3eaa8c-63c3-4b9e-817e-d28ffdb2e2fa.png)

**Reproduction:**

1. Clone https://github.com/bartenra/urql-ddos-repro
2. `npx vite --port 3001`
3. (other tab) `cd backend && node index.js`
4. Go to `localhost:3001`
5. Open network tab

**Background:**

I am assuming that the error response from one query invalidates the other, causing the other to be re-run, and then vice versa. But this is not what I expect, because I might need queries that overlap and that can error out (for example, if the user is not authenticated) in different parts of an application.

**Comment by kitten** [comment]
This is a bit suspicious to me and I'll have to take a look at the reproduction next week once I'll have time again.

Typically, we wouldn't expect to see this. As you pointed out, it isn't entirely unexpected to see this, as both queries overlap. However, the reason why this is clearly nonsensical is that both queries are complete, meaning they're entirely cached, so it doesn't make sense for them to refire.

The only thing I can explain this to myself with is that on receiving a result, the Vue component runs through an entire unmount & remount cycle or instead a restart of the query result source. The only other explanation is that something's explicitly triggering another network request.
Either doesn't really seem to make sense though either, hence I'll have to look and see what's causing this

**Comment by bartenra** [comment]
Glad to hear this is also unexpected for you!

I have two very simple templates:

```vue
<script setup lang="ts">
import { useClientHandle } from "@urql/vue";

const handle = useClientHandle();
const { error } = handle.useQuery({
  query: `
{ 
  me {
    id
    likesCheese 
  }
}` });
</script>

<template>
  <pre>{{ error }}</pre>
</template>
```

So I think it's unlikely that unmount & remount is happening. Just to be sure, I tried sticking a `onMounted` in there, which confirmed that it's only mounting once. However, it's updating rapidly (confirmed with `onUpdated`). Which I guess makes sense since the `error` ref keeps being updated.

Thanks for having a look at it!

**Comment by kitten** [comment]
@bartenra Yea, what I was referring to isn't "generic updates" but specifically whether a new query source is restarted here: https://github.com/FormidableLabs/urql/blob/63eec7eb8b6efeb49c0bb27249dec58d12121d2a/packages/vue-urql/src/useQuery.ts#L91-L112 But even if that's happening, I wouldn't be able to say why that is just yet. That'd be really odd 😆

**Comment by yankovalera** [comment]
I've been able to reproduce this in React, here are my findings:

- Queries are re-executed in executePendingOperations() method with client.reexecuteOperation
- I think the issue is this check https://github.com/FormidableLabs/urql/blob/main/exchanges/graphcache/src/cacheExchange.ts#L207: it's testing for data, and in the sample code data is {me: null}. I'm not sure if I'm missing something but I think a possible fix is to check for !result.error?

If this is the actual error, I'm happy to create a PR with a fix

**Comment by JoviDeCroock** [comment]
@yankovalera it's intended that we don't check for `result.error` as we pass that on to `write`, this because in queries we can have partial failures, when there's a partial failure we still want to persist this to the cache. In `write` you'll see that we track the `graphqlErrors` and see which field errored and see whether or not that's an optional field https://github.com/FormidableLabs/urql/blob/main/exchanges/graphcache/src/operations/write.ts#L279

**Comment by kitten** [comment]
@yankovalera if you're saying that this only happens when `me` has errored in any of the two queries then it'll depend on the error handling. This is because, I believe, with errors we do stop reexecution. We basically have some logic that checks whether any known path has an associated error. However, even so, if the `me` field is actually set to `null` then it's set to `null`, so that doesn't really imply that there'd be a cache miss.

It seems more likely to me that if this is the error handling that the error is associated to the `me` field, which may be triggering both queries one after another since neither are complete? Because, if so, that seems rather expected to me (for better or not) since one query overlaps the other, which then changes and isn't completely cached and hence refetched

**Comment by yankovalera** [comment]
@kitten @JoviDeCroock in the provided code, the me Query resolver is this

```
const resolvers = {
  Query: {
    me: async (_, obj) => {
      throw new Error("Unauthenticated");
    },
  },
};
```

This is causing queries to fires one after other forever - I think because they're dependant.

**Comment by kitten** [comment]
Ok, I actually didn't see that, which is why I wasn't able to immediately guess the problem. The underlying problem here is in how we determine "cacheability". If a given query is run twice should an error be cached? The answer — for multiple arguments in GraphQL — is a clear no. An error isn't cacheable because there's no indication of it being repeatable.

> But this is not what I expect, because I might need queries that overlap and that can error out (for example, if the user is not authenticated) in different parts of an application

What's important to this specific issue here is that it was already mentioned what the intention is. However, if the application is used in an unauthenticated manner, the `me` resolver likely shouldn't throw but utilise `null` instead, since an error doesn't indicate acceptable absence of data but unacceptable absence of data 🤔

Anyway, these are the factors that pushed us to implement error aware caching in the first place. Errors should always be handled, but a cache that forces the user to not only acknowledge it but dismiss it (with a 'hard-ish' refresh/reexecute) isn't doing its job well. Instead "unacceptable absence" became our measure. An error shouldn't be cached and hence its field (which is set to null at the error or at a parent field) shouldn't be cached.
