### ISSUE TITLE
Relay pagination in cache exchange breaks querying totalCount

### ISSUE THREAD

**Issue by Tam** [FormidableLabs/urql#2007]
urql version & exchanges:
```
"@urql/exchange-auth": "^0.1.6",
"@urql/exchange-graphcache": "^4.3.3",
"@urql/exchange-multipart-fetch": "^0.1.13",
"@urql/exchange-retry": "^0.2.1",
```

**Steps to reproduce**

1. Setup your client with the following cache exchange:
```js
cacheExchange({
    resolvers: {
        Query: {
            users: relayPagination(),
        },
    },
}),
```

2. Try to query data from the `users` query (or your relay paginated query) that _doesn't_ include paginated data.
```graphql
query GetTotalUsers {
  users {
    totalCount
  }
}
```

**Expected behavior**
Query should return object with total count:
```js
{ users: { totalCount: 124 } }
```

**Actual behavior**
Query returns `null`.

**Comment by Tam** [comment]
Specifying the `first` param works as a work-around to get the response.

```graphql
query GetTotalUsers {
  users (first: 1) {
    totalCount
  }
}
```

I should note that the query to the server is always successful, it's URQL parsing/caching the data that causes the issue. It's also fine if you remove the `relayPagination()` from the exchange.

**Comment by LeBenLeBen** [comment]
FYI this issue can be reproduced with `simplePagination` as well.

**Comment by JoviDeCroock** [comment]
After testing and talking this over a bit through #2137 we came to the conclusion that this is actually not spec-compliant as it doesn't include paginated arguments. This means that using `users (first: 1)` is actually the correct approach.

[Spec](https://relay.dev/graphql/connections.htm#sec-Arguments)

> A field that returns a Connection Type must include forward pagination arguments, backward pagination arguments, or both.

This means that passing `users (first: 0)` is also a possibility

**Comment by JoviDeCroock** [comment]
Hey all,

After researching this a bit in #2137 we concluded that this is actually against the [`relay-spec`](https://relay.dev/graphql/connections.htm#sec-Arguments)

> A field that returns a Connection Type must include forward pagination arguments, backward pagination arguments, or both.

Which means we always need a arguments to support paginating, so in essence `first: 1` working is the right thing here. In general the `relay-spec` specifies that we _can_ support arbitrary arguments on the connection which will work for arguments as you alluded to _but_ without arguments we'd have to pick these from a random-page which isn't guaranteed to be correct.

**Comment by kitten** [comment]
Closing this for now, due to a lack of responses.
As stated above, [additional `*Connection` fields are generally allowed by the spec](https://relay.dev/graphql/connections.htm#sec-Connection-Types.Fields):

> Connection types must have fields named edges and pageInfo. They may have additional fields related to the connection, as the schema designer sees fit.

However, if we query for instance `users` rather than `users(first: 10)` then we don't have any "real" result that we can pick out to resolve these fields from. In other words, all we can do is use the fields that are known to us per a real API result that's being referred to.

That said, since `totalCount`, in theory, never changes across pages, it wouldn't be infeasible to write a wrapper around `relayPagination` that adds it on from any given page. Basically, since it's "out of spec" we can only make basic assumptions here.

---

I'll close this issue for now, but happy to keep any questions or discussions ongoing :v: I of course also don't exclude the possibility that there may be more potential factors here that do allow us to improve what's done here, so maybe we'll revive this in the future, if we have a different added perspective here 😄

**Comment by LeBenLeBen** [comment]
Would it be possible to add a warning somehow? Since apparently it’s possible to know that the param is required but missing?

I don’t bother adding these params, it’s just that sometimes I forgot them and spend 15 minutes wondering why no results nor error would show.
