### ISSUE TITLE
(persisted-fetch) - The Node Crypto API is not available.

### ISSUE THREAD

**Issue by bulby97** [FormidableLabs/urql#2077]
Using nextjs 12, when trying to use Automatic Persisted Queries using Node `lts/fermium`, I got this error:
`[@urql/exchange-persisted-fetch]: The Node Crypto API is not available.`

In order to make it work, I copied the [hash.js file](https://github.com/FormidableLabs/urql/blob/00ad6421b8f08ce41892b14c91e12464f59d4202/exchanges/persisted-fetch/src/sha256.ts#L42) locally and replaced the `nodeCrypto = new Function('require', 'return require("crypto")')(require);`by `nodeCrypto = require('crypto')`

```
export const client = createClient({
  url: `${process.env.BACKEND_URL}/graphql`,
  preferGetMethod: true,
  exchanges: [
    dedupExchange,
    cacheExchange({
      updates: {...},
      optimistic: {...},
    }),
    persistedFetchExchange({
      preferGetForPersistedQueries: true,
    }),
    fetchExchange,
  ],
  fetchOptions: () => {
    const token =
      typeof window !== 'undefined' ? localStorage.getItem('jwt') : undefined
    return {
      headers: { authorization: token ? `Bearer ${token}` : '' },
    }
  },
})
```

urql version & exchanges:

urql: ^2.0.5
urql/exchange-persisted-fetch: ^1.3.2

1. 2.

**Expected behavior**
No error message

**Actual behavior**
Error message

**Comment by kitten** [comment]
We may need a further reproduction here or more information on this; for instance, while it's clear that this may be a problem with Next.js 12, and we could just look into this, in order to reduce work for whomever will pick this up it'd be great to know whether this is happening on the frontend or in Node.js; If it's happening on the frontend it could very well be a Next.js issue with bundling in general, if it's on the backend, it could be a problem with Next.js transpiling the Node.js code incorrectly.

Basically, if you're replacing `new Function('require', 'return require("crypto")')(require);` this could still be a frontend issue as you're then instructing Webpack to add a rather huge polyfill for the `crypto` Node API on the client-side. The intention of that code is to explicitly avoid this and never require any polyfill or external code to be added. Hence, this obscures this built-in Node module so that client-side builds never use the `"crypto"` module.

If this is happening on the backend however, we'll have to see what's happening to `require` and why we're unable to get the builtin module there.

**Comment by bulby97** [comment]
I understand ! Thank you !

Here is the [repo](https://github.com/bulby97/next-urql-exchange-persisted-fetch)

**Comment by yankovalera** [comment]
Hi, I've been checking the provided sample and I think could be related to the new [rust compiler](https://nextjs.org/blog/next-12#faster-builds-and-fast-refresh-with-rust-compiler) Next 12 is using.

**Comment by stefanaxelsson** [comment]
I do not think it is related to swc. I tested importing crypto in Next 12.0.4 the same way persisted-fetch does with babel and swc:
```
if (typeof window === 'undefined') {
    try {
        // Indirect eval/require to guarantee no side-effects in module scope
        // (optimization for minifiers)
        nodeCrypto= new Function('require', 'return require("crypto")')(require);
    } catch (e) {}
}
```

Results in the same error in both cases: `Critical dependency: require function is used in a way in which dependencies cannot be statically extracted` and nodeCrypto being undefined. [Which is a webpack error](https://github.com/webpack/webpack/blob/cc990fe13cff3729d37281cacac71f1cf230717d/lib/dependencies/CommonJsImportsParserPlugin.js#L150).

Using import or require works:
`import nodeCrypto from 'crypto';`

**Comment by JoviDeCroock** [comment]
Using `import nodeCrypto from 'crypto'` will include it in the bundle unless you explicitly provide an empty stub for it. Maybe Webpack 5/ Next 12 have a new way of dealing with this.

**Comment by stefanaxelsson** [comment]
From what I can see using 
`let nodeCrypto;
if (typeof window === 'undefined') {
    try {
        // Indirect eval/require to guarantee no side-effects in module scope
        // (optimization for minifiers)
        nodeCrypto = require('crypto');
    } catch (e) {}
}
` 
Does seem to work. Without the`if (typeof window === 'undefined')` an additional ~0.5mb of javascript is added to the client bundle.

**Comment by JoviDeCroock** [comment]
Sadly that does only automatically work for Next, other applications aren't doing an auto-replace of `typeof window` 😅

**Comment by kitten** [comment]
I think what's worth investigating here is how crypto is not loading:
> [@urql/exchange-persisted-fetch]: The Node Crypto API is not available.
Because this already implies that `typeof window === 'undefined'` is returning true, but the `require('crypto')` call that is eventually done does not succeed.
> Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
Regarding this output; It's not a straight-up error. I've seen it before and it shouldn't break the build unless something really odd is going on. It simply should bail out on the require-eval call in question, which is intended

**Comment by stefanaxelsson** [comment]
Ah, should have added the actual exception as well:

```
 ReferenceError: require is not defined
    at file://...//node_modules/@urql/exchange-persisted-fetch/dist/urql-exchange-persisted-fetch.mjs:31:61
    at ModuleJob.run (internal/modules/esm/module_job.js:170:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
```

**Comment by stefanaxelsson** [comment]
Ah, not sure if I'm helping or not but the error thrown is:
```
 ReferenceError: require is not defined
    at file://..//node_modules/@urql/exchange-persisted-fetch/dist/urql-exchange-persisted-fetch.mjs:31:61
    at ModuleJob.run (internal/modules/esm/module_job.js:170:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
```

**Comment by kitten** [comment]
@stefanaxelsson That's in fact super helpful 👍 so that's very telling; we're apparently in ESM mode in Next.js with Node here and hence can't use `require`. So that puts us into a spot where we'll either have to choose to split this into browser and non-browser bundles or do a similar approach to this with an async `import()` in the catch

**Comment by ryan-roemer** [comment]
Hi! So, I haven't built any of the below code at all, but just in case it's useful, here's something I've been hacking and testing out, design-wise.

In `sha256.ts`, switch from top-level import to async getter function (aka what @kitten suggested):

```js
let _nodeCrypto;
const getNodeCrypto = async () => {
  // Memoize.
  if (typeof _nodeCrypto !== 'undefined') { return _nodeCrypto; }

  // Default. Couldn't resolve (and will stay memoized).
  _nodeCrypto = Promise.resolve(undefined);

  if (typeof window === 'undefined') {
    try {
      _nodeCrypto = await new Function('return import("crypto")')();
    } catch (e) {}
  }

  return _nodeCrypto;
};
```

Then, consume like:

```ts
export const hash = async (query: string): Promise<string> => {
  const nodeCrypto = await getNodeCrypto();
  // ... all the rest of the other code.
};
```

or in transpiled CJS form:

```js
module.exports.hash = async (query) => {
  const nodeCrypto = await getNodeCrypto();
  // ... all the rest of the other code.
};
```

This should work with any of the following (assuming transpiled output names):

```js
// CJS
const { hash } = require("./sha256.cjs");
const { hash } = await import("./sha256.cjs");

// ESM
import { hash } from "./sha256.mjs";
const { hash } = await import("./sha256.mjs");
```

Some caveats:

- I don't know if `new Function('return import("crypto")')()` will correctly keep the crypto lib out of all frontend bundlers. I haven't even tried any. But it's a string, so hopefully?
    - And it avoids having to use the named `require` variable which will cause some issues in situations discussed above.
- The `import()` only works in Node.js v12.17.0 (at least without esm flags). So that's going to mean more Node.js runtimes have to use the non-node crypto code.

At any rate, hope that helps if this is a direction we want to experiment with!

**Comment by kitten** [comment]
`@urql/exchange-persisted-fetch@1.3.3` should be resolving this issue, however, we're hoping that there's no bundlers or setups out there that will run into more issues with the improved handling of ESM Node. So, do let us know if it's working or still broken for anyone, or if there's more environments that we've missed.
We do still want to avoid costly polyfills or JS-only implementations and the native APIs here are very important to us, so if they need further adjustments we'll come back to this once more :v:
