### ISSUE TITLE
executeQuery does not trigger a request since v2.0.5

### ISSUE THREAD

**Issue by remon-nashid** [FormidableLabs/urql#2092]
Like many users reported before, `executeQuery` returned by `useQuery` does not trigger a GraphQL request. Unlike the previous bug reports though, I cannot get it to work with neither a paused, a non-paused query, `network-only`, `network-and-cache` or any other combination of context options.

urql version & exchanges:
The issue occurs with the latest package versions.
- urql 2.0.5
- @urql/core 2.3.5

**Steps to reproduce**

1. Call `executeQuery({ requestPolicy: 'network-only' })`
2. Watch `network` tab in your favorite browser and you'll see no requests sent at all.

**Expected behavior**

Should work as described.

**Actual behavior**

It doesn't.

Thank you.

**Comment by remon-nashid** [comment]
Downgrading to version `2.0.4` resolves the issue.

**Comment by JoviDeCroock** [comment]
We always ask for a reproduction because the issue description can be misleading, I've quickly tried to verify your issue but could actually not reproduct it. The button performs what you describe but always seems to spawn a network request.

[reproduction](https://codesandbox.io/s/pensive-forest-7knn1?file=/src/components/Todos.js)

**Comment by remon-nashid** [comment]
Hmmm, unfortunately I cannot demo the bug within my private repo since it's not easy to extract. 

@JoviDeCroock the reproduction app attached looks legit and works fine on my end, too. Closing this issue and will continue to debug the issue locally. Thanks.
