### ISSUE TITLE
Using fragment in other fragment makes the object `null`; the same fragment in the query not

### ISSUE THREAD

**Issue by frederikhors** [FormidableLabs/urql#2108]
### Discussed in https://github.com/FormidableLabs/urql/discussions/2103 _but I think this is a bug and not a question_.

If I use the below code it doesn't work, the second query (`team()`) makes the player `null` in cache.

```graphql
fragment PLAYER on Player {
  id
  createdAt
  team {
    ...TEAM
  }
}

fragment TEAM on Team {
  id
  createdAt
}

query player($id: ID!) {
  player(id: $id) {
    ...PLAYER
  }
}

query team($id: ID!) {
  team(id: $id) {
    ...TEAM
    player {
      ...PLAYER
    }
  }
}
```

The code below addresses the issue (this is the only change I do in my code base):

```graphql
fragment PLAYER on Player {
  id
  createdAt
  # removed these lines from here:
  # team {
  # 	...TEAM
  # }
}

fragment TEAM on Team {
  id
  createdAt
}

query player($id: ID!) {
  player(id: $id) {
    ...PLAYER
    # to here:
    team {
      ...TEAM
    }
  }
}

query team($id: ID!) {
  team(id: $id) {
    ...TEAM
    player {
      ...PLAYER
    }
  }
}
```

My question is: why it works in queries and not in fragments?

**Comment by kitten** [comment]
Sorry, I'm closing this and have to ask you to keep it to the discussion first for two reasons;

- There's no inherent difference between traversal with or without fragments. Traversal is absolutely identical and the only addition is the decision whether to traverse a fragment found in a selection set
- The outcome of the discussion is unclear. If it's hard to reproduce, explain, or pin down to a suspected issue, then it's still not ready for a bug report. While we can help get there and an issue would achieve the same, the alternative here for me is to tack on a "needs more information" label, but since the discussion is still ongoing, that doesn't make much sense

Hope that works for you ✌️ also on a side note, the most likely problem here is that you don't have a reverse link built up from responses and if your fragments lead into each other you may accidentally create a loop that neither Graphcache nor your API can resolve

**Comment by frederikhors** [comment]
I have a repro!!! 😃😃😃😃

I'm creating a repo in git here, here the gif:

![issue](https://user-images.githubusercontent.com/41120635/143720552-de19bca4-408c-4421-873d-3540fd4b5bc6.gif)

**Comment by frederikhors** [comment]
I have a reproduction: https://github.com/frederikhors/iss-urql-fragment-null-obj

😃😃😃😃

### The steps

- git clone https://github.com/frederikhors/iss-urql-fragment-null-obj
- npm install
- go to https://codesandbox.io/s/apollo-server-urql-svelte-crud-h1pcl to start the server
- npm run dev

### The gif
![issue](https://user-images.githubusercontent.com/41120635/143720552-de19bca4-408c-4421-873d-3540fd4b5bc6.gif)

**Comment by frederikhors** [comment]
> * There's no inherent difference between traversal with or without fragments.

This is what I thought too. But moving that fragment into the query then everything works.

> the most likely problem here is that you don't have a reverse link built up from responses

How to create it?

> if your fragments lead into each other you may accidentally create a loop that neither Graphcache nor your API can resolve

I think I'm not in a loop in this case.

**Comment by frederikhors** [comment]
@kitten since Github has been down for a long time I don't know if you have seen these answers, excuse the ping.
