### ISSUE TITLE
RFC: graphql@16 support

### ISSUE THREAD

**Issue by adam-h** [FormidableLabs/urql#2130]
## Summary

`graphql-js` updated to [v16](https://github.com/graphql/graphql-js/releases/tag/v16.0.0) ([16.0.1](https://github.com/graphql/graphql-js/releases/tag/v16.0.1) as of writing) recently and there are a few, minor, breaking changes. Mostly around type tweaks.

## Proposed Solution

Update `graphql` (peer)dependency to v16, and associated types/usage.

**Comment by kitten** [comment]
Just checked, as expected no breaking changes, at least in our context. I've already seen the more "severe" changes when working on `graphql-web-lite` a while back, since that built off of `graphql@16.0.0-alpha.1` back then, but for `urql`'s purposes we're mostly only seeing snapshot breakage from the lacking trailing newlines in printed queries.

**Comment by jgoux** [comment]
I just upgraded and it seems like webpack 5 (used in the context of storybook) isn't able to correctly resolve the `@urql/execute-exchange` package when using `graphql@16.1.0` : https://github.com/FormidableLabs/urql/discussions/2139

**Comment by JoviDeCroock** [comment]
This will be fixed in https://github.com/kitten/babel-plugin-modular-graphql/pull/4 @jgoux

**Comment by jgoux** [comment]
> This will be fixed in [kitten/babel-plugin-modular-graphql#4](https://github.com/kitten/babel-plugin-modular-graphql/pull/4) @jgoux

You replied 28 sec after I posted, are you a wizard? 😂 

Thanks @JoviDeCroock ! 🚀
