### ISSUE TITLE
Add promisified request methods on the Client (especially for non-React API calls)

### ISSUE THREAD

**Issue by CaitlinWeb** [FormidableLabs/urql#216]
Thanks for this library. I'm new to GraphQL and wanted to find a library that would work with React and had active maintainers. (For instance, both `Lokka` and `graphql-request` seem to have been abandoned 🤷‍♀️ )

My only issue is I have a use case with the need for a GraphQL request outside of React. (The use case is on the server, checking if the user exists and create one if not.) Therefore, I can't use `<Query />` or `useQuery`, etc. It took a bit, but I figured out this is possible using `urql` thanks to the "Extending & Experimenting" documentation:

```javascript
const { pipe, subscribe } = require('wonka');
const { client, createRequest } = require('urql');

// create the client
const client = createClient(/*...*/);
// create the request
const request = createRequest(`query { ... }`, { variables });
// send to api
pipe(
	client.executeQuery(request),
	subscribe(({ data, error }) => {
		console.log(data, error);
	})
);
```

While this works, it's not pretty and Wonka doesn't currently have much documentation. I'm not sure if this code works in all cases.

I would *love* it if there was a utility function exposed that does the `pipe(...)` portion in the above code sample. Something that returns a promise I can chain off of, like:
```javascript
// send to api
sendRequest(client, request)
    .then((data, error) => {/*...*/})

// could also be something like
client.sendRequest(request)
   .then((data, error) => {/*...*/})
```

Thoughts?

**Comment by kitten** [comment]
I do have to write up documentation and release a nice site for Wonka! Apologies that that process isn't as easy yet as it should be 😢 

We actually have left off promisified variants of `executeQuery` after multiple refactors, since we weren't sure whether they're any use to someone, so this is definitely a signal that they indeed _are useful_.

You can also use the `toPromise` helper in Wonka to make this nicer for now, this would mean that you can at least convert the `Source<OperationResult>` to a promise, if you don't care about cancellation.

This is the operation in question: https://github.com/kitten/wonka/blob/master/src/web/wonka_sink_toPromise.d.ts

So to combine your code snippets into "one" by using `toPromise`, this would become:

```js
const { pipe, toPromise } = require('wonka');
const { client, createRequest } = require('urql');

const client = createClient(/*...*/);
const request = createRequest(`query { ... }`, { variables });

pipe(client.executeQuery(request), toPromise)
  .then(({ data, error }) => {/*...*/})
```

Please do note that no error is ever thrown and is instead on the result object. This is a convenience feature, since errors can happen in all sorts of ways in GraphQL, so we actually have an `error` property with our `CombinedError` on the result.

This still needs to be hinted at in the documentation a little more, but that's on my todo list :+1:

I think we can provide convenience wrappers for promise-based executions though :+1: seems very reasonable!

**Comment by CaitlinWeb** [comment]
@kitten Thanks for the fast response and detailed explanation! I will use `toPromise` for now, and am looking forward to those enhancements 😃 

If there's any feedback/help needed let me know; I can give you more details about my use case(s), for instance.

**Comment by kitten** [comment]
I'm not sure whether it'd make sense to add all these methods, since it's a particularly special use-case actually 🤔 

Do you think it'd be sufficient to add this to the documentation instead? Maybe as a guide or recipe?

**Comment by CaitlinWeb** [comment]
That's understandable, since urql is a React library and there are other libraries that handle fetching GraphQL queries outside of React. Personally I would rather use one library for GraphQL requests, though, so exposing the fetch functionality is a "nice to have". But, since it sounds like that's out of scope, adding this to documentation would be a good compromise 👍 

Before you write it up, though, you should know I tried out using `toPromise` and it fails silently without resolving. I see the fetch complete successfully but `then()` never gets called.

So I've been using this, which works:

```javascript
new Promise(function(resolve) {
	pipe(
		client.executeQuery(request),
		subscribe(resolve)
	);
})
  .then(({ data, error }) => {/*...*/})
```

I can open a new issue in the wonka repo for troubleshooting `toPromise` if you'd prefer.

**Comment by narinluangrath** [comment]
I'd also find wonka documentation really helpful for both this use case and for implementing custom exchanges.

**Comment by good-idea** [comment]
I have a similar use case *within* react. What I'm looking for is a middle-ground between the convenience of hooks and `executeQuery`.

It would be great if there were a simpler way to create queries & mutations for imperative-only usage. Maybe something like `client.createQuery`?

I have a component that handles a lot of mutations & queries, and handles the overall state with a reducer instead of the state returned by `useQuery` and `useMutation`. It looks a little bit like this:

```ts

export const useCheckout = (): UseCheckoutProps => {
  /**
   * Hooks setup
   */
  const [state, dispatch] = useReducer(reducer, initialState);
  const [, checkoutQuery] = useQuery({ query: CHECKOUT_QUERY });
  const [, addMutation] = useMutation(ADD_MUTATION);
  const [, createMutation] = useMutation(CREATE_MUTATION);
  const [, updateLineItemMutation] = useMutation(UPDATE_LINE_ITEM_MUTATION);
  const [, applyDiscountMutation] = useMutation(APPLY_DISCOUNT_MUTATION);
  const [, removeDiscountMutation] = useMutation(REMOVE_DISCOUNT_MUTATION);

  /**
   * On load, fetch the checkout if a token exists
   */

  useEffect(() => {
    if (
      initialCheckout.fetching ||
      !initialCheckout.data ||
      !initialCheckout.data.node
    )
      return;
    const checkout = initialCheckout.data.node;
    dispatch({ type: FINISHED_REQUEST, checkout });
  }, [initialCheckout.fetching]);

  /**
   * Public Functions
   */
  const addToCheckout = async (args: AddToCheckoutArgs) => {
    dispatch({ type: STARTED_REQUEST });
    const result = await addMutation(variables);
    dispatch({ type: FINISHED_REQUEST, ...result.data.checkoutLineItemsAdd });
  };

  return {
     ...state,
     addToCheckout,
     /* other functions */
  }
```

This has a couple disadvantages:

 - When I execute my mutations, the component re-renders twice: once when the mutation completes, and again after the call to `dispatch({ ... })`. I'd prefer that it only re-renders after dispatch.
 - I have to do some hooks gymnastics for the initial `useEffect` - since `useQuery`'s initial state has `{ fetching: false }`, this is kind of tricky. (In my case, the code above won't always work because it's possible that `initialCheckout.data` might return as `undefined` after the query has finished.)

I can (and will) avoid this by using `client.executeQuery` instead, but this comes with the overhead of needing to use `createRequest` to generate the key, etc, and requires some knowledge of how urql is working internally.

It would be great to be able to rewrite the above to be something like this:


```ts
export const useCheckout = (): UseCheckoutProps => {
  /**
   * Hooks setup
   */
  const client = useContext(UrqlContext)
  const [state, dispatch] = useReducer(reducer, initialState);
  const checkoutQuery = client.createQuery({ query: CHECKOUT_QUERY });
  const addMutation = client.createMutation(ADD_MUTATION)
  /* etc */

  /**
   * On load, fetch the checkout if a token exists
   */

  useEffect(() => {
    const variables = { /* some variables */ }
    const result = await checkoutQuery(variables)
    const checkout = result.data && result.data.node || undefined
    dispatch({ type: FINISHED_REQUEST, checkout });
  }, []);

  /**
   * Public Functions
   */
  const addToCheckout = async (args: AddToCheckoutArgs) => {
    const checkout = getOrCreateCheckout();
    const checkoutExists = Boolean(checkout);
    const mutate = checkoutExists ? addMutation : createMutation;
    const variables = checkoutExists ? { checkoutId, ...args } : args;

    dispatch({ type: STARTED_REQUEST });
    const result = await mutate(variables);
    console.log(result);
    const resultKey = checkoutExists
      ? 'checkoutLineItemsAdd'
      : 'checkoutCreate';
    dispatch({ type: FINISHED_REQUEST, ...result.data[resultKey] });
  };

  return {
     ...state,
     addToCheckout,
     /* other functions */
  }
```

I'd be happy to put a PR together if this is something that you think is worthwhile - just let me know how you'd like it to look or if you foresee any issues.

**Comment by parkerziegler** [comment]
@good-idea @CaitlinWeb this is seeming more and more like something that folks want in the core `urql` API. I'm going to explore things on the `wonka` side to see if I can figure out why @kitten's original solution with `toPromise` isn't behaving as expected. In the meantime, @good-idea I'd be fine with you opening a PR w/ your proposal for the API, and we can shape it once we have something to look at. The basic API suggestion of:

```
client.createQuery({ query, variables });
client.createMutation(mutation)
```

seems like a good starting point. cc/ @kitten @andyrichardson thoughts on this?

**Comment by good-idea** [comment]
@CaitlinWeb would the above PR do what you needed?

**Comment by kitten** [comment]
I'll investigate some options to make this nicer. I really think this looks rather compelling and gives us another layer of customisation that's also useful for adapting the library to other frameworks / UI libraries.

I'll see how we can make this happen without making the client's API surface larger. For now it has a couple of methods it might not even need.

@parkerziegler I think it's mostly misbehaving because it's a lazy promise, if I remember how I implemented it. That means that it won't do anything or subscribe to the underlying observable until then is called. I'd have to see why that isn't quire working. Might be because it's not caching the result?

**Comment by parkerziegler** [comment]
🤔 Yeah I'm not totally sure. I did notice that using `toPromise` with one of the `source` operators like `fromValue` does work properly. What seems to happen with `client.executeQuery` is that we never actually call `resolve` (`.then` never executes). I was starting to wonder whether it's be related to the `share` operator, but don't have quite enough knowledge of it to be sure.

**Comment by CaitlinWeb** [comment]
> @CaitlinWeb would the above PR do what you needed?

@good-idea Looks right for my use case, but I think calling the methods `requestQuery` and `requestMutation`, or something similar, would be more appropriate. The request is sent when calling those methods (inside the Promise). 

An alternative would be to add a layer such as `.send()` or `.request()` before the Promise, so if you do `const myQuery = client.createQuery(query, variables)` then to actually send it you'd then do `myQuery.send()`. Hope that makes sense.

**Comment by CaitlinWeb** [comment]
@kitten @parkerziegler Thanks for taking another look at this. There are instances where api calls aren't directly tied to the view. Also, urql is a friendly implementation of GraphQL and it would be cool to see it work for other libraries beyond React.

I'm not currently working on a GraphQL project anymore, but if you'd like me to test the next version that incorporates these utility functions then I will see what I can do.

**Comment by andyrichardson** [comment]
> There are instances where api calls aren't directly tied to the view

For these use cases you can execute a query directly on the client using the exposed via context.

```
import { Context } from "urql";

// ..
const client = useContext(Context);
pipe(
  client.executeQuery(...),
  // ...
```

**Comment by good-idea** [comment]
@andyrichardson This is definitely an option, but it requires a bunch of knowledge about the internals of Urql for something that would be better provided with a really simple API

 - You need to import `pipe` and `subscribe` from wonka, and subscribe to it
 - You need to use `createRequest` from `utils/request` to provide the proper argument to `client.executeQuery`

My PR #241 simplifies all of this by adding `client.createQuery` and `.createMutation`. They return query/mutation functions that are then ready to be called. Adding something like `client.runQuery` would be trivial. (But the difference between `runQuery` and `executeQuery` would be confusing, I'll leave it to someone else to name these things..)

**Comment by andyrichardson** [comment]
@good-idea I wouldn't consider the use of streams to be the internals of urql. For those new to streams, there is a learning curve, but this is not uncommon for libraries of this nature.

I think one of the blockers here is the lack of documentation for Wonka (I imagine if we were continuing to use RxJS the use of streams would be less of a problem?) but @kitten is working on that.

I think you're right that needing to prepare the query in order to execute it is unnecessary and I think that's definitely something we could look into (I'll check out your PR 👍)

If we were able to return a stream but give users yourself the flexibility to not have to import Wonka (for basic functionality) would that have some appeal?

@kitten - am I right in thinking we could add utility functions to our stream such as `{ ...observable, toPromise: () => pipe(observable, toPromise) }`. If so, that might give us the best compromise 🙌

**Comment by good-idea** [comment]
Streams aren't that big of a learning curve, but all I'm after is a basic way to run queries and mutations. Something like:

```js
const queryResult = await query(MY_QUERY, variables)
const mutationResult = await mutate(MY_MUTATION, variables)
```

**Comment by kitten** [comment]
I'm starting to wonder whether it'd actually be enough to do:

```js
await client.query(QUERY, vars);
await client.mutation(MUTATION, vars);
```

Since lazy evaluation can basically just be ignored, since this would be sufficient:

```js
const query = () => client.query(QUERY, vars);
const mutation = () => client.mutation(MUTATION, vars);

// ...

await query()
await mutation()
```

And we could either add options as another argument:

```js
await client.query(QUERY, vars, { requestPolicy: 'network-only' });
```

Or just make it more similar to the hooks API:

```js
await client.query({
  query: QUERY,
  variables: vars,
  requestPolicy: 'network-only'
});
```

**Comment by ctrlplusb** [comment]
Also super keen on this feature. As a side note it would be awesome to be able to use graphql-code-generator to leverage type-safe queries via the imperative APIs.

P.S. _Fantastic_ work on this client implementation. It's a dream ❤️
