### ISSUE TITLE
(react) - cache-and-network requestPolicy causes fetching flicker when no data is returned

### ISSUE THREAD

**Issue by alextuppen** [FormidableLabs/urql#2203]
urql version & exchanges: 2.0.6 - client is created without specifying any exchanges

**Steps to reproduce**

1. Create a React useQuery hook, pause it waiting for a variable to come down from the parent component and set the requestPolicy to cache-and-network
2. Set the variable from the parent component as a query variable and execute the query in a situation where the server will not return anything (it works correctly when data is returned)

**Expected behavior**
The fetching boolean remains true until the query has completed.

**Actual behavior**
The fetching boolean starts true, flips to false, then flips back to true and finally settles on false. 

I looked at creating a reproduction but I don't have access to a public server with a query that returns nothing, sorry.

**Comment by kitten** [comment]
Sorry, I don't really understand the description; specifically, I'm a little puzzled by these statements 😅 
> in a situation where the server will not return anything
> flips to false, then flips back to true and finally settles on false

I'm half assuming that this may be a slight misunderstanding of the API here, because `cache-and-network` may deliver _stale_ data, which is indicated by `result.stale`, while `fetching` is an internal state flag only maintained by the hook itself.

But we may either need a more thorough description here or a reproduction. We have several example folders and example APIs (via trygql.formidable.dev) that can help you get to a reproduction by the way. Any of these can be bootstrapped into a CodeSandbox: https://github.com/FormidableLabs/urql/tree/main/examples

That said though, I'm struggling to understand either the code that's been written, the scenario & conditions that are in place (since "execute" is a bit ambiguous in the presence of `pause`), or what the expected behaviour is and whether that simply doesn't match up with the expected behaviour of the API design or is indeed an inconsistency.

**Comment by alextuppen** [comment]
Sorry, I'll throw a reproduction together, have you got the links to the actual end points from that page? I'm struggling to dig them out. 

Thank you for replying so fast!

**Comment by kitten** [comment]
Of course, no worries! The endpoints are all at: https://trygql.formidable.dev/
Our examples basically use these ones so we don't need to add server sandboxes on CSB

**Comment by alextuppen** [comment]
I think that this was some weird behaviour in one specific place that I could never replicate elsewhere so I'm closing it.

**Comment by hawkeyes21** [comment]
@alextuppen I encountered this exact scenario. Changing the network-policy does fix the issue, but were you able to find an alternate solution?

**Comment by alextuppen** [comment]
@hawkeyes21 Unfortunately not, I got busy and it ended pushed to the back of the priority pile and then the company laid me off so I don't have access to the code with the issue anymore sorry
