### ISSUE TITLE
(react) - Fetching initial value is false on first mount

### ISSUE THREAD

**Issue by Josyto** [FormidableLabs/urql#2226]
After upgrading to version 2.1.1 from version 2.0.6 I had problems with the initial value of the "fetching" variable.
After calling the query I get that the data and error values ​​are undefined and the fetching is false.
After that fetching changes to true.
The options are only variables, no pause enabled.

In version 2.0.6 the initial value of fetching after the call to useQuery was true.

2.0.6 version, first value was true, after get data get false.
![image](https://user-images.githubusercontent.com/18529351/151787526-f3c18703-d790-4456-bed1-09cb368a9b38.png)

2.1.1 version, first value was false, after get true and finally get data and get false.
![image](https://user-images.githubusercontent.com/18529351/151787159-c6342d50-f939-461d-b85d-fba4d5e70047.png)

"urql" >= "2.1.0",
"@urql/devtools": "2.0.3",
"@urql/exchange-auth": "0.1.7",
"@urql/exchange-graphcache": "4.3.6",
"@urql/exchange-multipart-fetch": "0.1.14",

**Steps to reproduce**

useQuery with default options and network-only mode.

**Expected behavior**
Initial value of fetching should be true.
Demo: https://codesandbox.io/s/urql-fetching-2-0-6-jcdjb

**Actual behavior**
Initial value of fetching is false.
Demo: https://codesandbox.io/s/urql-fetching-2-1-1-oe9e6

**Comment by kitten** [comment]
The problem here is that the `requestPolicy` is set to `"network-only"`. What this basically causes most of the time is that there are situations where an initial state before an effect update is not quite accurate. That's expected and it simply signifies how dangerous it can be to use `urql` in a UI framework without a cache. That's actually quite similar to React's Suspense requirements in general. If you need consistent state, then you'll need to read state at least once.
That's actually why we don't recommend altering the default `requestPolicy` for UI frameworks and are considering making this less transparent.

What I believe isn't expected here is that the _initial_ `fetching` value is `false` which is really the only issue here that's immediately apparent to me. I reckon the problem may be that we never get rid of the initial default state here: https://github.com/FormidableLabs/urql/blob/481bf43a8199e4e61c750655c09da431f75077b1/packages/react-urql/src/hooks/useQuery.ts#L63

I'd imagine that this may be expected, but for some reason what should happen is that the following section isn't updating this to `fetching: true` right away: https://github.com/FormidableLabs/urql/blob/481bf43a8199e4e61c750655c09da431f75077b1/packages/react-urql/src/hooks/useQuery.ts#L161-L168

**Comment by kitten** [comment]
This should be less confusing now in [`urql@2.1.2`](https://github.com/FormidableLabs/urql/releases/tag/urql%402.1.2)

**Comment by Josyto** [comment]
The main problem was that my rendering depended on fetching, stale (when there is cache), error and data.
I considered the state `false, false, undefined, undefined` as not possible, so I had problems that could have been solved by aborting the first render.
I failed to define this problem in the issue but just tested the new version [`urql@2.1.2`](https://github.com/FormidableLabs/urql/releases/tag/urql%402.1.2) and it works fine.

Many thanks for your speed @kitten @JoviDeCroock.

**Comment by frederikhors** [comment]
@Josyto They are a super team.

**Comment by Josyto** [comment]
> @Josyto They are a super team.

Without a doubt, they are a formidable team 😄
