### ISSUE TITLE
Testing useQuery components

### ISSUE THREAD

**Issue by AaronLaBrie** [FormidableLabs/urql#224]
Hi! Thanks for putting this library out, I've really enjoyed using it so far.

I'm wondering if y'all have any suggestions about how to approach testing components that use the `useQuery` hook.

I dug through the docs and issues but didn't see anything that quite lined up, my apologies if I just missed something.

**Comment by good-idea** [comment]
Hey @AaronLaBrie , not sure if you've solved this on your end, but what I have been doing is splitting my components into, essentially, a "loader" component and a "view":

```js

export const ProductDetailView = ({ fetching, data }) => {
  if (fetching) return <p>Loading..</p>
  // etc..
}

export const ProductDetail = ({ productId }) => {
   const [response] = useQuery(PRODUCT_QUERY, { variables: { productId }})
   return <ProductDetailView {...response} />
}
```

This way I can just test `<ProductDetailView />` by manually passing in `fetching` and `data`, since it no longer cares wether these props are being supplied by urql or not.

This has also been helpful in other ways - for instance, I have a number of custom hooks that require a `product`. Before, when I was using `useQuery` in the same component of these hooks, it was getting complicated because the hooks all need to be called, so I couldn't `return <p>Loading..</p>` early, and not call the latter hooks. Or, I would need to re-write these custom hooks to deal with what would happen if `product` is undefined - which isn't really what they were meant to do.

**Comment by andyrichardson** [comment]
@good-idea breaking down the components like that sounds like a strong approach.

The other option is to mock fetch. The advantage to this is that you can mock all response states while also testing the outgoing API calls and any exchanges you may have added (or may add in the future).

**Comment by AaronLaBrie** [comment]
Whoops, sorry I missed this! 

Thanks for the good suggestions, those are both reasonable options.

**Comment by swillis12** [comment]
@good-idea, If you want to write an integration test for an ancestor component, you will still need to mock the graphql call.

@AaronLaBrie, @good-idea, what about this approach? https://graphql.org/blog/mocking-with-graphql/

This seems like it could potentially be more maintainable than mocking fetch... let me know what you think.
