### ISSUE TITLE
RFC: Client-side failover / redundant endpoints

### ISSUE THREAD

**Issue by orangecms** [FormidableLabs/urql#2254]
**Note**: I am willing and getting paid to fully work on this myself. We see a potential benefit for the community, so we would prefer to share the idea and upstream our efforts. :-)

## Summary

As of now, the client accepts exactly one URL:
```js
const client = createClient({
  url: 'http://localhost:3000/graphql',
});
```

For availability and failover, most providers would put redundancy behind DNS, i.e., let the record resolve to multiple IP addresses, have load balancers in place, etc..

However, my employer poses the requirement to do client-side failover, so that it would be simpler for the infrastructure side.
A simple solution would be to allow passing an array of endpoints and iterating over them in case of network errors.

## Proposed Solution

When creating the client, allow for passing either a single url, or an array. To simplify compatibility, call it `endpoints` or possibly `urls`, retaining the original `url` for backwards compatibility or general single-url use.

Note that this is not well suited for persistent connections, as in pub-sub. Consider erroring on subscription attempts when using multiple URLs. That might be possible to accomplish through typing or otherwise static analysis, otherwise needs handling at run time.

The default strategy should be to simply try the first URL in the array, and then try another in case of network error, exposing the final network error in case all URLs fail. Possibly allow for passing a custom strategy, such as picking a random URL or round-robin for load balancing.

## Requirements

Allow for passing a custom strategy to handle errors, given that both network and logic errors may occur. This means also that the GraphQL errors need to be distinguished; one needs to decide whether some error stems from a client (e.g., typo in a query) or from actual back-end failure. Given a distributed system, note that multiple servers may be running different versions of the API and/or the logic behind them.

**Comment by JoviDeCroock** [comment]
You mean a bit like the [retry-exchange](https://formidable.com/open-source/urql/docs/advanced/retry-operations/), this exchange has a property that we haven't documented yet which is named `retryWith` this would allow you to alter the `context.url` and access a different endpoint https://github.com/FormidableLabs/urql/blob/main/exchanges/retry/src/retryExchange.ts#L29-L32

**Comment by kitten** [comment]
I think this use-case is indeed covered by the `retryExchange`. Sorry!
We're also often inclined to reject proposals that aren't only covered by other implementations already (or only require minor modifications and lines of code), but that also are very HTTP-centric, as we can see HTTP-concerns creeping into an increasing amount of our API if we don't have any checks and balances.

For reference, when someone finds this via the search. The `retryExchange` allows us to alter the operation with the `retryWith` option dynamically, which could be used for fallback URLs. Subsequently, the default `url` could also be changed by mapping operations in a prior exchange. https://formidable.com/open-source/urql/docs/advanced/retry-operations/

On a side note, this doesn't follow the full RFC template. For reference, we require a couple of things so people can read a proposal and get the full idea of what the idea is — this for instance in multiple sections doesn't state a proposed solution clearly 😅 ❤️ So just for the benefit of explaining the RFC process and for future readers, I'll point this out here — no offense intended! We appreciate RFCs a lot! ❤️ 

> However, my employer poses the requirement to do client-side failover, so that it would be simpler for the infrastructure side.

This doesn't state a problem. Here you assume that we and you want the solution. That means you're justifying a solution after you've come up with it. Instead, a proposal should assume no solution, you'll then state the problem, and it should be made clear why the proposed solution (or one of them) is the obvious choice.

> When creating the client, allow for passing either a single url, or an array. To simplify compatibility, call it endpoints or possibly urls, retaining the original url for backwards compatibility or general single-url use.

There's a lot of context in `urql` already, for instance, while there is a `url` option, we also have the `retryExchange`. You are explaining "How will this change be implemented, and how does it work?" (from the template) but you are not taking into account what already exists. Even if the `retryExchange` didn't exist, you'd then have to say _why_ this option is the clear one. In general, we'd go (and have gone) for exchanges, so here you'd say why it'd be an option instead, and what conflicts that may create.

> The default strategy should be to simply try the first URL in the array, and then try another in case of network error

This is a little imprecise. You're saying "default strategy" here with no code samples or user-facing API implemented. Since this is a user-facing example, when you say default strategy, make sure to say what makes it the default and how users would alter the defaults, if you intend for them to do so

> Allow for passing a custom strategy to handle errors, given that both network and logic errors may occur.

This conflicts a bit with the term "network error", which we don't define anywhere but in `CombinedError.networkError`. So, given that that exists, this stands in conflict with saying "network error" before

----

Anyway, I hope you find this useful, and please don't take this the wrong way — we do appreciate RFCs a lot and if we wouldn't have the `retryExchange` already, I would've loved working with you on getting the RFC into a state where it can be picked up.

If you have some questions about this problem, since you do mention it's a problem you're facing, feel free to open a [discussions thread](https://github.com/FormidableLabs/urql/discussions/new) and we can help you with the `retryExchange` :v:

**Comment by kitten** [comment]
@orangecms That'd be awesome! Cheers ❤️ Let me know if you need any guidance on that
