### ISSUE TITLE
`minifyIntrospectionQuery` removes too many types

### ISSUE THREAD

**Issue by damiangreen** [FormidableLabs/urql#2335]
"@urql/introspection": "^0.3.2",

**Steps to reproduce**

```
import { readFile, writeFile } from 'fs/promises'
import {
  getIntrospectedSchema,
  minifyIntrospectionQuery,
} from '@urql/introspection'

const file = 'src/generated/schema.json'

async function compact() {
  const data = await readFile(file, 'utf8')
  const minified = minifyIntrospectionQuery(getIntrospectedSchema(data))
  writeFile(`${file}-modded.json`, JSON.stringify(minified))
}

export default compact

```

Using the code above to compact a schema compresses it well , but it removes too many types resulting in runtime errors  such as 
```
[GraphQL error]: Message: Variable "$filter" expected value of type "ComstoreComponentFilterInput" which cannot be used as an input type., Location: undefined, Path: undefined
```

Example input schema at https://demo.firepad.io/#q94nJ08QFl
ourput at https://demo.firepad.io/#e3uYCH7SYO
**Expected behavior**
doesnt remove types
**Actual behavior**
Removes types.

I should add that i'm attempting to use this package as a standalone to compress my schema, which im then loading into Apollo.

**Comment by frederikhors** [comment]
I'm using it and it works good. I don't understand what you mean.

**Comment by kitten** [comment]
I'm not quite sure what you're using the output for since you're getting a server-side error from a GraphQL API, since this is mostly intended for use with Graphcache, but to include more data in your output you have to enable the following options: https://github.com/FormidableLabs/urql/blob/8e92357c5d1a7db2e28827377bda4e781dcd8e3b/packages/introspection/src/minifyIntrospectionQuery.ts#L159-L168

```ts
export interface MinifySchemaOptions {
  /** Includes scalar names (instead of an `Any` replacement) in the output when enabled. */
  includeScalars?: boolean;
  /** Includes enums (instead of an `Any` replacement) in the output when enabled. */
  includeEnums?: boolean;
  /** Includes all input objects (instead of an `Any` replacement) in the output when enabled. */
  includeInputs?: boolean;
  /** Includes all directives in the output when enabled. */
  includeDirectives?: boolean;
}
```

By default, this utility will remove scalars, enums, inputs, and directives from the output, since those aren't needed for our normalised cache, Graphcache, to function.
