### ISSUE TITLE
RFC: Customizable dedupe logic

### ISSUE THREAD

**Issue by CreativeTechGuy** [FormidableLabs/urql#2398]
## Summary

We have use-cases where multiple queries which obtain similar data are requested at the same time. They aren't identical queries so aren't deduped, but some of the queries are subsets of other queries. We would like a way to indicate that query A should wait for query B in our application since we know that once A returns, we'll have all of the data needed for B.

## Proposed Solution

* An API on the core client which returns the list of in-flight queries. This wouldn't add any configuration but would enable us to write custom logic to `pause` new queries based on the queries that we see are already in-flight. This should be relatively straight-forward to expose since this information is all already available and used by dedupExchange internally.
* [Unlikely] Additional configuration to the dedupExchange to enable hooking into the conditions used to dedupe so custom logic can be used.

Possibly a tangent. But the ability to defer requests for a short time since query B may occur before A. If B is made without A, then we want to send just B, but if B is made and then immediately after A is made, we then want to dedupe B and only send A despite it coming second (B is requesting a subset of the data that A is requesting).

## Requirements

* N/A

**Comment by kitten** [comment]
Sorry, this isn't really an RFC 😅 There's no proposed solution but only a problem. However, I'm also having trouble understanding this problem. This seems like a structure or tooling problem on your end potentially.

Structural duplication is an issue that's related to fragment composition. Composition is basically the tool that GraphQL gives us to deal with the problem of combining data requirements, which is most embraced in Relay's tooling.

Say, you have multiple components on a single page. If each component, which consumes data from GraphQL exposes fragments for the data it requires and these fragments are composed upwards, given a GraphQL schema that is buil to accommodate your UI perfectly, then you can always represent any page with a single GraphQL query.

The other thing you're mentioning here are dependent queries, so not deduplication or composition. As you're saying, that's typically a UI or schema issue. You'd typically coordinate dependent queries in your UI code, e.g. with `useQuery`'s `pause` option.
There's no mechanism in GraphQL that can "solve" dependent queries as we'd then map variables from one GraphQL operation to another, which is basically the UI's responsibility.

However, this problem shouldn't occur when there's no user interactions in your UI. When the user doesn't make any changes then a query should be able to retrieve the data for the entire page, _if_ the schema is built to accommodate the UI 🤔

I'm happy to convert this over to a discussion, but as an RFC, I'm not sure this would go anywhere since it sounds more like a question ✌️
