### ISSUE TITLE
Auth Exchange's didAuthError hook returns a locked ReadableStream for Response.Body

### ISSUE THREAD

**Issue by jameshopkins** [FormidableLabs/urql#2407]
I'm trying to inspect the response body from within `didAuthError`. I can see that `error.response` is a `Response` but I'm unable to use any serialize methods on it (`.json()`, `.text()`, etc).

```js
const client = createClient({
      url: "http://localhost:4000/graphql",
      exchanges: [
        authExchange({
          ...
          didAuthError: ({ error }) => {
            const body = await error.response.json();
          }
          ...
        }),
        cacheExchange,
        fetchExchange,
      ],
    });
```

urql version & exchanges:

`"urql": "^2.1.3"`, `"@urql/exchange-auth": "^0.1.7",`

**Expected behavior**

Given the example above, I'd expect to have access to a JSON-serialized representation of the response body.

**Actual behavior**

I get the error `TypeError: Failed to execute 'json' on 'Response': body stream already read`

**Comment by kitten** [comment]
This is intentional and expected behaviour for two reasons 😅 
- We don't make an assumption that the response is delivered via HTTP and instead only standardise on the GraphQL serialisation format, hence the `CombinedError#response` property is mostly for debugging
- When an error occurs we expect that the GraphQL serialised response is all that's needed (plus at most `response.status` in exceptional circumstances when there's no other way) hence `error.graphQLErrors` or `error.networkError` are the only accessible methods to inspect the error

So, since the response's body has already been consumed we make no effort to clone it and repeat the body or make the JSON blob available otherwise :v:

**Comment by jameshopkins** [comment]
That makes sense, cheers @kitten  for explaining
