### ISSUE TITLE
useQuery not being re-rendered after manual cache update

### ISSUE THREAD

**Issue by sergiogc9** [FormidableLabs/urql#2554]
Thanks for this awesome GraphQL client! In my current company we've been working on migrating our app to GraphQL and we chose this client 😄.

I'm opening this issue because we're facing what we think it's a bug but wanted to be sure we're not doing anything wrong first. I think explaining it could be tricky so I created a sandbox where the bug can be reproduced:

[https://codesandbox.io/s/urql-bug-fb1edy](https://codesandbox.io/s/urql-bug-fb1edy)

In a nutshell, we have a sidebar with an items counter and a container with the items shown as "cards". Then, when the remove button is clicked, the item card is removed but the counter is not decreased to 0. To do this, we perform manual updates to the cache using the `@urql/exchange-graphcache` exchange. 

I did some research to figure out what's happening and this is what I found:
- The bug only happens using react v17 (using v18 seems to work).
- The bug is related to the `currentInit` global variable used by the `useQuery` hook [here](https://github.com/FormidableLabs/urql/blob/c70b1737f192bc2c53d4e1687025f39e5179c967/packages/react-urql/src/hooks/useQuery.ts#L47). 
- It's caused because when we remove the **last item** in the cache, then the `EmptyContent` component is mounted, which performs a graphql query (in our case something related to user permissions), so the `currentInit` variable is set to `true` [here](https://github.com/FormidableLabs/urql/blob/c70b1737f192bc2c53d4e1687025f39e5179c967/packages/react-urql/src/hooks/useQuery.ts#L131). Then, the sidebar component doesn't get re-rendered because [this if condition](https://github.com/FormidableLabs/urql/blob/c70b1737f192bc2c53d4e1687025f39e5179c967/packages/react-urql/src/hooks/useQuery.ts#L163) is false. 
- We found a workaround which is using an optimistic resolver for that mutation (you can see it commented in the sandbox), but this would be a temporal fix as we are not considering optimistic queries at this moment.

Probably the schema and the manual update could be improved, but it is how we have it now (I tried to simulate the most our environment). 

If you think this is a bug, I can try solving it, but a starting point would be nice (e.g. more context about the `currentInit` global variable). Otherwise, if you think this is an expected behaviour or you think we're doing something wrong, we're happy to know it.

**urql version & exchanges:**

```
"@urql/core": "2.6.0",
"@urql/exchange-graphcache": "4.4.3",
"urql": "2.2.2",
```

**Steps to reproduce**

Open the sandbox and click the remove button on the item card.

**Expected behavior**

The item card is removed and the items counter is decreased to 0.

**Actual behavior**

The item card is removed but the counter remains at 1.

---

Thanks!

**Comment by JoviDeCroock** [comment]
Hey!

The `currentInit` check is in place to fix a React issue: `cannot update component x while component y is rendering`, basically cross-component updates because a state is being initialized.

Question, in your real life scenario are you using a service-worker/msw as well, it looks like adding an aritficial delay to the responses `ctx.delay(1)` makes everything work. The response and React's render cycle might be equalized as they are both using a microtick (and the response from a service-worker is as well)

**Comment by sergiogc9** [comment]
Thanks for your response! 

No, obviously in our real life scenario we are using a real GraphQL server. We only use msw for testing, but here I used it to make the sandbox easier. 

I tried adding the delay in all responses (in `handlers.ts` file) as your suggested in the sandbox with no luck, where did you add the delay exactly? But anyway, in the real scenario we are performing real calls and the bug happens.

**Comment by JoviDeCroock** [comment]
> No, obviously in our real life scenario we are using a real GraphQL server.

Heh, hence I asked a service-worker or msw 😅 was trying to get to the bottom of it.

So yeah basically the lifecycle of React seems to synchronize between the mount of `EmptyContent` and the `updateResult` happening for the `SideBar`. This is pretty peculiar but a real-world scenario nonetheless, thinking what the best way to tackle this is, removing `currentInit` will fix it but you will see a big `console.error` from React on every update or when you mount similar queries/....

**Comment by kitten** [comment]
Verified and fixed with the new patches: https://codesandbox.io/s/urql-bug-forked-mchckz

- [`urql@2.2.3`](https://github.com/FormidableLabs/urql/releases/tag/urql%402.2.3)
- [`@urql/core@2.6.1`](https://github.com/FormidableLabs/urql/releases/tag/%40urql%2Fcore%402.6.1)

This was _really_ hard to pin down and I left an explanation in the PR, but it's a little confusing. We basically made an incorrect assumption about React's scheduling. We've been aware of an issue with `currentInit` for a while but couldn't quite pin down when this would become an issue. But this really helped us. Cheers! ❤️

**Comment by sergiogc9** [comment]
Awesome work! Thanks for solving this so fast! 💯
