### ISSUE TITLE
RFC: Fix for useQuery variables being optional

### ISSUE THREAD

**Issue by robertherber** [FormidableLabs/urql#2606]
In my codebase this feels like a bug - but I'm posting it as an RFC since I might be missing some perspective on this. An example of what I expect to give a type error:
```GraphQL
query GetPage($pageNumber: Int!) {
  page(pageNumber: $pageNumber){
    title
    body
  }
}
```

Which doesn't give a type error for this:
```TypeScript
const [{ data }] = useGetPage() // <-- obviously missing variables with pageNumber
```

When using useQuery the variables parameter is always optional - even if variables are required by the query type. The issue is with the `UseQueryArgs` interface, which currently looks like this:
```TypeScript
export interface UseQueryArgs<Variables = object, Data = any> {
    query: string | DocumentNode | TypedDocumentNode<Data, Variables>;
    variables?: Variables; // <--- here is the issue
    requestPolicy?: RequestPolicy;
    context?: Partial<OperationContext>;
    pause?: boolean;
}
```

I did some experimenting and I think something like this could be better (works as expected when using useQuery, although it does cause some type compatibility issues with [@graphql-codegen/typescript-urql](https://npmjs.com/package/@graphql-codegen/typescript-urql)):

```TypeScript
export interface UseQueryArgsWithVariables<Variables = object, Data = any> {
    query: string | DocumentNode | TypedDocumentNode<Data, Variables>;
    variables: Variables;
    requestPolicy?: RequestPolicy;
    context?: Partial<OperationContext>;
    pause?: boolean;
}

export interface UseQueryArgsWithoutVariables<Data = any> {
    query: string | DocumentNode | TypedDocumentNode<Data, Variables>;
    requestPolicy?: RequestPolicy;
    context?: Partial<OperationContext>;
    pause?: boolean;
}

export type UseQueryArgs<Variables = object, Data = any> = keyof Variables extends never ? UseQueryArgsWithoutVariables<Data> : UseQueryArgsWithVariables<Variables, Data>
```

I tried with a similar approach for useMutation which has the same issue but wasn't able to get it 100%.

**Comment by JoviDeCroock** [comment]
I personally advise people towards using code-generation because even if it's not optional you don't know what to add, using typed-document node is what I've used for this https://github.com/dotansimha/graphql-typed-document-node

**Comment by kitten** [comment]
Hm, is the problem here rather that we typo'd it when moving over to the generics and `?:` forces it to now be optional? I'm not sure if we can solve it in a backwards compatible way, but we could take a look at that. Not sure if TypeScript has a good solution for this. Maybe a type extension ternary could work

**Comment by nandorojo** [comment]
I believe this is fixed in the latest codegen version.

https://github.com/dotansimha/graphql-code-generator/pull/7195

https://github.com/dotansimha/graphql-code-generator/pull/7977

However, I believe there would indeed be a simple way using TypeScript to require / reject using `variables` based on the `Variables generic itself`. I could probably look into it and submit a PR.

**Comment by robertherber** [comment]
@nandorojo Yeah, it seems to require the options object to be passed for useQuery that has required variables with the latest version. It would be awesome if it would also require the variable property in those cases. And similarly for the mutation variables :)

I've realised my example above doesn't quite work as advertised - since it's checking whether it extends never it will always be the case..

**Comment by kitten** [comment]
The behaviour we want here is actually not super trivial. What we want is that if no generics are passed `variables` is optional, when a generic for empty/nullish variables are passed, we still want the property to be optional. However, when we infer or have a passed generic of non-empty variables, we want the property to be required.

This means that we want to write something like this:

```
type MaybeRef<T> = T | Ref<T>;
type EmptyVariables = undefined | null | { [prop: string | number]: never; };
type AnyVariables = Record<string, any>;

export interface BaseUseQueryArgs<T = any, V = AnyVariables> {
  query: MaybeRef<TypedDocumentNode<T, V> | DocumentNode | string>;
  requestPolicy?: MaybeRef<RequestPolicy>;
  context?: MaybeRef<Partial<OperationContext>>;
  pause?: MaybeRef<boolean>;
}

export type UseQueryArgs<T = any, V = AnyVariables> = BaseUseQueryArgs<T, V> & (V extends EmptyVariables ? { variables?: MaybeRef<V> } : { variables: V });
```

(I took this from the `vue-urql` code, since the test there is easy to use to test for whether this is working)

Unfortunately, however, it's really hard to make a check in TypeScript that checks for non-empty types that aren't `object` or `Record<string, any>` i.e. the arbitrary input. Since, any arbitrary type for variables will likely always extend such a type.

**Comment by nandorojo** [comment]
I believe the options object becomes required from one of those PRs when variables are required. Does it not?

In any case, this is a simple TS fix by using conditional arguments based on the generic.

**Comment by nandorojo** [comment]
@kitten I see, so the tough case to solve here is if we are just getting a basic `object` type or `Record<string, string>`.

**Comment by kitten** [comment]
hm, on second thought, this may work 🤔 Basically adding a standin type (`EmptyVariables`) that then gets converted to `AnyVariables` as input.

```typescript
type MaybeRef<T> = T | Ref<T>;
type EmptyVariables = { [prop: string | number]: never; };
type AnyVariables = Record<string, any>;

export interface BaseUseQueryArgs<T = any, V = EmptyVariables> {
  query: MaybeRef<TypedDocumentNode<T, V> | DocumentNode | string>;
  requestPolicy?: MaybeRef<RequestPolicy>;
  context?: MaybeRef<Partial<OperationContext>>;
  pause?: MaybeRef<boolean>;
}

export type UseQueryArgs<T = any, V = EmptyVariables> = BaseUseQueryArgs<T, V>
  & (V extends EmptyVariables ? { variables?: MaybeRef<AnyVariables> } : { variables: MaybeRef<V> });
```

**Comment by nandorojo** [comment]
Creative thinking there. Looks like it should work.

The same thing could be done for `executeMutation`, where a conditional is used to determine the arguments array.

**Comment by kitten** [comment]
I implemented a PR that we can ship along with our other upcoming breaking changes. The trouble here is that some behaviour may not be backwards-compatible for people that use TypeScript with typings (or `TypedDocumentNode`) generation.
I'd also like to be careful here, since it's a tad hard to test whether we've regressed on utilities.

**Comment by robertherber** [comment]
Huge thanks for this @kitten. The new types fix a handful of would-be bugs in a matter of minutes.. :)
