### ISSUE TITLE
RFC: possibility to log obtained data

### ISSUE THREAD

**Issue by bogdankol** [FormidableLabs/urql#2654]
Hi! I figured out that there is one main difference between @urql/react and @urql/svelte. Its about logging requested data - in react I can see in console what data came to me and when, but in svelte I cannot do that. It always shows {
  isPaused,
  pause, 
  resume,
  subscribe
} when using queryStore({}) and { 
  subscribe
} when using mutationStore({}). I can see received data only when its rendered or in network. 

## Summary

It would be good if logging of obtained data into console would be available

## Proposed Solution

Perhaps just rewriting react source code into svelte would do

**Comment by kitten** [comment]
Hiya 👋

Sorry, heads up, I'll proactively close this issue after answering, because the necessary features for this already exist. However, feel free to continue using this thread for any ongoing discussion or questions ✌️

We currently already have two main tools available for this:
- The `debugExchange`: Which can be imported from core and added in the list of exchanges (depending on where it's placed it can also see operations before deduplication) https://formidable.com/open-source/urql/docs/api/core/#debugexchange
- The urql devtools: Which are a browser extension and an exchange together, visualising any incoming or outgoing activity https://github.com/FormidableLabs/urql-devtools

These two basically expand on information your can gather on what `urql` gives you beyond the browser network devtools.
If you then need to get information about your bindings, we prefer to recommend manual logging tools (in your case, just subscribe to the store and then log), or your framework's browser devtools
