### ISSUE TITLE
How to use subscriptions with existent data?

### ISSUE THREAD

**Issue by BrunoQuaresma** [FormidableLabs/urql#272]
I have a component where is displaying a todo list so, I'm doing a query to get all todos like `getAllTodos` and also I'm creating a subscription called newTodo. My question is after receive an update from the newTodo subscription how can I update the data in `getAllTodos` state?

I didn't find anything on docs or in the subscription example.

**Comment by kitten** [comment]
One way would be to have your query and subscription in one component and to handle the merge in the `useSubscription`'s second argument, the `handleSubscription` function 😀

**Comment by BrunoQuaresma** [comment]
In this case:
```javascript
const [{ fetching, data }] = useQuery({ query: getAllTodos });

const [res] = useSubscription(
    { query: newTodoSubscription },
    (todos: any = data, response: any) => {
        console.log(todos)
    }
  );
```
The result of `console.log(todos)` always is undefined even when data is fetched.

**Comment by BrunoQuaresma** [comment]
I can do some workaround like this:
```javascript
const [allTodos, setAllTodos] = useState();
const [{ fetching, data }] = useQuery({ query: getAllTodos });

const [res] = useSubscription(
    { query: newTodoSubscription },
    (todos: any = data, response: any) => {
        return response.todo.node
    }
  );

useEffect(() => {
  if (data && res.data) {
    setAllCards(data.cards.concat(res.data));
    return;
  }

  if (data) {
    setAllCards(data.cards);
  }
}, [data, res.data]);
```

But I think it is not ideal.

**Comment by DominikGuzei** [comment]
Use redux oder mobx to manage your data 😉 GraphQL should not be your client side data store anyway, otherwise you will bind your whole frontend app to this stack. We are using GraphQL **only** for fetching / subscribing to data (which is what it was built for) which gets handed over to redux or mobx which trigger fine-grained re-renderings like in any other client side app (actually the components don't even know if you use REST or GraphQL (and they shouldn't).

**Comment by BrunoQuaresma** [comment]
Ok, I see. I thought it had some kind of store in background to manage the data like Apollo client does. Thank you for the explanation.
