### ISSUE TITLE
`handle.useQuery()` should only be called in the `setup()` or a lifecycle hook.

### ISSUE THREAD

**Issue by wucdbm** [FormidableLabs/urql#2779]
https://github.com/FormidableLabs/urql/blob/8fc678e8bf81c72d57f5cf27f03bf3b132dcf951/packages/vue-urql/src/useClientHandle.ts#L72

TL;DR Why does this code in that if statement even exist, what is its purpose

- We always have the reference to the client
- We do not need `setup` context because we have the client and `useClient` will not be called in `callUseQuery`
- This code only results in redundant console errors in a `NODE_ENV=development` staging build
- Isn't the WHOLE idea about the handle to be able to run queries in a callback, past the `setup` function context

**Comment by kitten** [comment]
It exists because it's not redundant and we've gotten too many issues like these unfortunately having to explain that Vue's Compositional APIs and component hooks only function inside the setup method.

> Isn't the WHOLE idea about the handle to be able to run queries in a callback, past the setup function context

Yes, but the main useClientHandle function has to be called in the setup method.

> This code only results in redundant console errors in a NODE_ENV=development staging build

The warning is limited to development builds because we don't need to enforce behaviour that's there by convention in a production build, since it'll lead to issues long before then

> We do not need setup context because we have the client and useClient will not be called in callUseQuery

The context is actually based on this: https://github.com/FormidableLabs/urql/blob/8fc678e8bf81c72d57f5cf27f03bf3b132dcf951/packages/vue-urql/src/useClient.ts#L26

There's also the additional reason of the setup lifecycle being needed because it's the canonical space to hook into certain effects phases and register unmount callbacks.

You can find out more about this here: https://github.com/FormidableLabs/urql/discussions/2422

Also, clearly I have to be a little strict on thiis. This is a question and neither adheres to our issue or RFC template, and a discussion thread would be more appropriate. But there are pre-existingn threads that do answer most of these questions already.
