### ISSUE TITLE
Add ability to override useQuery args on synchronous calls

### ISSUE THREAD

**Issue by andyrichardson** [FormidableLabs/urql#279]
It's currently not possible to manually trigger a query/mutation in the same render as updating a variable / query.

A more detailed example of this problem is [documented here](https://github.com/andyrichardson/tipple/issues/41)

**Comment by kitten** [comment]
This issue and the linked one is missing some of the context that the PR has. So a little confusing without the details.

That being said as far as React goes, the next query should not be executed automatically in the same render when the arguments change. That'd be an anti- pattern. Resct could've made effects synchronous but they're deliberately deferred and batchable 😀

**Comment by andyrichardson** [comment]
All context aside, the issue here is that certain events will influence state and also need to trigger an action.

> the next query should not be executed automatically in the same render when the arguments change

Totally agree with this sentiment when using `useQuery` without `skip`, but for times where we want to manually trigger an API call which also influences state, things become much trickier. Effects can be used to trigger API calls for the most part but I believe there will be edge cases - particularly on events that trigger the component itself to be unmounted such as an onClose handler for a modal.

This could be a none issue and I agree that this could encourage an antipattern, let's leave this for the time being until we find a real-world use case.

**Comment by kitten** [comment]
I think from what we've seen let's close this issue for now. I've seen some comments on issues that imply that people are using `pause` effectively to wrap up the hooks. And in other cases calling `execute*` will always cancel the automatically triggered update perfectly fine.

In even other cases this won't be necessary since every aspect can be controlled via exchanges, i.e. make an exchange that alters all operations before the rest of the pipeline or before `fetchExchange`, etc

In general there's also the third case of defining what we mean by "synchronous". From a hooks standpoint, especially with concurrent mode in the future, there'll be _nothing_ per se that runs synchronously. So deferring an API call, like our executions, isn't an issue, so we won't have to make this more synchronous in essence, since the expectation will be that everything in React will to some extent be deferred, like `useEffect` already is for instance.

We can open new issues maybe for this if we have specific limitations and code examples of what we'd like to enable :+1:
