### ISSUE TITLE
'fetch is not defined'

### ISSUE THREAD

**Issue by JoaoFGuiomar** [FormidableLabs/urql#283]
Hi 👋 

I was trying `urql` with `NextJS` and I'm getting `fetch is not defined` in the method `executeQuery` in file `urql.js`. 

Installed `isomorphic-unfetch` hoping it would solve the problem but it persists.
What am i missing? 🤔

**Comment by kitten** [comment]
We don't have any hard dependency on fetch to decrease our bundle size, since ultimately exchanges like the `fetchExchange` are optional.

But since `isomorphic-unfetch` is just a polyfill you can apply it before creating your urql client 👍

As described in their docs:

```js
import 'isomorphic-unfetch';
``` 

https://www.npmjs.com/package/isomorphic-unfetch

Hope this helps 👍

**Comment by JoaoFGuiomar** [comment]
Yep that works. Thanks 🙏
