### ISSUE TITLE
executeQuery toPromise never resolves but executeMutation does

### ISSUE THREAD

**Issue by Cooke** [FormidableLabs/urql#298]
pipe(client.executeQuery(....), toPromise) never resolves
pipe(client.executeMutation(...), toPromise) resolves as expected

**Comment by kitten** [comment]
`toPromise` converts a lazy stream to an eager promise. But since promises are defined for a single value and the completion of a stream, the `toPromise` operator waits for the **last event**.

So you'll also have to use the `take` operator to complete the stream immediately after the first value was emitted.

E.g.

```js
import { pipe, take, toPromise } from 'wonka';

pipe(
  client.executeQuery(/*...*/),
  take(1),
  toPromise
)
```
