### ISSUE TITLE
Subscription seem unstable

### ISSUE THREAD

**Issue by CodebyOmar** [FormidableLabs/urql#316]
The subscription client works sometimes and other times i get a connection failed error. This is my subscrptin client below:
<img width="705" alt="error" src="https://user-images.githubusercontent.com/24954601/59956193-b386df80-9486-11e9-9a17-dac76d40b9b9.PNG">

```
const subscriptionClient = (token) => {
  return new SubscriptionClient(
  `ws://${process.env.REACT_APP_SUB_API_URL}`, {
    reconnect: true,
    connectionParams: {
      headers: {
        Authorization: `Bearer ${token}`,
      }
    }
  });
}
```

**Comment by kitten** [comment]
Hiya, I know it isn't quite easy to do so, but do you have a reproduction? This might be an issue with the `SubscriptionClient` or backend rather than `urql` and it's hard to pinpoint exactly what is terminating the connection. The warning indicates that it might be the server closing it actually.

We do have an example in this repository that could be repurposed for a reproduction.

**Comment by CodebyOmar** [comment]
Sorry i wasn't able to create a reproduction but i found the issue. My server was rejecting the connection. I set up ngrok on my localhost to get a `https://` url, only then i was able to subscribe using `wss://`

**Comment by kitten** [comment]
Alright, glad you figured it out 👍
