### ISSUE TITLE
Bug in fetch HTTP status code handling

### ISSUE THREAD

**Issue by isker** [FormidableLabs/urql#341]
Hi!  This is purely static analysis, so forgive me if I'm misunderstanding:
https://github.com/FormidableLabs/urql/blob/25f4b96d6a510ade43eb4839ab595fc65e8a716a/src/exchanges/fetch.ts#L136-L142
Shouldn't L139 be checking `response.status >= statusRangeEnd`, not `>`?  It'd be strange if exactly 400 was valid but not 401.

**Comment by parkerziegler** [comment]
@isker that makes plenty of sense to me. I imagine this was just a small oversight at the time of writing the `fetchExchange`. If you'd like to make a PR for it I'd be happy to review, otherwise I can take care of it for the next release. We're still coordinating when / how to do the next release – we want to get a working version of the DevTools out as well. But this may come up in a patch release as well. Will ping here once I coordinate w/ @andyrichardson and @kitten on a release schedule.

**Comment by parkerziegler** [comment]
Released in v1.2.0.
