### ISSUE TITLE
Add subscription authorization context example

### ISSUE THREAD

**Issue by RodolfoSilva** [FormidableLabs/urql#416]
Has any example how can I use **urql** with JWT + Subscription? With option to reconnect, like apollo client do?
I've see the subscription example but I don't know what is the right way to pass the Authorization context.

**Comment by JoviDeCroock** [comment]
Hey,

Since we leave the option to the user to use the subscription client they prefer I’ll show an example of the one we use in our examples

‘’’
const wsClient = new SubscriptionClient(`ws://localhost:5000/`, {
    reconnect: true,
    connectionParams: {
        // Pass any arguments you want for initialization
        authToken: myToken
    }
});
‘’’

**Comment by kitten** [comment]
Closing this, since the answer above seems to be what you're looking for? Generally, we don't develop [`subscription-transport-ws`](https://github.com/apollographql/subscriptions-transport-ws), so we can't really point out the specifics on how to use it necessarily. But I hope this does answer your question, but let us know if it doesn't.

For questions unrelated to `urql` and its development, maybe our [Spectrum](https://spectrum.chat/urql) would be a better destination?
