### ISSUE TITLE
URQL doesn't deserialize dates

### ISSUE THREAD

**Issue by RobbieGM** [FormidableLabs/urql#473]
**Describe the bug**
URQL returns DateTime fields as strings, not native JS Date objects.

**Steps to reproduce**
1. Make a basic server (I used `apollo-server`) that returns a DateTime field for some query.
2. Run the query and see the response
3. It will be an ISO-formatted string, not a native JS Date object

**Expected behavior**
A date is returned for the queried field.

**Actual behavior**
A string is returned.

**Additional context**
It's possible that this is just a design limitation or not even a bug--just a feature I would really like to see. It would be especially useful with TypeScript clients that rely on the data type actually being what it thinks it is.

**Comment by JoviDeCroock** [comment]
I know this can be achieved with the [graphcache](https://github.com/FormidableLabs/urql-exchange-graphcache) by using a custom resolver to cast it to a date. I don't think this use case fits in the minimalist strategy of urql.

**Comment by RobbieGM** [comment]
Thanks for the prompt response! In the meantime, I think the best course of action to take to optimize DX would be to at least to inform TypeScript users (via static types) that their Dates have been converted to strings. I have solved this in my workspace by adding the type definition below and would be interested in creating a pull request to integrate that if you think it's a good idea.
```
type Json = string | number | null | Json[] | { [key: string]: Json };
type SerializedDates<T> = T extends Date
  ? string
  : T extends { [key: string]: any }
  ? { [K in keyof T]: SerializedDates<T[K]> }
  : T extends Json[]
  ? SerializedDates<T[number]>[]
  : T;

declare module 'urql' {
  export declare const useQuery: <T = any, V = object>(
    args: UseQueryArgs<V>
  ) => UseQueryResponse<SerializedDates<T>>;
}
```

**Comment by kitten** [comment]
That’s the thing though unfortunately. This is not strictly speaking a lack of deserialisation since nothing can be serialised without access to a schema (or other means of transformation) and your scalar definition, so no client can do this (at least without a special heuristic it’s dates, which doesn’t make much sense to be imposed)

You’ll probably don’t want to share exact same types between your server and client for this reason, but instead resort to specialised type generation for the front end like with Apollo Codegen or GraphQL Code Generator.

Hope that makes sense :) I’ll close this for now, but we’re obviously still available for any further questions

**Comment by RobbieGM** [comment]
I see why strings shouldn't be auto-deserialized to Dates, but why should generating types rather than sharing them be a requirement? It's more convenient to just `import` rather than running some kind of watcher to generate types, and the solution to this problem of having correct typings would be quite simple--just tell API consumers that they are not quite getting what they expected but rather a somewhat serialized version of it.

**Comment by kitten** [comment]
@RobbieGM Its basically a recommendation to avoid this trouble :) A lot of normalisation goes on in GraphQL and a lot of serialisation in terms of scalars. In fact, scalars even come with definition on not only how to parse their special values but also on how to serialise and normalise them. This is inherent to GraphQL, so it’s hard to specifically inform about something that is so tied to how it handles things 🤔 

Specifically, I wouldn’t share the types just because it’s likely that these small differences between server types and client types (after normalisation and serialisation) can lead to this confusion.

**Comment by robert-zaremba** [comment]
Hi,
So what's the recommended way to convert string to dates, when the type of a filed (in GraphQL scheme) is `Time`?

**Comment by clentfort** [comment]
Hi, I wrote a custom scalars exchange to scratch my own itch. You can find it here https://www.npmjs.com/package/urql-custom-scalars-exchange.

**Comment by shtse8** [comment]
I believe it warrants reconsideration because sharing code bases between client and server has become more prevalent today. This functionality should be optional to use. This is particularly true for the Date type, as I find myself having to manually deserialize each field.

**Comment by musjj** [comment]
urql-custom-scalars-exchange is unfortunately no longer maintained. What's currently the best approach for dealing with this (and serializing other custom scalars)?
