### ISSUE TITLE
Using relative url with next.js api routes

### ISSUE THREAD

**Issue by BjoernRave** [FormidableLabs/urql#484]
I am not a 100% sure if this restriction comes from urql, but it only allows absolute urls. When using next.js [api routes](https://github.com/zeit/next.js/issues/7297) it hinders me from an easier config, since I could theoretically just pass`'/api/graphql'` as url

**Comment by kitten** [comment]
Sorry for not replying to this for so long. I don't think this has anything to do with urql. Most likely you're trying to use an absolute URL on the server-side which won't work? Could that be?

If your API is on the same server as the app, it may be worth to create a small `fetchExchange` for the server-side that instead just uses your GraphQL schema directly.

**Comment by kitten** [comment]
Closed due to inactivity. [`next-urql`](https://github.com/FormidableLabs/next-urql) is maybe the better place to ask this at.

**Comment by BjoernRave** [comment]
I would like to ask this again. My problem is, that I am using next.js api routes for my graphql server, so my api routes are on the same domain. My application has a subdomain for every user and it would things much easier if every subdomain would send requests to their "own" api routes, so that cookies get passed accordingly

**Comment by dsebastien** [comment]
I also wonder about this. Why can't we pass a relative URL to urql? 

> If your API is on the same server as the app, it may be worth to create a small `fetchExchange` for the server-side that instead just uses your GraphQL schema directly.

I'm curious about this. I get the idea, but is there an example somewhere? I'm not too sure about how to create/use a `fetchExchange`.

**Comment by kitten** [comment]
Typically this should work but I never looked into this because of the lack of reproductiveness without spinning up a full Next project for this. The `url` option is just passed to `fetch` so the same rules apply as for any other `fetch` call, ergo this shouldn't be an issue. What is probably an issue is if you make this call on the server-side which means that it'll fail

**Comment by dsebastien** [comment]
Alright, I'll try again tonight. Yesterday I couldn't wrap my head around what you meant with "a small fetchExchange". Tried a few things, but didn't get anywhere. Indeed the code must run on the server (initiated through Next's `getServerSideProps`), which is why I was trying to figure out how to `require` the schema and pass it directly to the urql client.

**Comment by JoviDeCroock** [comment]
Hey @dsebastien if you can make a small example in https://codesandbox.io/ I'm up to take a look

**Comment by dsebastien** [comment]
It's alright. I was just using it wrong ;-)
