### ISSUE TITLE
Update cache for a query after mutation

### ISSUE THREAD

**Issue by morajabi** [FormidableLabs/urql#56]
As an example, I have a query (a list of things) in another part of the app, which I need to update the cache for it based on a mutation (add to list) in another part of the app. 

~I can return the whole data (the updated list) for that query so it gets updated, but I think if I can only return only the newly added thing, and manually add it to the list in the cache.~

~I don't know if it's a good idea or it's achievable in another way (plz lemme know). Thanks!~

Could you please explain why it's not possible to use the returned data from the mutation for invalidation, instead of fetching from the server? Thanks :)

**Comment by morajabi** [comment]
Continued in #59

**Comment by morajabi** [comment]
So it seems it wasn't the same as #59

**Comment by kitten** [comment]
Probably a good idea to refer to #85 instead.

Updating the cache manually is impractical as we currently invalidate stale caches. We don't have cache normalisation so updating the cache manually after a mutation can get you into all kinds of trouble since it's a lot of hacky, manual work. It'd honestly be easier to just do the refetch or to store the mutation's result in local UI state for as long as queries are refetching.

**Comment by kitten** [comment]
v1 is released now which means this issue was resolved / is out-of-date 👌

Some docs and a proper announcement for v1 are still in progress in pending. It's completely usable so far but the API has changed, so I have to ask for some more patience, but everything will be ready quite soon ✌️

**Comment by jgoux** [comment]
@kitten Could you expand a bit on the solution proposed by the v1 API in this case?

In my case I'd like a "dumb" solution to cache invalidation, which is to refetch a query when a specific mutation triggers.

For that to happen, we should be able to pass some kind of dependencies.

Now that I think about it, it could looks like `useEffect` API, with a list of mutations that triggers the query's refetch when they're executed. 😄 

```js
// refetch getTodos when one of addTodo, removeTodo or editTodo mutation is triggered
let [{ data, fetching, error }] = useQuery({ query: getTodos }, [addTodo, removeTodo, editTodo])
```

**Comment by tonypee** [comment]
Cache seems to invalidate for me (im quite impressed). Re OP - it is now using the query from the mutation to invalidate - i just found out that that was my issues (not returning a query). i suggest you do some testing

**Comment by kitten** [comment]
@jgoux If you need to invalidate unrelated queries when a mutation happens your Beet bet is to write a customised cache. This is intentional as we're orienting urql more towards customisability and experimentation friendly APIs.

So currently the document-based cache that is the default only invalidates your queries when any type names match up which is already a common heuristic and would even be needed in a normalised cache
