### ISSUE TITLE
originalError is not fully preserved during ssr serialization/deserialization

### ISSUE THREAD

**Issue by mtford90** [FormidableLabs/urql#562]
Only `GraphQLError.message` seems to be preserved. See [ssr.ts#40](https://github.com/FormidableLabs/urql/blob/master/packages/core/src/exchanges/ssr.ts#L40)

 In our project (which uses next.js) we'd like to use the `originalError` to access error codes and set a status (e.g. 404 if `error.graphQLErrors[0].originalError.error_type === "NotFound"` in our case. The `originalError` seems to be fully available during the prepass but only `message` is available when next.js performs its own render.

I was able to make a fix for this problem myself in a fork and all seems to be working fine. I haven't made a PR as I need to check out your contribution guidelines first and the solution is probably a bit rough but, none the less, I'd appreciate some feedback/comments on both the problem and my approach to solving it: https://github.com/mtford90/urql/commit/d0229ce815a679c6a33cbaaa4a12295842803bbc

Cheers & let me know if anymore info is needed.

**Comment by kitten** [comment]
Hiya 👋 I’ve just taken a look and we’ve indeed forgotten to serialise `GraphQLError`s in the `ssrExchange`. That being said I’m not quite comfortable with the idea of serialising an entire arbitrary error instance for multiple reasons:

- there are differing sets of properties on `Error` from engine to engine, filtering them all and maintaining this is tedious and keeping a list of properties that should be serialised is arbitrary
- These errors don’t have to be simple `Error` instances like in your case, they can contain any number of custom properties
- We could accidentally expose sensitive information without people being aware of it, since errors on the server-side may carry more information on properties than one would wish to expose

But the `GraphQLError` already has a solution to this. They standardise one the `extensions` property being an arbitrary object of properties. Would that be sufficient for your use-case?

I’m definitely up for opening a PR that adds proper `GraphQLError` serialisation that leaves out all but `message`, `nodes`, `path` and `extensions`, which is definitely safe

**Comment by kitten** [comment]
The above PR should fix this behaviour. As previously said it unfortunately does not serialize `graphqlError.originalError` so as not to expose it accidentally, but it does serialize `extensions` fully.
