### ISSUE TITLE
cache invalidation problem with empty lists and adding the first item

### ISSUE THREAD

**Issue by gabor** [FormidableLabs/urql#596]
short version: when adding the first item into an empty list, the cache does not get invalidated.

long version:
imagine a have a schema where i have a `Group` type, and groups contain lists-of-users.
something like:
```graphql
type User {
  id: ID!
}

type Group {
  id: ID!
  users: [User!]!
}

type Query {
  getGroup(id:ID!):Group
}

type Mutation {
  addUserToGroup(userID:ID!, groupID:ID!):User!
}
```

now, on a page i show the details of a given group, a list of it's users, with a query like:
```graphql
getGroup(id:"42") {
  id
  users {
    id
  }
}
```

i can add a new user on the page, which executes a mutation like:
```graphql
addUserToGroup(userId:$userId, groupId: $groupId) {
  id
}
```
(i did not write out the `__typename` attributes, but they are there).

usually this works fine, i mean, if i create an user, the mutation returns the `User` typename, and the cache gets invalidated, and the list of users gets updated.

but, if i display a group, where there are no users, and i create the first user, the page does not refresh, i assume, because originally the `User` typename did not arrive, because there were no users.( i am not 100% sure about this, i am just guessing here).

is there a way to work around this problem?

**Comment by JoviDeCroock** [comment]
Hey,

You can find more information about this limitation here: https://github.com/FormidableLabs/urql/issues/378

This can be solved by using `graphCache`, essentially the issue comes down to us not having the possibility to know what type that list of users is unless you are using something like `relayPagination`.

```
getGroup(id:"42") {
  id
  users {
    id
  }
}
```

If there are no users, we don't know that `__typename` users should invalidate this.

More resources on this:
- https://spectrum.chat/urql/help/query-not-refetched-after-a-mutation-using-exchange-graphcache~615d2331-2899-4648-ae26-88e6a50d2223

**Comment by gabor** [comment]
hi,

thanks for the answers. some more questions:

1. in case of relay-pagination, how would this be solved? for me it seems that if there are no items, there will be no items with with relay, too.

2. you mentioned this can be solved by "graphCache". would graphCache solve this transparently for me, or would i have to write custom code to manipulate the local-cache after the mutation? the reason i'm worried about graphCache is that i have used the apollo client-side graphql libraries before, where you have a normalizing cache, and i had to write manual code to update related things after mutations, and it became  so complex, it was unmanageable. my hope was that with the urql-document-cache, i trade fetching "efficiency" for easier correctness.

3. is there a way perhaps, to manually add a couple more typenames to a query somehow? something like `useQuery({query, additionalTypeNames:['User']})`

**Comment by JoviDeCroock** [comment]
1. in the case of relay you would return the edge that has changed to have the correct navigation, and that would refetch that edge.
2. you would need a `custom updater` (anything with lists needs custom stuff since we can't make assumptions about it, lists are hard)
3. We have thought about this but haven't really went on that avenue, I might bring it up again today since more people seem to run into it.

Thank you for your feedback btw, I highly appreciate it.

**Comment by gabor** [comment]
i saw the pull-request, i'm glad it is happening.

for now i went with a hack, where in the graphql-schema i have queries returning a "dummy" object for every type, so in the query i can do something like:

```graphql
getGroup(id:"42") {
  id
  users {
    id
  }
}

dummyUser {
  id
}
```

this is enough to associate the cache-item with the object-type. of course, your draft solves this much more elegantly.

**Comment by JoviDeCroock** [comment]
Hey @gabor 

This has been released and documented here https://formidable.com/open-source/urql/docs/basics/document-caching/#document-cache-gotchas

**Comment by gabor** [comment]
@JoviDeCroock thank you,  i tried it out and it works well!

**Comment by acro5piano** [comment]
The document moved here:

https://formidable.com/open-source/urql/docs/concepts/document-caching/#adding-typenames
