### ISSUE TITLE
[graphcache] mutation update executed twice

### ISSUE THREAD

**Issue by zenios** [FormidableLabs/urql#653]
Hi All

I have a mutation update configured for graphcache that for some weired reason it is executed twice for a single mutation.

One execution with empty result
Second execution with filled result

I did some debugging and i can see that the first execution is done via writeOptimistic before the mutation is send to the server.

And the second is the correct execution done after the results arrives.

I dont have any optimistic configurations in place

**Comment by zenios** [comment]
The mutation is

```
mutation CreateFriendRequestMutation($withUserId: ID!) {
  createFriendRequest(withUser: $withUserId)
}
```

I dont know what other information i can provide

**Comment by JoviDeCroock** [comment]
A reproduction is the source of all information, it's very hard for us to make an assumption as to what variables you are calling with, ... For instance why is there no result is it an invalid call or the same call as the second?

**Comment by zenios** [comment]
The mutation accept a string and returns a boolean.

And the update is called twice one with result as {} and the second with result {createFriendRequest: true}

**Comment by JoviDeCroock** [comment]
So what I can derive from your current explanation is the following:

You have:

```
cacheExchange({
  updates: { Mutation: { createFriendRequest: () => smth  } },
  optimistic: { createFriendRequest: () => smth  },
})
```

And you are asking why `createFriendRequest` is called twice, right? The last argument of your updater function is `ctx` which has a property called `optimistic` this can help your determine if this is called because of an `optimistic` update or just your regular response.

This because even if it's an optimistic update you can have special logic, like adding an item to a list, we allow the user to utilise the updater function for the response they construct in `optimistic` and the one they get from their server-response.

**Comment by zenios** [comment]
Here is a sandbox

https://codesandbox.io/s/focused-night-ztnmm

I have a console log inside update that you can see it logs twice

The only difference from my case is in sandbox case both result and args are null on first execution
and args null on second execution

**Comment by JoviDeCroock** [comment]
Thanks for the reproduction @zenios that's appreciated, it had to do with the fact that the mutation had no selectionset, there's a fix PR up!

**Comment by zenios** [comment]
You are welcome

**Comment by kitten** [comment]
Fixed in https://github.com/FormidableLabs/urql/releases/tag/%40urql%2Fexchange-graphcache%402.3.0
