### ISSUE TITLE
Cache updates on error

### ISSUE THREAD

**Issue by zenios** [FormidableLabs/urql#670]
Hi

lets say i have this type

```
type User {
    id:ID!
    name:String!
    presence:Boolean!
}
```

And the following two queries

```
query User {
  user {
    id
    name
  }
}

query Presence {
  user {
    id
    presence
  }
}
```

At the beginning i execute the first query everything goes well and cache is updated with the results.

At a second stage i execute the second query and the server errors, returning null for user and an errors array.

I noticed that cache is updated and setting user to null. Is this something that should be supported? I understand that graphql supports partial data and errors but is it correct to invalidate the whole user entity because one query errored?

**Comment by kitten** [comment]
We have no way of knowing _why_ a given field is `null` or has been set to `null`, but only the link will be affected.

So given this situation there are multiple factors: do we check the error? This in truth is difficult, because `errors[].path` may not always be present, and even if it is, we still can't know whether the error affects the link or not.

The alternative in user-land here is to define a cache resolver that can get to the user without the link, which is only possible obviously if `user.id` is stable.

That being said, if your UI and app requires `Query.user` to exist and an error makes it `null`, isn't the GraphQL API implying that it may be `null` due to an error although you expect it to be delivered, i.e. this field shouldn't be `null`?

If you don't have control over the API it may be worth having a mapping exchange that nulls out the entire response if your expected field isn't set, to work around the fact that you expect this field to be required.

**Comment by zenios** [comment]
Understood. Thanks you very much
