### ISSUE TITLE
relayPagination does not play well with suspenseExchange

### ISSUE THREAD

**Issue by zoontek** [FormidableLabs/urql#685]
Hi! I'm using graphcache and suspense exchange both and I noticed that when suspense mode is enabled, the "fetch next results" request using the `relayPagination` will throw the Promise and display the initial suspense loader.

```json
// urql version & exchanges
{
  "@urql/devtools": "0.1.2",
  "@urql/exchange-graphcache": "2.3.0",
  "@urql/exchange-suspense": "1.8.7",
  "urql": "1.9.5",
  "wonka": "4.0.9"
}
```

**Steps to reproduce**

1. Create a project with graphcache and suspense exchanges.
1. Wrap a page displaying a list of paginated items with a `React.Suspense` component and its fallback.
1. Scroll or click next to load next items.
1. The loading fallback will appear.

**Expected behavior**

It should be possible to disable suspense mode when fetching next paginated results and handle the list loading locally (or maybe another option I didn't think about?)

**Actual behavior**

The Promise is throw, then caught by the parent `React.Suspense` component, displaying the initial loading view.

I refreshed the app at start, then scroll to fetch more results:

![hZ8PSfRWyy](https://user-images.githubusercontent.com/1902323/78821453-cb116380-79d9-11ea-99b8-4fa940e5a3d1.gif)

**Comment by kitten** [comment]
That's unfortunately expected behaviour. When `urql` returns into a loading state then there's no way to avoid the suspense when you're using `@urql/exchange-suspense` with suspense mode.

The reason for that is that you're getting a cache miss here, so no result at all, which means that the hook doesn't have any data to display, hence the suspense interruption.

This can be worked around using the "partial cache data" mode in Graphcache, since then the result will be fetched in the background if only some data is missing.

Apart from that we don't recommend the usage of client-side suspense anymore. It boils down to being a "fancy loading state" for `urql` on the client-side, and isn't supposed to be used for that, since the normal `fetching` flag does the trick as well. Overall suspense doesn't currently really do much for us and we're considering deprecating `@urql/exchange-suspense`.

**Comment by zoontek** [comment]
> The reason for that is that you're getting a cache miss here, so no result at all, which means that the hook doesn't have any data to display, hence the suspense interruption.

Ok, I get it 🙂

> Apart from that we don't recommend the usage of client-side suspense anymore. It boils down to being a "fancy loading state" for urql on the client-side, and isn't supposed to be used for that, since the normal fetching flag does the trick as well.

You recommend keeping `suspense` off and handle the fetching state in each component?

**Comment by kitten** [comment]
@zoontek If you can, it will give you more control over your loading states, yes 😅 That being said, if you already hoist much of your data fetching up to a higher component in your tree, this won't be as bad as it sounds

**Comment by zoontek** [comment]
I removed suspense, everything work wells then. Thanks for all your help!

**Comment by micabe** [comment]
Hi @kitten ,
I also want to point out that it does not play well with `subscriptionExchange` too. Some subscription updates never come..
best regards

**Comment by kitten** [comment]
@micabe Hiya 👋 feel free to ask on Spectrum about that or open another question issue here on GitHub.
This shouldn’t cause any issues so this is definitely unexpected; but maybe something else may be going on.

**Comment by micabe** [comment]
Thanks @kitten,
I left a thread on Spectrum https://spectrum.chat/urql/help/subscriptions-updates-do-not-go-through-with-suspense-true~03ddb938-994f-496e-92cb-81915a3a4369 👍
