### ISSUE TITLE
More precise useQueryResult type

### ISSUE THREAD

**Issue by XVincentX** [FormidableLabs/urql#696]
Hey,

I've been using the urql client for a while and I've been noticing that maybe the hooks could leverage some typings to give some guarantees and skip some `if` in the code.

Basically if these 3 assumptions hold:

- If `fetching` is `true`, `data` is undefined and `error` is undefined
- If `fetching` is `false`, and `data` is not undefined, then `error` is undefined
- If `fetching` is `false`, and `error` is not undefined, then `data` is undefined

Then we can write a type union that encompasses these cases so that impossible states are unrepresentable but more importantly the type checker will restrict the type avoiding to do some null checks along the way.

```ts
export type UseQueryState<T> =
  | {
      fetching: boolean,
      stale: boolean,
      data?: T,
      error?: CombinedError,
      extensions?: Record<string, any>,
    }
  | {
      fetching: true,
      data: undefined,
      error: undefined,
    }
  | {
      fetching: false,
      data: undefined,
      error: CombinedError,
    }
  | {
      fetching: false,
      data: T,
      error: undefined,
    };
```

**Comment by kitten** [comment]
Hiya 👋

Unfortunately none of these states are mutually exclusive, which is why the type isn’t more precise. Let me quickly list them out 😅

If you’ve already fetched before and are changing the inputs, you’ll be back at fetching new state, but will still have access to the previous state’s data. Hence `fetching` may become `true` again while `data` and `error` are still accessible.

The `error` and `data` states can also coexist. In GraphQL any query may deliver partial data. If a resolver on an optional field (which may cascade even) has errored, then the server will still send _some_ available data, `null` out some fields, and will deliver one or more `GraphQLError`s (per errored resolver).
This is why `urql` abstracts this with the `CombinedError` already, to make this part a little more user-friendly.

Apart from this there’s also some other (less common) states. The `stale` flag for instance hints at data being fetched in the background while some cached data is already available.

Hope this makes sense! 🙌

**Comment by XVincentX** [comment]
It totally makes sense, thanks for the quick clarification — as long these checks are legit I'm fine with having them there.

Cheers!
