### ISSUE TITLE
svelte: re-render just an item in list, not all the list items

### ISSUE THREAD

**Issue by frederikhors** [FormidableLabs/urql#704]
Coming from `svelte-apollo` (a project that seems abandoned (no recrimination, everyone takes their time as they can), I would like to avoid the same fate for `@urql/svelte` that I want to use in my next projects) I can see here a similar issue.

### Reproduction steps:

- go to REPL: https://codesandbox.io/s/urql-svelte-list-rerendering-uwsvn

- click a button

- every button re-render; so the entire list re-render itself

- I expect re-render only the button I clicked

Same problem for `svelte-apollo` here: https://github.com/timhall/svelte-apollo/issues/19

I know this can be something we have to fix in our application using a solution like:

```svelte
const data = query(client, {
  query: SOME_QUERY,
});

let resultData = []
$: $data.then(data => resultData = data.data.queryResult)
```

but this solution as you can see is very cumbersome as the project grows.

What do you think about?

**Comment by frederikhors** [comment]
I also tried with `<svelte:options immutable/>` in `Button.svelte` but the problem is still there.

**Comment by frederikhors** [comment]
Here an example by Svelte docs about immutability: https://svelte.dev/examples#immutable-data

**Comment by kitten** [comment]
This is all due to reactive, immutable data, and that’s the same principle as in React. And this is the correct behaviour.

Have a look at your network tab and you’ll see that when you send a mutation data is invalidated and the cache updates queries.

This updates the data which causes a rerender with the fresh query data and is expected behaviour :)

This is described in here: https://formidable.com/open-source/urql/docs/basics/document-caching/

As for the result not changing. We’re getting a new server-side response. That means you’ll have a fresh result. Hence the rerender. So the mantra, as in React or Preact, will always be to let the component rerender and not do a deep-equal diff, which is potentially more expensive than just rerendering a part of the app.

**Comment by frederikhors** [comment]
Oh. Now I'm a little sad.

Practical example.

I have a list of 200 players who are playing by nickname and score. Example:

- John Wayne (150)
- Heidi (200)
- Mario Bros (300)

Each of them can vary both the nickname and the score or it can even disappear.

I need the list to be always fully visible on the page.

This is a problem but maybe I can use "Normalized cache" for this, what do you think?

**Comment by kitten** [comment]
So the normalized cache may still cause an update; even if it doesn't send an additional request.

There's a reply on this on this thread: https://github.com/FormidableLabs/urql/issues/648#issuecomment-601621596

So basically:

> If you’re not seeing any performance issues, I wouldn’t be worried, but if your component is indeed becoming slow, it may be helpful to use `React.memo` — as you’ve mentioned — with a deep equal comparison, for instance `react-fast-compare` to avoid rerendering all notifications too often.

So this is left up to userland. In this case you'd have your components check whether they need to rerender.

But if you think about the complexity of this, it's easier to first think about virtualizing your list, because DOM renders / browser renders are always more expensive than the data mangling on the JS-side. This is also why it's a UI library responsibility and not ours.

Apart from virtualisation you can also deep-equal the entire data result, possibly with a separate svelte store function. Similarly it's also possible to write an `urql` exchange to filter out deep-equal results. But again, at this point you're deep-equaling data (so doubling the cost) of traversing all the data, instead of stopping at each rendering view.

**Comment by frederikhors** [comment]
I'm sorry but my head is frying. I can't understand this situation: it's crazy.

_I am taking advantage of your **kindness** and **courtesy** and I hope to help those who like me will happen here in the future._

If I read here: https://svelte.dev/tutorial/svelte-options, I understand that by using:

> immutable={true} — you never use mutable data, so the compiler can do simple referential equality checks to determine if values have changed

> immutable={false} — the default. Svelte will be more conservative about whether or not mutable objects have changed

If you see the example they are changing the `todos` array as we are also doing with `urql`:

```js
let todos = [
  { id: 1, done: true, text: 'wash the car' },
  { id: 2, done: false, text: 'take the dog for a walk' },
  { id: 3, done: false, text: 'mow the lawn' }
];

function toggle(toggled) {
  todos = todos.map(todo => {
    if (todo === toggled) {
      // return a new object
      return {
        id: todo.id,
        text: todo.text,
        done: !todo.done
      };
    }

    // return the same object
    return todo;
  });
}
```

Why it doesn't work with our `todos` example?

**Comment by cdock1029** [comment]
Because of this:
>// return the same object

**Comment by kitten** [comment]
When we get a new server result it will be a new array, yes. In the case of Graphcache it’ll also be a new response.

It’s immutable all the way down, so all the data is fresh when a new result comes in :)

**Comment by frederikhors** [comment]
Okay, I'm getting there.

So, to better understand:

- I changed my first example in this: https://codesandbox.io/s/urql-svelte-list-re-rendering-with-no-flash-jyqoy (I removed the orange "flash" effect)

- I opened it full screen here: https://jyqoy.csb.app

- I opened the Chrome Dev Tools and checked-in "Paint flashing":

![image](https://user-images.githubusercontent.com/41120635/79518103-795b7f80-8050-11ea-88e4-3efdf735f056.png)

- If I click one todo the others don't get re-painted

![image](https://user-images.githubusercontent.com/41120635/79518434-5da4a900-8051-11ea-81fe-330bcda49d13.png)

So now **the million dollar question**:

If Chrome is not re-painting the others todos what does it mean?

Is it capable of understand what is changed and what not?

Is this the correct behavior you were talking about, @kitten?

**Comment by kitten** [comment]
Ok, just to iterate through this from the top 😅 

- You have a list of todos from an API, via a result with `data`
- You send a mutation causing this query to update
- `urql` sends a new query and receives a new result for said list. All the data has changed
- `svelte` sees this update and rerenders
- All items are mapped to buttons, which subsequently also rerender
- All buttons update with the new item

That's the flow here; if you look at the devtool's network tab you can also see not only the mutation but also the new query. In Graphcache you wouldn't have this query, but you'd still have a new result from the cache anyway.

Now that means that you can't stop the rerender of `App` which contains the query, which is semantically correct and by design. That's just idiomatic 😉 

I'm not too well versed with how to start adding the equivalent of `React.memo` to a Svelte component, but Button would have to do a _deep equality check_ if it wanted to do stop the update (or a shallow check if you don't have nested data for your todos)

**Comment by frederikhors** [comment]
Ok, everything is clear to me.

You are an angel, @kitten.

Just one last thing:

If **Chrome is not re-painting** the others todos (no green color on them) does it mean it's capable of understand what is changed and what not, right?

And this Chrome feature (no-repainting) helps us with performance, right?

**Comment by kitten** [comment]
@frederikhors yes, this may be something on a lower level; but either Chrome doesn’t mark this as an update because nothing has changed, or Svelte doesn’t update the DOM elements in its fragment functions when nothing has changed, or both even

**Comment by frederikhors** [comment]
You angel, thanks.
