### ISSUE TITLE
svelte: error: "Function called outside component initialization"

### ISSUE THREAD

**Issue by frederikhors** [FormidableLabs/urql#711]
`@urql/svelte: 0.2.0`

**Steps to reproduce**

- go to REPL: https://codesandbox.io/s/urql-svelte-error-function-called-outside-component-initialization-jyqoy?file=/App.svelte

- the error appears in all its magnificence:

```error
"Function called outside component initialization"
```

**Expected behavior**

I need to assign `todos` store after the `sleep()` function:

```svelte
onMount(async () => {
  await sleep(2000);
  todos = query({ query: TODOS_QUERY });
});
```

**Actual behavior**

It works if you use the "classic":

```svelte
$: todos = query({ query: TODOS_QUERY });
```

**Comment by kitten** [comment]
You can’t call a store creator outside the component; internally it uses things like `getConrext` so that won’t work :)

Especially with the delay it won’t be called with the right timing; I’m not sure what you’re trying to achieve but maybe you’ll want to look at using the client’s methods directly

**Comment by rlundquist3** [comment]
Was spinning my wheels on this for a while as well. Turns out the suggestion [here](https://stackoverflow.com/questions/62101637/urql-svelte-function-called-outside-component-initialization-if-not-in-onmou) of moving svelte to `devDependencies` needed to be done for `@urql/svelte` as well??? That change got me up and running at least. Hopefully no unintended consequences.
