### ISSUE TITLE
svelte: error: process is not defined

### ISSUE THREAD

**Issue by frederikhors** [FormidableLabs/urql#712]
`"@urql/svelte": "0.1.3"`

Using this project: https://github.com/frederikhors/svelte-urql-app, I had to add in `rollup.config.js` the below code to make it work:

```js
import replace from '@rollup/plugin-replace'
...
replace({
    'process.env.NODE_ENV': JSON.stringify(
        production ? 'production' : 'development'
    ),
}),
```

or I had this error:

```console
urql-core.mjs:501 Uncaught ReferenceError: process is not defined
    at new Z$1 (urql-core.mjs:501)
    at initClient (urql-svelte.mjs:18)
    at instance (App.svelte:6)
    at init (index.mjs:1385)
    at new App (App.svelte:12)
    at main.js:3
    at main.js:3
```

It can be useful?

**Comment by JoviDeCroock** [comment]
Hey @frederikhors 

This is because most off the time you'll do `NODE_ENV=x rollup`, this makes `process.env` defined. We use these checks to allow you to cut more bytes in a production build, this is a standard used in a majority of libraries.

```
replace({
    'process.env.NODE_ENV': JSON.stringify( 'production'),
}),
```

Removes all the `development` warnings saving a lot of bytes since these are just strings.
