### ISSUE TITLE
graphcache: (perhaps) svelte: cache in storage's write method doubled if slow query

### ISSUE THREAD

**Issue by frederikhors** [FormidableLabs/urql#724]
`@urql/svelte: 0.1.3`
`@urql/exchange-graphcache: 2.3.3` and `2.3.4`

**Steps to reproduce**

1. go on [fullscreen REPL](https://j9z66.csb.app)

1. open browser Dev Tools

1. click on "Posts"; let it load...

1. API for `albums` sleeps for about 4 seconds on purpose

1. when `albums` are downloaded see in console the latest `batch {}`

**Expected behavior**

It only contains `albums` objects.

**Actual behavior**

It contains both `albums` and `todos` objects. `Todos` comes from the first query it already completed!

**Additional context**

`batch: {}` come from [urql.js file](https://codesandbox.io/s/urql-svelte-cache-batch-contains-other-types-j9z66?file=/urql.js:387-421):

```js
write: async batch => {
  console.log("batch:", batch);
  ...
}
```
---

![image](https://user-images.githubusercontent.com/41120635/79796818-774a3700-8356-11ea-8df6-65318e514aac.png)

---

_It's the same on my localhost, not a Codesandbox fault._

[Codesandbox project](https://codesandbox.io/s/urql-svelte-cache-batch-contains-other-types-j9z66).

**Comment by JoviDeCroock** [comment]
That's intended this is due to commutativity, your query for albums dispatched first and then the one for todo's meaning that this could lead to inconsistent data.

That's why if the last query applies before the one before it will be tentatively applied and reiterated after. This is intended to make offline work consistently

**Comment by frederikhors** [comment]
Amazing. Thanks.
