### ISSUE TITLE
graphcache: 2.3.4: Invalid resolver data but no cache resolvers used

### ISSUE THREAD

**Issue by frederikhors** [FormidableLabs/urql#725]
Upgrading from `@urql/exchange-graphcache: 2.3.3` to `2.3.4` I have a new warning in console:

```error
Invalid resolver data: The resolver at `Query.players({"input":{"first":20}})` returned an invalid typename that could not be reconciled with the cache.
(Caused At: Unnamed query)
https://bit.ly/38yWDau#8
```

which I can't reproduce [on Codesandbox](https://codesandbox.io/s/urql-svelte-graphcache-234-invalid-resolver-data-1c5ct) because of https://github.com/FormidableLabs/urql/issues/723.

I'm not using cache resolvers. I changed nothing in my code.

What changed is my cache in localStorage.

Below what I think is the problem:

With **2.3.3**

```json
{"Query\tplayers({\"input\":{\"first\":20}})":":\"Query.players({\\\"input\\\":{\\\"first\\\":20}})\"",
"Query.players({\"input\":{\"first\":20}})\tnodes":":[\"Player:2385\"]",
"Player:2385\tscore":"739404",
"Player:2385\tcreatedAt":"\"2020-04-20T21:16:29Z\"",
"Player:2385\tid":"\"2385\"",
"Player:2385\t__typename":"\"Player\"",
"Query.players({\"input\":{\"first\":20}})\t__typename":"\"PlayersConnection\""}
```

With **2.3.4**

```json
{"Query.players({\"input\":{\"first\":20}})":":\"Query.players({\\\"input\\\":{\\\"first\\\":20}})\"",
"Player:2385.score":"739404",
"Player:2385.createdAt":"\"2020-04-20T21:16:29Z\"",
"Player:2385.id":"\"2385\"",
"Player:2385.__typename":"\"Player\""}
```

As you can see with `2.3.4` there are no more:

1. `"Query.players({\"input\":{\"first\":20}})\tnodes":":[\"Player:2385\"]",` (maybe useless, maybe) and

1. `"Query.players({\"input\":{\"first\":20}})\t__typename":"\"PlayersConnection\""` which I think is what it complains about

**Comment by JoviDeCroock** [comment]
Yes, we removed the `\t` from the entries since this got Firefox confused.

**Comment by frederikhors** [comment]
Is not about `\t` I think.

> As you can see with 2.3.4 there are no more:
> 
> "Query.players({\"input\":{\"first\":20}})\tnodes":":[\"Player:2385\"]", (maybe useless, maybe) and
> 
> "Query.players({\"input\":{\"first\":20}})\t__typename":"\"PlayersConnection\"" which I think is what it complains about

**Comment by kitten** [comment]
Yes, there’s been a breaking change that affects the persisted storage, since it’s still experimental.

We changed how the keying works, so if you wipe your cache and start from scratch it’ll start working again. We don’t as of yet, have a signal to indicate to the storage that the queries have failed since the offline API is incomplete.

Also, I know we’re not as responsive on Spectrum, but that’s by design. Please use it ♥️ We can’t build the tracks of someone’s figurative railroad fast enough.

We know that `@urql/svelte` and the offline features have quirks; but we need to free up time for every piece of work, and issues, while important, are inherently a slow process of validation, reproduction, investigation, and fixing.

So if we go via Spectrum we can take them slower and give you more detailed instructions on helping us find out what’s going on

**Comment by frederikhors** [comment]
OK.

> We changed how the keying works, so if you wipe your cache and start from scratch it’ll start working again.

Anyway it's not working after wiping.
