### ISSUE TITLE
[proposal] exchange to fetch schema

### ISSUE THREAD

**Issue by andrewmclagan** [FormidableLabs/urql#765]
Is there any logic that would inhibit developing an exchange that periodically fetches the GraphQL schema and caches it? Would simplify development and deployment to different environments. This would of course works best in an isomorphic setup.

**Comment by kitten** [comment]
In production, most APIs disable introspection to prevent the schema from being fully explored, which makes complexity attacks easily executable for attackers if the API isn’t protecting against them.

This is why Graphcache doesn’t implement introspection. Continuously updating the schema can also be detrimental when we introduce offline caching (persistence is already supported but still experimental; so undocumented for now).
Having the schema be added at compile time (using for instance GraphQL Code Generator or other tools) is simply a good way to “force” users to handle changing dramatically changing schemas gracefully.
That being said, considering changing schemas that adhere to best practices, like depreciation and additive changes, it is a possibility to have dynamic schema retrieval.

There are several problems however, which is why we haven’t added this:

- When is the schema I validated when it’s cached in local storage or a service worker?
- Is it acceptable to slow down all API requests by a non-minified schema download for a first time visitor, considering that serialised schema JSON is extremely heavy?
- Dynamically changing the schema on the fly in Graphcache isn’t hard per se, but we haven’t explored all implications.

So overall, you could move this to instantiation time for the time being, when you create your urql Client, but given tools like GraphQL Code Generator that can also generate types for our hooks, we haven’t seen dynamic schema fetching / introspection as a priority 😅

On a side note: In theory it’d even be possible for us right now to allow schema awareness with more user configuration rather than a schema, so we’re keeping our options open. (Although the DX of schema awareness is obviously much better)

**Comment by andrewmclagan** [comment]
Great answer thank you for taking the time, i will close this.

**Comment by Undistraction** [comment]
I know this is an old discussion, but I'd like to add that for many projects it isn't an option to include a schema in the source because the API is behind auth, and making the API shape available to unauthenticated users isn't an option. This means that the only option for exposing the schema to URQL is via a runtime introspection query. Not ideal, especially with larger schemas, but necessary in order to access nice features of graphcache like handling of partials.
