### ISSUE TITLE
@urql/core fails on require in Node 13

### ISSUE THREAD

**Issue by KyleAMathews** [FormidableLabs/urql#788]
With the new Gatsby Recipes feature, we're using Urql to do queries & subscriptions to drive the CLI UI as people run recipes (which has worked beautifully so thanks!).

A common bug report though is things don't work on Node 13 due to some incompatibility in @urql/core.

The error we get is `No valid exports main found for '/Users/John/node_modules/@urql/core'` e.g. this issue https://github.com/gatsbyjs/gatsby/issues/23202 (which also has reproduction instructions).

Things work correctly on earlier versions of node.

**Comment by kitten** [comment]
We're aware of this issue, but aren't quite sure yet how to resolve this.

In a prior update we set `package.json:main` on all ESM-supporting packages to exclude the extension: https://github.com/FormidableLabs/urql/blob/6716ae6dd2e630a4da6632f2092e2c42ca4ce04d/packages/core/package.json#L21

This is a fix for Webpack. When Webpack starts using `.mjs` files it by default stops looking at `package.json:module` in nested packages for some reason. This is unexpected and led Webpack to then look at `package.json:main` which means one package's `.mjs` bundle would lead to its dependency's `.js` to be used instead of `.mjs`.
The missing extension mitigated this issue.

Starting with Node.js 13 something weird happens however. In some cases (and I'm not sure what the pre-condition is, but `--experimental-modules` definitely causes odd issues) Node.js isn't happy with the lack of extensions and/or the lack of `package.json:exports`.

I'm currently suspecting that Node.js resolves the `.mjs` file even when it's not in "Modules-mode", which we may be able to mitigate by moving the extension-less path for Webpack to `package.json:browser`. This however would then fail again for when Webpack is used to bundle server-side bundles, like in Next.js, which currently works again.

**Comment by kitten** [comment]
Ok, so I still can't manage to reproduce this in isolation and following the instructions from that issue on Node `v13.14.0` also doesn't cause the issue 😅 

That being said though, the issue is 15 days old and we did ship a couple of fixes for ESM support less than 15 days ago (maybe 12 days ago or so?) https://github.com/FormidableLabs/urql/blob/master/packages/core/CHANGELOG.md#1114

**Comment by kitten** [comment]
Hiya :wave: So I haven't seen a re-report on your repo, so is this safe to close? cc @mxstbr

**Comment by KyleAMathews** [comment]
Tested on v13.14.0 and it's working! Thanks for fixing it right before I filed the bug haha :-D
