### ISSUE TITLE
next-urql: Have an official with-typescript-urql example in nextjs repo

### ISSUE THREAD

**Issue by pranaypratyush** [FormidableLabs/urql#818]
## Summary
I just discovered `next-urql` and I wonder why this amazing thing doesn't have a merged example in nextjs examples folder. 

## Proposed Solution
I could create an example but it might be opinionated. Would request people who are well accustomed to the package to submit a working example there

## Requirements
Since the new nextjs has `getStaticProps` and it's causing some confusion in the community I would recommend the example to be made after https://github.com/FormidableLabs/urql/issues/754 is merged and is incorporated in the example.

**Comment by kitten** [comment]
You're right, that's an easy win :+1:

**Comment by pmarsceill** [comment]
@pranaypratyush I was curious why the example in the next.js folder just uses the regular `urql` package also. Could you provide an example with `urql-next` ? I am curious because I've seen a few different ways of doing this, and I'd like to see how to use this package without opting out of the [Automatic Static Optimization ](https://nextjs.org/docs/advanced-features/automatic-static-optimization) if possible.

**Comment by kitten** [comment]
I think for now we'll let this one be superseded by #1502, i.e. an example in our own repo among a lot of others
