### ISSUE TITLE
Mutations not working

### ISSUE THREAD

**Issue by ar1a** [FormidableLabs/urql#82]
Hey, my backend is using https://github.com/rmosolgo/graphql-ruby and when I run this mutation like so
```
const MarkCollectedMutation = `
mutation {
  updateItem(itemId: "6", collected: true, collectedBy: "Aria", collectedAt: 1234) {
    id
    collected
    collectedAt
    collectedBy
    code
  }
}
`;
  const onKeyDown = async e => {
    if (e.keyCode === 13) {
      console.log(item.id, e.target.value, Date.now());
      const data = await markCollected();
      console.log(data);
    }
  };
    <Connect
      query={query(ItemsQuery)}
      mutation={{
        markCollected: mutation(MarkCollectedMutation, { collected: true })
      }}
      children={({ loaded, fetching, refetch, data, error, markCollected }) => (

```
I get the error 
`Uncaught (in promise) {message: "No data"}`
and the server logs
```
Started POST "/graphql" for ::1 at 2018-05-22 12:06:26 +1000
Processing by GraphqlController#execute as */*
  Parameters: {"query"=>"mutation {\n  updateItem(itemId: \"6\", collected: true, collectedBy: \"Aria\", collectedAt: 1234) {\n    id\n    collected\n    collectedAt\n    collectedBy\n    code\n    __typename\n  }\n}\n", "variables"=>{}, "graphql"=>{"query"=>"mutation {\n  updateItem(itemId: \"6\", collected: true, collectedBy: \"Aria\", collectedAt: 1234) {\n    id\n    collected\n    collectedAt\n    collectedBy\n    code\n    __typename\n  }\n}\n", "variables"=>{}}}
Completed 200 OK in 3ms (Views: 0.3ms | ActiveRecord: 0.0ms)

```

**Comment by kitten** [comment]
You can try to use `0.3.0-next1` under the `@true` tag which should give you more detailed errors, which is one of the changes of this new v0.3. Generally this poor error in v0.2 indicates that the query hasn't received any data.

This can have multiple reasons. The most common one being that your mutation returned an error in a resolver and no data, which is still `200 OK`, since the request was completed successfully from an HTTP standpoint. So you can also just look at the network tab in your devtools and observe the GraphQL query's response. It'll probably be something like:

```json
{
  "data": null,
  "errors": ["Oh no! XYZ went wrong"]
}
```

That's at least my suspicion 😅  Hopefully v0.3 will land soon so that this becomes less confusing

**Comment by ar1a** [comment]
This was caused by #86
