### ISSUE TITLE
graphcache caching errors

### ISSUE THREAD

**Issue by protometa** [FormidableLabs/urql#825]
I am using graphcache and have a simple query that may fail sometimes. If it fails initially, data is not fetched on subsequent requests. It seems the null data from the error response is cached.

urql version & exchanges: urql v1.9.7, exchange-graphcache v2.4.2

**Steps to reproduce**

I think I have reproduced a failing test case but I don't really know what I'm doing: https://github.com/protometa/urql/commit/ec0905850bac597eddd5ac3f1c5434f194c554e0

**Expected behavior**

Second request after error is a cache miss and fetches data.

**Actual behavior**

Second request after error is a cache hit and contains null data.

**Comment by JoviDeCroock** [comment]
Hey,

The reasoning behind this is that data should be invalidated when for instance the user isn’t authorized to view this anymore. We can’t decide for you whether or not this error invalidates cache.

There are a few options you can take though, you can change your requestPolicy to cache-and-network or you can use @urql/exchange-retry.

**Comment by protometa** [comment]
I understand that data should be invalidated on auth errors. That makes sense to me.

In my scenario the first request is an auth error. After setting the right token the request runs again without errors but is a null value. This makes no sense to me.

> GraphCache should also refetch that query next time you hit it because your data is null

I believe this is not happening in my case or in the test which seems to show that the null is cached and returned on the next request.

**Comment by kitten** [comment]
If only a single field is `null` this may be valid data. The error may have some path information but either way, we can’t infer whether this error state is consistent or temporary.

So that `Query.author` field is written. If you don’t want that to happen then the entire `Query` data must be `null` instead to indicate that the query does not have a result.

If this is happening because of an auth error and you’re refreshing your token, you may want to not let the failed results come through to the cache.

If you have an exchange set up for authentication, like an `authExchange`, then you could use the `retryExchange` to get a fresh result once you have a new token and are authenticated

**Comment by protometa** [comment]
In Apollo server an error thrown in a resolver will result in a response that still contains `"data": { "author": null }` for example. This kind of null response is also handled in the `correctly clears on error` test so I thought maybe that was expected (though the error in that test is on a mutation). But you're telling me that this is a problem with the server, perhaps not setting the `Query.author` to non-nullable?

**Comment by kitten** [comment]
There’s no special handling of errors in Graphcache, because the presence of errors doesn’t actually tell us anything at first.

When Graphcache sees a field that leads to an entity or null, it’ll cache this link internally. Conceptually we can’t tell whether this field has errored or not. If we could tell that it has errored (which is possible with a full `GraphQLError`) we still can’t make the assumption that it’ll only _sometimes_ error.

We basically assume consistency and that every result reflects the server state accurately. If something is inconsistent that breaks assumptions 😅


The mutations are a separate case btw, because mutations are never queried from the cache. So a `null` field there simply does nothing

**Comment by protometa** [comment]
In my case it's too aggressive that responses containing errors should contribute to the cache. How can I prevent that in general? Should I use a modified graphcache or can it be done with another little exchange?

**Comment by protometa** [comment]
As far as I can tell there is no `requestPolicy` or other context that an exchange can pass back up the chain to prevent a response from being cached :/

That could be a useful feature.. maybe in the form of a `cachePolicy`.

**Comment by kitten** [comment]
So to back this up a little, we don’t know much about your underlying use-case here, so we can’t propose a solid way forward.

Graphcache can in theory skip caching fields that have errors, but that also depends on the error path field from `GraphQLError`s which a lot of APIs don’t provide due to users not knowing about this detail. Even then we’d not be able to definitively say what to do.

A workaround would be to modify the original GraphQL query document to exclude the fields on a result that have errored. Then on a subsequent request you’d fetch them again. This also isn’t always desirable behaviour though, because sometimes errors are simply expected.

It’s also not unlikely that a combination of the `retryExchange` and `cache-and-network`may work for you. Or you could even read out the errors on the framework / hook level and decide to call `executeQuery` manually to refetch.

**Comment by protometa** [comment]
The `retryExchange` doesn't seem right in my case as I don't want to retry immediately. There are cases were the state on the server might result in errors that then require user input to correct. After that the query is rerun like normal but then the client has even less information this time when deciding if it should retry with network than it did when deciding if it should cache because the original errors are of course no longer returned with cache hit. 🥺

Selective caching of fields based on `GraphQLError`s could also be an interesting feature exposed by a `cachePolicy` option.

**Comment by JoviDeCroock** [comment]
We'll need a bit more information, that user input is that a mutation? If that is then that solves the caching problem since a mutation results in a refetch or gives you the possibility to alter the cache. User input for a query would mean that the variables change so that means it also shouldn't be a cache hit since we normalise by query name and variables.

There seems to be a missing key part in what you're describing.

**Comment by protometa** [comment]
In my case it's a token returned from a mutation that goes in the header of the query requests, so it's out-of-band for the cache. But even with completely in-band scenarios where there are cases were the query variables wouldn't change and the mutation wouldn't alter the cache in the right way. I don't always have complete control over the server code either.

**Comment by kitten** [comment]
Ok, let me recap that. For authentication the mutations are indeed out-of-band, like you mentioned. However, I wouldn’t regard results with auth errors as valid results. This exchange demonstrates an authentication pattern that helps with this: https://gist.github.com/kitten/6050e4f447cb29724546dd2e0e68b470

Together with the retry exchange no errored results would reach the Uinifbits set up correctly. Alternatively, the retry could be integrated into the `authExchange` so that the failed result is still returned while a new one is being retried.

Mutations not altering the cache in the right way is mitigated by the update configuration. It’s offloaded to the user-land to define a mutation’s behaviour and how it affects the cache.

Even then, the resolvers could be used to disallow `null` values on certain fields of you need to disallow them and they aren’t marked as non-null by the API you don’t control.

Certainly we could allow you to configure that errored fields aren’t cached. Let’s ignore the complexity of the `GraphQLError` format for a moment and suppose you had an easy config to say “if this field on this query result from the server is `null` and has an error attached to it, don’t cache it.”

Now, suppose the first result succeeds, another query triggers, this will immediately start fetching.  That’s randomly duplicate work. We don’t even know whether we’d succeed this time. If we deemed it a cache miss we’d be refetching infinitely. If we have schema awareness turned on, then the field (because it’s optional) would still be left out and we’d be infinitely refetching.

So as you can see, with our mantra of accurately reflecting server state internally, there’s no reconcilable option to make this happen 😅

But we do have the solutions from above and have plenty of options:

- If we don’t control the schema, add a resolver that disallows `null` and transforms the result
- Use `reexecuteQuery` from the hook (or the equivalent in other frameworks) to refetch in your business logic / UI when you know it’s safe to retry
- Add an exchange that alters the results to adhere to what you expect (throw away the result’s data if an unexpected error occurs)
- Add an exchange that sends a `network-only` retry in the background while the partial result is shown
- Add the `retryExchange` to retry instead of “accepting” the partial result
- If this is an auth problem: Use the `authExchange` pattern from the Gist to ensure that we authenticate before fetching (and handle retries gracefully)
- If a mutation provides the data that was leading to the error and the mutation won’t update the query, manually provide an updater function to make sure it does, so that the query refetches (worst case: `cache.invalidate` is your friend 😇)

So depending on the problem, I’m sure we can find a solution here 🌟

**Comment by protometa** [comment]
I really appreciate the detailed auth example but honestly it's a bit much just to avoid a cached error null, which I'll probably run into again in other places. I ended up going with an extra exchange that nukes data when there are errors in order to dodge the cache.

Being able to see whatever data there is while disabling caching on errors would be more ideal but this just works for now.
