### ISSUE TITLE
question: access to graphcache directly

### ISSUE THREAD

**Issue by wuweiweiwu** [FormidableLabs/urql#829]
we have currently implemented a way to getting normalized entities from our graphql queries using a mix or `normalizr` and `@apollo/client` `readFragment` however, we'd like to move to `urql` for our graphql client.

One major difference that Ive noticed is that `readFragment` is only available within the graphcache resolver and cannot be access directly (ie: inside a component) whereas apollo exposes `client.readFragment` directly

Following up on discussions from https://github.com/FormidableLabs/urql/issues/85 and https://github.com/FormidableLabs/urql/issues/317. is there a way to access the cache directly and/or use `readFragment` directly?

**Comment by kitten** [comment]
We’ve previously experimented with that idea, but fundamentally it is unlikely to be implemented at this point because there isn’t a sensible API we could come up with that makes good guarantees. Both in terms of not _coupling_ this API to only work with Graphcache, and being able to infer where this entity comes from.

Graphcache doesn’t support this because its job is to accurately reflect the schema on the server. This means that queries must be runnable against the server when they’re executed against the cache, and queries / results from the server will always be accurately reflected by Graphcache. This is a powerful guarantee that makes it unlikely that state goes out of sync.

I’m wondering what your use-case I and whether it could actually be resolved with a cache resolver?

**Comment by wuweiweiwu** [comment]
our use case is centered around the goal of not passing large nested objects around and instead get it from the graphql client cache when needed via `readFragment` and `normalizr` but I think a possible workaround for us would just be a custom entity cache that is written to in a graphcache resolver.

another solution could be just using the data from the urql directly but we'd have to figure out a solution for deeply nested objects & TypeScript mapping of generated graphql types -> client types

**Comment by kitten** [comment]
I think this is a problem we do believe in, but it’s a problem we approach very differently, hence we haven’t come up with a solution yet that satisfies our requirements and expectations.

Generally, as applications grow with GraphQL, what we often like to see is that presentational components are wrapped in “dats mapping components” which only have two responsibilities: Define a fragment that satisfies all data requirements of the presentational components, and accept this fragment data as a prop and pass it on.

This pattern can be extremely successful and effective, because it layers on top of the visual aspects and logic of an application. These components are free to be extended with mutations or other pieces of business logic that don’t have to mix with UI concerns.
It’s a general pattern in componentised apps that mixes well with GraphQL.

A tool called “fraql”, I believe, attempted to make this simpler and more effective but falls short of integrating well with a library that actually executes GraphQL, a GraphQL client.

So at this point it becomes clear that our goals are really aligned, but we don’t want two things from this:

- We don’t want this behaviour to be implemented using an escape hatch. Subtle AI design choices steer how core is written, and an escape hatch that allows you to extract arbitrary data (direct `cache` / `store` access in Graphcache with the same API) allows you to arbitrarily read data where it goes against what GraphQL is good at. We go against defining data relationships.
- We don’t want this pattern to become boilerplate. It should be seamless and lead to the architecture described above intuitively.

This leads me to this: https://github.com/FormidableLabs/urql/issues/317

We had an early on expression of this desire, but no good API that leads to the above and isn’t just restricted to normalised caching.
I hope that makes sense 😅

I do want to make sure that we find an escape hatch in the meantime for you, but it’d be desirable for this to not become the norm, but just an escape hatch.
The resolvers approach is definitely one way, but you do risk running out-of-sync with Graphcache data, since you’re storing in what is assumed to be a side-effect-less read.
Another alternative for you would be to use `client.readQuery` and supplying resolvers and fields for individual items (which presumably most schemas will have), so that you can drill down into an item that you know you’ve fetched earlier.

**Comment by wuweiweiwu** [comment]
I see! we've briefly explored the fragment approach but failed to find a way to elegantly handle recursive graphql types but i think its worth another try. I agree that its an effective pattern that meshes well with component based ui architectures.

that totally makes sense! as the default document cache cannot unlock a first class fragment api

I wonder if its possible to expose the `cache` instance as a property somehow like `__dangerousDontUseCacheInstance` im also happy to contribute sometime to further #317 

Thanks for the detailed response! much appreciated!

**Comment by kitten** [comment]
We've built-in warnings actually and mechanisms that are very tailored towards a normal query flow, which ensure things like commutative cache updates and consistent cache data towards server data.
So to have an escape hatch would not only go against that but would probably require a new API layer and a bunch more code which pushes the bundle size.

We haven't yet found a lot of use cases that require us to go down this road, especially since GraphQL schemas typically cater for the UI, i.e. direct fragment access should not be necessary if the `Query` has query fields for all individual types.

I'll close this for now if that's alright :) but happy to discuss this more in RFCs
