### ISSUE TITLE
Support @defer and @live

### ISSUE THREAD

**Issue by krvajal** [FormidableLabs/urql#830]
@defer is a directive for streaming GraphQL responses from the server to the client.

By streaming the response, the server can send the most critical (or most available) data first, following up with secondary data shortly afterward.

@defer was first described by [Lee Byron at React Europe 2015](https://youtu.be/ViXL0YQnioU?t=768) and got experimental support in [Apollo in 2018](https://blog.apollographql.com/introducing-defer-in-apollo-server-f6797c4e9d6e)

**Comment by kitten** [comment]
I don’t think this is ready to be picked up yet. In theory it’d require just more exchanges delivering updates results over time and handling different protocols (event streams likely) but support is shaky.

It’d be great to add the proposal spec change link here, but I haven’t found it yet

**Comment by krvajal** [comment]
I tried to look it up but couldn’t find it either.
Even if this is something that can not be worked on right now it may make sense to keep the issue open

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by kitten** [comment]
I think we'll have to close this for now, if there's nothing to go on yet. There's no possible implementation plan or way forward yet, including on some supporting infrastructure, so even if we decided to go ahead with this now, reaping the benefits of this would be hard, especially since I doubt that with this spec even, there'd be a marginal benefit on most GraphQL setups / servers.

We can always come back to this once it's ready :)
