### ISSUE TITLE
Create Smart List component

### ISSUE THREAD

**Issue by kenwheeler** [FormidableLabs/urql#84]
For that sweet boy @mxstbr

**Comment by mxstbr** [comment]
Yes please! 😍

**Comment by kitten** [comment]
I think this would really pair well with the fragment-level cache idea that I've now finally written (haha) https://github.com/FormidableLabs/urql/issues/85

**Comment by kenwheeler** [comment]
Sure. Actually, before I take a crack at it, @mxstbr did you have a high level checklist of details you'd like included?

**Comment by kitten** [comment]
Hm, I'm not sure whether it'd make sense to "overload" the render prop's object with so many parameters, but I think this makes a lot of sense otherwise. Maybe we need a flexible description of the fetching logic though. I agree that Relay-style cursors are popular, but sometimes cursors and/or pagination are implemented in subtly different ways, and I'd hate to force a "one true structure" on people. Maybe we can find sth that uses the Relay-style connection cursors by default though?

Regarding the render prop object, maybe we can do:

```js
['nextPage' | 'prevPage']: {
  loading: boolean,
  error?: CombinedError,
  data: T
}
```

**Comment by jpstrikesback** [comment]
To that sentiment re strict Relay @kitten, I'd like to try this with an AppSync API without strict Relay connection spec, just your run of the mill after cursors :), and it would be nice to not enforce a specific spec, though a default is nice too. Anyways, there's my toonie's-worth, I don't want to interrupt something actually happening with these thoughts :)

**Comment by mxstbr** [comment]
The Relay connection spec is convention of where to put cursors and which arguments to pass depending on which direction you want to go, right? It'd be great if it worked out of the box with that since it's pretty widely used. That being said, you can probably make an abstraction that allows users to reduce the first/last item to arguments for the `fetchPage` methods, if that makes sense?

**Comment by jpstrikesback** [comment]
Yeah, totally, and fake a PageInfo/hasNext/PreviousPage?

**Comment by jpstrikesback** [comment]
(Although I'm not quite sure how off the top of my head to fake that in a nice way)

**Comment by kitten** [comment]
Currently there are no plans anymore to implement this as a component. However, there are plans to implement a normalised cache exchange for v1. I'll close this issue for now, but feel free to open new issues with new ideas :+1: I'll leave this with the vague promise: There will be normalised caching 😆
