### ISSUE TITLE
next-urql: MultiPartFetchExchange not working

### ISSUE THREAD

**Issue by BjoernRave** [FormidableLabs/urql#853]
The multipartfetchexchange is not working in combination with next-urql.

It keeps sending `application/json` requests

Reproduction: https://codesandbox.io/s/github/BjoernRave/next-urql-multipart

**Comment by JoviDeCroock** [comment]
Hey @BjoernRave 

I fixed your sandbox for you, this can be confusing since we already updated our docs for the new major of `next-urql`.

For now exchanges are the second argument to `withUrqlClient`, you need to take the argument in account, [working sandbox](https://codesandbox.io/s/peaceful-dream-6x4l9?file=/pages/index.js).

Example function:

```
const mergeExchanges = (ssrExchange) =>
  process.browser
    ? [
        dedupExchange,
        cacheExchange,
        ssrExchange,
        multipartFetch,
      ]
    : [
        dedupExchange,
        cacheExchange,
        multipartFetch,
      ];
```

**Comment by BjoernRave** [comment]
ahh, upps I messed it up then. Thanks for the clarification

**Comment by kitten** [comment]
Sorry about that! We’ve kind of slipped in our release schedule and merged a PR that actually altered the docs and needed to wait 😅
