### ISSUE TITLE
Populate Exchange docs not up to date?

### ISSUE THREAD

**Issue by BjoernRave** [FormidableLabs/urql#867]
Today I tried to use the `populateExchange`. According to the docs you can just add it to the exchanges array and it works, but according to the types you need to pass in the schema.

Also I tried generating my schema with https://github.com/dotansimha/graphql-code-generator, but when I tried to provide it to either `graphcache` or `populateExchange` I get the following error: 
```
(property) PopulateExchangeOpts.schema: IntrospectionQuery
Type '{ __schema: { description: any; queryType: { name: string; }; mutationType: { name: string; }; subscriptionType: any; types: ({ kind: string; name: string; description: any; fields: any; inputFields: ({ ...; } | { ...; })[]; interfaces: any; enumValues: any; possibleTypes: any; } | ... 5 more ... | { ...; })[]; dire...' is not assignable to type 'IntrospectionQuery'.
  The types of '__schema.queryType' are incompatible between these types.
    Property 'kind' is missing in type '{ name: string; }' but required in type 'IntrospectionNamedTypeRef<IntrospectionObjectType>'.ts(2322)
getIntrospectionQuery.d.ts(154, 12): 'kind' is declared here.
populateExchange.d.ts(4, 5): The expected type comes from property 'schema' which is declared here on type 'PopulateExchangeOpts
```

Another potential problem with the populate exchange and graphql code generator is, that I get this error when trying to generate without providing a subset, but just `@populate`, which is probabaly an issue I should open on their repo:

```
GraphQLError: GraphQLDocumentError: Field "deleteOneMovement" of type "Movement!" must have a selection of subfields. Did you mean "deleteOneMovement { ... }"?
```

**Comment by JoviDeCroock** [comment]
The problem with the schema is purely a typing discrepancy, we'll look into that but for now it should work if you just use `as any` which isn't ideal.

The last issue is related to `gql-code-generator` more than us I think

**Comment by BjoernRave** [comment]
okay I will open an issue on their repo

**Comment by schmod** [comment]
The graphql-code-generator issue is actually happening because they're validating the input documents against the standard graphql-js validation suite, and it violates the [ScalarLeafsRule](https://github.com/graphql/graphql-js/blob/b12dcffe83098922dcc6c0ec94eb6fc032bd9772/src/validation/rules/ScalarLeafsRule.ts) validation.  

You can work around it by adding `skipDocumentsValidation: { ignoreRules: ['ScalarLeafsRule'] }` to the codegen config.

It might be worth updating urql's own documentation to note that use of the `@populate` directive will (intentionally) produce GraphQL documents that do not conform to this validation rule.
