### ISSUE TITLE
Calling async function before retry

### ISSUE THREAD

**Issue by haswalt** [FormidableLabs/urql#878]
N.B. I would ask on spectrum but appears to be broken.

urql version & exchanges: 1.9.8 - default exchanges

I'm currently working through the problem of refreshing auth tokens and then retrying failed requests. The problem with refreshing tokens is that they are async requests. I was hoping to drop in a method into the retry exchange to support an async "before" function but i'm struggling to get my head round the right sources.

My current attempt is a clone of the retry exchange with a new source fromPromise merged into the result$ pipe.

Any help or pointers would be appreciated.

**Comment by kitten** [comment]
I do have a gist here that shows how to implement an `authExchange`, which sounds like what you're looking for: https://gist.github.com/kitten/6050e4f447cb29724546dd2e0e68b470

We haven't converted this into a recipe / guide in the docs yet. There's some more details here in this Spectrum thread: https://spectrum.chat/urql/help/handling-jwt-token-and-refresh-token-with-next-urql~adeb2820-8d10-4605-bfef-d8c9182907e7

**Comment by haswalt** [comment]
Thanks @kitten I did see that on spectrum now it's working again. The difference in my scenario is that the token has expired comes back from our graph endpoint as an error extension so we sort of need to hook into retry to handle it in the error callback.

**Comment by kitten** [comment]
So the `retryExchange` shouldn't handle it, as it's not responsible for authentication.
The expiration error should be picked up by the `authExchange` (since everyone does auth a little differently we only have the Gist template above) and the exchange there should run the refresh logic;

You can kind of swap around the logic in the `retryExchange` to instead also include a separate "refresh and retry" loop. I can get you a different Gist to get this done, since we've already helped someone implement this (it's closed source so I may only be able to get this to you tomorrow)

**Comment by haswalt** [comment]
That sounds exactly like what i was attempting to do. thanks.

Gist would be really appreciated. We've recently moved over from apollo so getting my head round things is a little tricky.

**Comment by kitten** [comment]
Here's a gist of the general pattern you may want to try: https://gist.github.com/kitten/6ea667b704ae529f5604c7f1229bdeaf

It covers a lot of edge cases, like:
- Retrying on error
- Having some space to proactively check invalid tokens (if you're willing to add that)
- Async initialisation
- Refreshing with mutations
- etc

**Comment by haswalt** [comment]
Thanks so much for that, super cool that you went out of your way to help out!.
