### ISSUE TITLE
RFC: Avoid persisted fetch queries hashing in the browser. Compile it at build time! ☺

### ISSUE THREAD

**Issue by frederikhors** [FormidableLabs/urql#886]
## Summary

Avoid persisted fetch queries hashing in the browser. Compile it at build time! ☺

## Proposed Solution

As stated here https://github.com/apollographql/apollo-link-persisted-queries#build-time-generation:

> If you want to avoid hashing in the browser, you can use a build script to include the hash as part of the request. Then you pass a function to retrieve that hash when the operation is run. This works well with projects [like this](https://github.com/leoasis/graphql-persisted-document-loader) which uses webpack to generate the hashes at build time.
> 
> If you use the above loader, you can pass `{ generateHash: ({ documentId }) => documentId }` to the `createPersistedQueryLink` call.

What do you think, awesome guys?

**Comment by kitten** [comment]
I'm not sure if this would actually have a large impact given that the cost of hashing these queries should be rather small. We haven't even added caching for those hashes yet, because of that.

If GraphQL Code Generator, which already has support for urql, supports this though, this could be done using the existing API 🤔

**Comment by frederikhors** [comment]
> cost of hashing these queries should be rather small 

It can be costly on small devices.

Please.

☺

**Comment by JoviDeCroock** [comment]
I mean essentially this is already possible with the `generateHash` option, if your `gql` compile time for queries already includes a hash you can use that.
