### ISSUE TITLE
[next-urql] Next + Redux + urql runs Suspense-behavior in server.

### ISSUE THREAD

**Issue by wodnjs6512** [FormidableLabs/urql#920]
When combining Next + Redux + urql in certain manner looks like suspense(such as returning different view depending on redux store value with useSelector (redux hooks)), server runs as if code asserted Suspense.

If I use useState instead of useSelector, then everything works fine.

I spent some time looking over the source code of next-urql, https://github.com/FormidableLabs/urql/blob/main/packages/next-urql/src/with-urql-client.tsx @ line 93, initUrqlClient includes hardcoded parameter for Suspense usage as below.

```javascript
const urqlClient = initUrqlClient(clientConfig, true);
```

Would there be any chance of fixing this bug? It would be nice to handle this with parameter or function.

** Guess this might be related to https://github.com/FormidableLabs/urql/issues/916 **

urql version & exchanges:
- urql 1.9.8
- next-urql 1.0.2
- next.js 9.4.4

**Steps to reproduce**
Take a look at the below codeSandbox
https://codesandbox.io/s/hardcore-mcnulty-1c1vv

**Expected behavior**
Suspense must not run in Server Side render

**Actual behavior**
Guessing Suspense-like code runs in server preventing server to render properly

**Comment by JoviDeCroock** [comment]
The main reasoning behind that hardcoded `truthy` value there is to let the `init` know we can or can't bind `suspense` since this only has to be active when `options.ssr` is true or we have `getInitialProps` (we use this for `ssr-prepass`). 

As you can see this `truthy` value does not imply a 100% guarantee of `suspense` https://github.com/FormidableLabs/urql/blob/main/packages/next-urql/src/init-urql-client.ts#L17 since we prepass here all boundaries should have been resolved resulting in no suspense behavior on the server.

The error in #916 seems similar in the essence that this check does not correctly work when using with `_app` rather than on page/component level. I'll look into this

**Comment by kimorkim** [comment]
This issue occurs when the `useQuery` runs after `ssr-prepass`.
Due to the use of `redux`, the server will be rendered twice.
`ssr-prepass` handles suspence, but it does not work after `ssr-prepass` has been used.
If the `useQuery` is run for the first time after `ssr-prepass` on the server, a separate action seems necessary.

**Comment by JoviDeCroock** [comment]
I've dug deeper into both this and the other issue concerning `getServerSideprops` and reached the conclusion that this case is going to be really hard/impossible to support given the current API.

Formerly we only had `getInitialProps` which would be available on the component, so we could detect the presence of this and use where/when needed. Now with `getStaticProps` being a function that we export from the file we can't effectively couple these. This means when we run our `prepass` function to resolve our queries we won't have these injected props they'll be `undefined`.

This means that we execute our query with `undefined`, after that `next.js` will execute `renderToString` and use these functions to inject additional props. Now all of a sudden we'll see new variables on `useQuery` making it execute again, however we are in a regular `renderToString` meaning that because this new query dispatches and throws a Suspense boundary the server crashes.

**Comment by FireworksX** [comment]
I got same problem `ReactDOMServer does not yet support Suspense.` because between `await ssrPrepass()` and `ReactDOM.renderToString()` some variable has changed.

Example: 
```
{
  lang: router.getParam('langSlug'),
  sportSlug: router.getParam('sportSlug'),
  dateNow: dayjs().format(`YYYY-MM-DD HH:mm:ss`), // Problem here
  matchesLimit: 10
}
```

While running  ssrPrepass `dateNow` has changed and when `renderToString` calling, `useQuery` try `createRequest` generate new queryId and can`t find him in cache and then `throw Promise` but *ReactDOMServer does not yet support Suspense*
