### ISSUE TITLE
Consider exporting URQL as UrqlClient instead of Client

### ISSUE THREAD

**Issue by wtrocki** [FormidableLabs/urql#928]
Client is simply to generic and it clashes many times, causing confusion etc. 
I have been using `as UrqlClient` in last 6 projects. This can be done while leaving old Client for backward compatibility.

**Comment by kitten** [comment]
We've been thinking about this, however there are mixed packages out there with the same problem that approach this with mixed solutions. This is because it's unclear how far one should go. Does our `CombinedError` become `UrqlCombinedError`? Does Graphcache's `Data` type become `GraphcacheData` or even `UrqlData`?

Overall we found it more helpful to consistently name things clearly and rely on people importing it with an alias, e.g. `Client as UrqlClient` or `Provider as UrqlProvider`. We find this especially acceptable since it's rare to import things where names collide, which will namely be `Provider`, `Context`, and `Client`.

**Comment by wereHamster** [comment]
You can also import * as URQL and then use <URQL.Client>
