### ISSUE TITLE
Ability to be able retrieve network request status code.

### ISSUE THREAD

**Issue by wtrocki** [FormidableLabs/urql#929]
I have been working with URLQL and in many cases when getting error from server I would like to asses it (networkError) based on the status code. Would be possible to export status code to URLQL (or if I missed that feature - document it in docs)

**Comment by kitten** [comment]
Hiya 👋

The `statusCode` is available on the `CombinedError`, since it carries the whole `FetchResponse` on `response`: https://github.com/FormidableLabs/urql/blob/8033b9bc386740d959ee398ba40def05234b79fd/packages/core/src/utils/error.ts#L45

This isn't highlighted as much since we can't guarantee that every error is going to originate from a fetch request or is going to carry a response. However you can use that to assess the code.

It isn't as common to use HTTP status codes with GraphQL, except for some authentication errors where we'd actually recommend a `GraphQLError` with an `extensions` code, but you should be able to rely on `CombinedError#response` consistently

**Comment by wtrocki** [comment]
I build datastore based on URQL where by default we inspect error code to decide about the fate of the replication parcel so my use cases are different. Thank you for your quick response! Got all the information.
