### ISSUE TITLE
GraphQL Subscriptions

### ISSUE THREAD

**Issue by cross311** [FormidableLabs/urql#93]
Looking at the todos for the project, there is nothing around subscriptions.

Are there any plans to add subscription support or at least giving a pointer for if you need subscriptions do not recommend this project?

**Comment by kitten** [comment]
Yes :tada: It's coming in the next urql release, urql v0.3! :100: https://github.com/FormidableLabs/urql/pull/72

It'll be usable via a "subscription exchange". Exchanges are like links in Apollo but build our fundamental query pipeline where any flow of queries might be handled/redirected/altered. The subscription exchange will be adaptable so that it's agnostic to the transport layer used, as there is no standard for GraphQL subscriptions via websockets / other async transport protocols.

More info about how it's used can be found here: https://github.com/FormidableLabs/urql/pull/75

There'll also be support for using Apollo Links as urql exchanges handling requests, so you could also directly plug Apollo's request + subscription handling into urql in the future: https://github.com/kitten/urql-exchange-apollo

I'll leave this issue open so that we can track it for the release

**Comment by kitten** [comment]
v1 is released now which means this issue was resolved / is out-of-date 👌

Some docs and a proper announcement for v1 are still in progress in pending. It's completely usable so far but the API has changed, so I have to ask for some more patience, but everything will be ready quite soon ✌️
