### ISSUE TITLE
urql subscriptions examples depends on a library not compatible with es module based browser build

### ISSUE THREAD

**Issue by wighawag** [FormidableLabs/urql#946]
In the following page https://formidable.com/open-source/urql/docs/advanced/subscriptions/
th example use `subscriptions-transport-ws` (https://github.com/apollographql/subscriptions-transport-ws) to create an exchange for graphql subscription

Unfortunately this library do not expose an `es module`. (see https://github.com/apollographql/subscriptions-transport-ws/issues/500) 

Do you have any library that would work

Note that I tried the following PR but fails for some other reason : https://github.com/apollographql/subscriptions-transport-ws/pull/508#issuecomment-680948054

urql version & exchanges:

@urql/core 1.12.3
subscriptions-transport-ws 0.9.18
graphql 15.3.0
wonka 4.0.14
@urql/devtools 2.0.2

**Steps to reproduce**

```
import {Client, defaultExchanges, subscriptionExchange} from '@urql/core';
import {devtoolsExchange} from '@urql/devtools';
import {SubscriptionClient} from 'subscriptions-transport-ws';

const subscriptionClient = new SubscriptionClient(process.env.THE_GRAPH_WS, {
  reconnect: true,
});

export default new Client({
  url: process.env.THE_GRAPH_HTTP,
  exchanges: [
    devtoolsExchange,
    ...defaultExchanges,
    subscriptionExchange({
      forwardSubscription(operation) {
        return subscriptionClient.request(operation);
      },
    }),
  ],
});
```

**Comment by kitten** [comment]
As long as you set up your bundled correctly this won't cause any issues (unless of course you're just using browser ESM support)

But overall, this is something we can't do anything about. `subscriptions-transport-ws` is de facto the standard GraphQL Subscriptions support library, at least for Apollo Servers, and it's just an example for us since that's what people expect to see.

So it doesn't affect our code and since it's just an example and not our library there's unfortunately nothing we can do to remedy this 😅

**Comment by wighawag** [comment]
By the way, I indeed use browser ESM support and I still did not find anyway to resolve the issue and have to skip using websocket unfortunately.
While I understand it might be out of scope of urql, it would be great if user of urql and esm module could benefit for websocket transport
