### ISSUE TITLE
[urql@1.10.1] Just broken

### ISSUE THREAD

**Issue by nghiepit** [FormidableLabs/urql#971]
Hi hi, it's me again.

Maybe it's just broken in `next-urql`.
```
Default Client: No client has been specified using urql's Provider.This means that urql will befalling back to defaults including making requests to `/graphql`.
If that's not what you want, please create a client and add a Provider.
```

Reproduction https://codesandbox.io/s/romantic-fast-8sise?file=/pages/index.js

**Comment by JoviDeCroock** [comment]
Could you try removing your `node_modules` and reinstall? This is most  likely due to your package manager deduplicating incorrectly.

**Comment by nghiepit** [comment]
I had tried `rm -rf node_modules` and reinstall.
And used `yarn-deduplicate` but both still broken.
After `yarn add next-urql`  again to force `urql`  to the same `1.10.1` version the problem has been resolved.

**Comment by kitten** [comment]
Sometimes this can be a little fiddly. We've determined that `next-urql` doesn't have a peer dependency on `urql` and instead a direct one which is probably making this worse. We'll have to clean that up on the next major bump of `next-urql`

**Comment by lukasluecke** [comment]
I am running into the same issue, however none of the proposed solutions solve it for me 😞 Anything else I can try?

**Comment by bubbaspaarx** [comment]
Check you are not using 'Provider' from react-redux.

**Comment by jshxr** [comment]
For anybody using a workspace/monorepo and still running into this issue:

**Make sure that the `createClient()` method is imported from the same `urql` dependency as any `useQuery` or `useMutation` hook.**

In my case, I was using a _yarn workspace_ and its _Plug'n'Play_ feature. `urql` was installed in two of the workspace packages.
The setup looked something like this:

### Package 1
`package.json`
```javascript
{
    // ...
    "dependencies": {
        // ...
        "urql": "^2.1.3",
    }
}
```
`index.ts`
```typescript
import { useQuery } from 'urql';
// ...
export const useSomeData = () => useQuery(SOME_DATA_QUERY);
```
### Package 2
`package.json`
```javascript
{
    // ...
    "dependencies": {
        // ...
        "urql": "^2.1.3",
        "next-urql": "^3.3.2",
        "package1": "workspace:*"
    }
}
```
`pages/_app.tsx`
```typescript
import { withUrqlClient } from 'next-urql';
import { useSomeData } from 'package1/data';

const App= () => {
    const data = useSomeData();
    // ...
};

export default withUrqlClient(/*...*/)(App);
```

`withUrqlClient()`, under the hood, used the `createClient()` method of the `urql` dependency installed in `package2`.
`useSomeData()`, on the other hand, used the `useQuery()` hook of the `urql` dependency installed in `package1`.

Therefore, the underlying [`Context.Provider` and `Context.Consumer`](https://github.com/FormidableLabs/urql/blob/4792f3411d3dcb3730ee91a6622020ebb2da751c/packages/react-urql/src/context.ts#L9-L10) didn't belong to the same `Context`, resulting in the error message.

Fixed it by removing `urql` and `next-urql` from `package2`, installing `next-urql` in `package1` and re-exporting `withUrqlClient`.

**Comment by kitten** [comment]
@jshxr Actually, to avoid duplicates we simply recommend deduplicating dependencies, specifically that's important for `@urql/core`. This can often be done by running `npx yarn-deduplicate` which updates the `yarn.lock` file and then running `yarn` again ✌️

**Comment by jshxr** [comment]
@kitten Running [`yarn dedupe`](https://yarnpkg.com/cli/dedupe/)(`yarn-deduplicate` only works with _yarn 1_) was one of the first things I tried after reading JoviDeCroocks answer, however the error didn't resolve.

My `.yarn/cache` also only features one urql (`urql-npm-2.1.3.zip`) and one @urql/core(`@urql-core-npm-2.4.1.zip`).
Maybe this has something to do with how PnP works? (I don't know how it works 😆)

**Comment by nianiam** [comment]
@jshxr I know this is an old closed topic, but just in case you haven't managed to figure out the mysteries of PnP here's a little bit of help troubleshooting PnP problems.

There are a couple of `yarn` CLI tools we can use to investigate how our dependencies are defined:
- `yarn why <package-name>`
	- This will show you _why_ a package has been installed. For example, which of your workspaces has it as a dependency.
	- Sometimes this is enough to figure out if there are multiple instances of a package by checking the hashes at the end of the output.
- `yarn info <package-name>`
	- This will show you package information including things like the package's dependencies but importantly _the number of instances in your code-base_.
	- We can also investigate the _peer dependencies of each instance_ using the `--virtuals` flag.
	- We can also use the `-A/--all` flag to check this from the top level of our monorepo.

```
-> yarn info urql -A --virtuals
├─ urql@npm:2.2.3
│  ├─ Instances: 2
│  ├─ Version: 2.2.3
│  │
│  └─ Dependencies
│     ├─ @urql/core@npm:^2.6.1 → npm:2.6.1
│     └─ wonka@npm:^4.0.14 → npm:4.0.15
│
├─ urql@npm:2.2.3 [5abd3]
│  ├─ Version: 2.2.3
│  │
│  └─ Peer dependencies
│     ├─ @types/graphql@* → ✘
│     ├─ @types/react@* → npm:17.0.4
│     ├─ graphql@^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0 || ^16.0.0 → ✘
│     └─ react@>= 16.8.0 → npm:17.0.2
│
└─ urql@npm:2.2.3 [5c718]
   ├─ Version: 2.2.3
   │
   └─ Peer dependencies
      ├─ @types/graphql@* → npm:14.5.0
      ├─ @types/react@* → npm:17.0.4
      ├─ graphql@^0.11.0 || ^0.12.0 || ^0.13.0 || ^14.0.0 || ^15.0.0 || ^16.0.0 → npm:15.8.0
      └─ react@>= 16.8.0 → npm:17.0.2
```

Here we can see the `urql` package has `@urql/core` and `wonka` as dependencies, but also `@types/graphql`, `@types/react`, `graphql` and `react` as peer dependencies. **In order for an instance to be the same, it's peer dependencies must also be satisfied**.

So, in this output, we need to add `@types/graphql` and `graphql` to the peer dependencies of whichever workspace corresponds to the hash [5abd3] (the crosses at the end of the line indicate this).

## What should you have done in your example?
Instead of removing `next-urql` and `urql` from package2, we should instead add `urql` to the peer dependencies of package 1 and also ensure _both_ packages have all of `next-urql` and `urql`'s peer dependencies satisfied by using `yarn info urql -A --virtuals`; preferably all with the same versioning.

## What if I can't control the dependencies?
If you're not the package maintainer, you can enforce dependencies using the `.yarnrc.yml` file. Here's yarn's [docs](https://yarnpkg.com/configuration/yarnrc) on that.

Yarn should really have a "how to troubleshoot" dependencies section because none of this is obvious...
